/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSquareTriangleCircleTriangleFill: {
  name: 'square-triangle-circle-triangle-fill';
  data: string;
} = {
  name: 'square-triangle-circle-triangle-fill',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M1 .5a.5.5 0 0 0-.5.5v6a.5.5 0 0 0 .5.5h6a.5.5 0 0 0 .5-.5V1A.5.5 0 0 0 7 .5H1Zm11.447.276a.5.5 0 0 0-.894 0l-3 6A.5.5 0 0 0 9 7.5h6a.5.5 0 0 0 .447-.724l-3-6ZM1.526 8.842A.5.5 0 0 1 2 8.5h4a.5.5 0 0 1 .474.342l1 3a.5.5 0 0 1 0 .316l-1 3A.5.5 0 0 1 6 15.5H2a.5.5 0 0 1-.474-.342l-1-3a.5.5 0 0 1 0-.316l1-3ZM12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`
};
