/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsBookmarkFill: {
  name: 'bookmark_fill';
  data: string;
} = {
  name: 'bookmark_fill',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 0.5C2.17157 0.5 1.5 1.17157 1.5 2V13.5382C1.5 14.5932 2.56037 15.3186 3.54367 14.9362L7.81878 13.2736C7.93534 13.2283 8.06466 13.2283 8.18122 13.2736L12.4563 14.9362C13.4396 15.3186 14.5 14.5932 14.5 13.5382V2C14.5 1.17157 13.8284 0.5 13 0.5H3Z" fill="#6E778C"/></svg>`,
};
