/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsTriangleUp: {
  name: 'triangle_up';
  data: string;
} = {
  name: 'triangle_up',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12 10H4L8 6L12 10Z" fill="currentColor"/></svg>`,
};
