/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsCheckerboard: {
  name: 'checkerboard';
  data: string;
} = {
  name: 'checkerboard',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#checkerboard_svg__clip0_430_11618)"><path fill-rule="evenodd" clip-rule="evenodd" d="M0.5 2C0.5 1.17157 1.17157 0.5 2 0.5H9H14C14.8284 0.5 15.5 1.17157 15.5 2V7V14C15.5 14.8284 14.8284 15.5 14 15.5H7H2C1.17157 15.5 0.5 14.8284 0.5 14V9V2ZM14 14.5H8.41465C8.46992 14.3436 8.5 14.1753 8.5 14V9C8.5 8.76882 8.4477 8.54986 8.35429 8.35429C8.54986 8.4477 8.76882 8.5 9 8.5H14C14.1753 8.5 14.3436 8.46992 14.5 8.41465V14C14.5 14.2761 14.2761 14.5 14 14.5ZM7.5 7C7.5 7.23118 7.5523 7.45014 7.64571 7.64571C7.45014 7.5523 7.23118 7.5 7 7.5H2C1.82468 7.5 1.65639 7.53008 1.5 7.58535V2C1.5 1.72386 1.72386 1.5 2 1.5H7.58535C7.53008 1.65639 7.5 1.82468 7.5 2V7Z" fill="currentColor"/></g><defs><clipPath id="checkerboard_svg__clip0_430_11618"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`
};
