/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSquareMinus: {
  name: 'square_minus';
  data: string;
} = {
  name: 'square_minus',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#square-minus_svg__clip0_389_13133)"><rect x="1" y="1" width="14" height="14" rx="1" stroke="#6E778C" stroke-linecap="round" stroke-linejoin="round"/><path d="M5 8H11" stroke="#6E778C" stroke-linecap="round" stroke-linejoin="round"/></g><defs><clipPath id="square-minus_svg__clip0_389_13133"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`,
};
