/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsTouchpad: {
  name: 'touchpad';
  data: string;
} = {
  name: 'touchpad',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M0.5 4C0.5 3.17157 1.17157 2.5 2 2.5H14C14.8284 2.5 15.5 3.17157 15.5 4V10V12C15.5 12.8284 14.8284 13.5 14 13.5H8H2C1.17157 13.5 0.5 12.8284 0.5 12V10V4ZM8.5 12.5H14C14.2761 12.5 14.5 12.2761 14.5 12V10.5H8.5V12.5ZM7.5 10.5V12.5H2C1.72386 12.5 1.5 12.2761 1.5 12V10.5H7.5ZM8 9.5H14.5V4C14.5 3.72386 14.2761 3.5 14 3.5H2C1.72386 3.5 1.5 3.72386 1.5 4V9.5H8Z" fill="#6E778C"/></svg>`,
};
