/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsCellphone: {
  name: 'cellphone';
  data: string;
} = {
  name: 'cellphone',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.5 2C2.5 1.17157 3.17157 0.5 4 0.5H12C12.8284 0.5 13.5 1.17157 13.5 2V9V14C13.5 14.8284 12.8284 15.5 12 15.5H4C3.17157 15.5 2.5 14.8284 2.5 14V9V2ZM12.5 2V8.5H3.5V2C3.5 1.72386 3.72386 1.5 4 1.5H12C12.2761 1.5 12.5 1.72386 12.5 2ZM12.5 9.5H3.5V14C3.5 14.2761 3.72386 14.5 4 14.5H12C12.2761 14.5 12.5 14.2761 12.5 14V9.5ZM8 13C8.55228 13 9 12.5523 9 12C9 11.4477 8.55228 11 8 11C7.44772 11 7 11.4477 7 12C7 12.5523 7.44772 13 8 13Z" fill="#6E778C"/></svg>`
};
