/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsLabelFill: {
  name: 'label_fill';
  data: string;
} = {
  name: 'label_fill',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_382_12920)"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.06202 0.503865C0.908918 0.484727 0.755554 0.537347 0.646451 0.646451C0.537347 0.755554 0.484727 0.908918 0.503865 1.06202L1.50387 9.06202C1.51765 9.17234 1.56782 9.27491 1.64642 9.35353L7.64639 15.3544C7.74016 15.4482 7.86734 15.5009 7.99995 15.5009C8.13256 15.5009 8.25975 15.4483 8.35352 15.3545L15.3535 8.35461C15.5488 8.15936 15.5488 7.8428 15.3536 7.64753L9.35359 1.64648C9.27496 1.56784 9.17237 1.51766 9.06202 1.50387L1.06202 0.503865ZM6 5C6 5.55229 5.55229 6 5 6C4.44772 6 4 5.55229 4 5C4 4.44772 4.44772 4 5 4C5.55229 4 6 4.44772 6 5Z" fill="#6E778C"/></g><defs><clipPath id="clip0_382_12920"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`
};
