/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSteamBoiler: {
  name: 'steam_boiler';
  data: string;
} = {
  name: 'steam_boiler',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#steam-boiler_svg__clip0_430_11246)"><path fill-rule="evenodd" clip-rule="evenodd" d="M5 0.5C4.72386 0.5 4.5 0.723858 4.5 1C4.5 1.27614 4.72386 1.5 5 1.5H8.5V5.5H5.5V4C5.5 3.72386 5.27614 3.5 5 3.5C4.72386 3.5 4.5 3.72386 4.5 4V5.5H4C3.72386 5.5 3.5 5.72386 3.5 6V8.5H2C1.72386 8.5 1.5 8.72386 1.5 9C1.5 9.27614 1.72386 9.5 2 9.5H3.5V10.51C3.46769 10.5034 3.43425 10.5 3.4 10.5H1C0.723858 10.5 0.5 10.7239 0.5 11V15C0.5 15.2761 0.723858 15.5 1 15.5H4H12C12.2761 15.5 12.5 15.2761 12.5 15V12.5H15C15.2761 12.5 15.5 12.2761 15.5 12V9C15.5 8.72386 15.2761 8.5 15 8.5H12.5V6C12.5 5.72386 12.2761 5.5 12 5.5H9.5V1C9.5 0.723858 9.27614 0.5 9 0.5H5ZM4.5 6.5H5H9H11.5V9V10.5H4.5V9V6.5ZM14.5 11.5H12.5V11V9.5H14.5V11.5ZM4.5 11.5H11.5V12V14.5H4.5V11.5ZM3.5 14.5V11.49C3.46769 11.4966 3.43425 11.5 3.4 11.5H1.5V14.5H3.5ZM12 4C12.5523 4 13 3.55228 13 3C13 2.44772 12.5523 2 12 2C11.4477 2 11 2.44772 11 3C11 3.55228 11.4477 4 12 4Z" fill="currentColor"/></g><defs><clipPath id="steam-boiler_svg__clip0_430_11246"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`,
};
