/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsArrowUpFromLine: {
  name: 'arrow_up_from_line';
  data: string;
} = {
  name: 'arrow_up_from_line',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M7.5 14.5H3C2.72386 14.5 2.5 14.7239 2.5 15C2.5 15.2761 2.72386 15.5 3 15.5H8H13C13.2761 15.5 13.5 15.2761 13.5 15C13.5 14.7239 13.2761 14.5 13 14.5H8.5V2.20711L12.6464 6.35355C12.8417 6.54882 13.1583 6.54882 13.3536 6.35355C13.5488 6.15829 13.5488 5.84171 13.3536 5.64645L8.35355 0.646446C8.15829 0.451184 7.84171 0.451184 7.64645 0.646446L2.64645 5.64645C2.45118 5.84171 2.45118 6.15829 2.64645 6.35355C2.84171 6.54882 3.15829 6.54882 3.35355 6.35355L7.5 2.20711V14.5Z" fill="#6E778C"/></svg>`,
};
