/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsMailOpen: {
  name: 'mail_open';
  data: string;
} = {
  name: 'mail_open',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#mail-open_svg__clip0_435_9004)"><path fill-rule="evenodd" clip-rule="evenodd" d="M7.75193 1.71761C7.90565 1.62977 8.09435 1.62977 8.24807 1.71761L14.1774 5.10581L8.23705 8.30446C8.08906 8.38415 7.91094 8.38415 7.76295 8.30446L1.82259 5.10581L7.75193 1.71761ZM1.5 6.06786V14C1.5 14.2761 1.72386 14.5 2 14.5H14C14.2761 14.5 14.5 14.2761 14.5 14V6.06786L8.71115 9.18493C8.26719 9.42399 7.73281 9.42399 7.28885 9.18493L1.5 6.06786ZM8.74421 0.849369C8.28306 0.585855 7.71694 0.585855 7.25579 0.849369L1.25579 4.27794C0.788429 4.545 0.5 5.04202 0.5 5.5803V14C0.5 14.8284 1.17157 15.5 2 15.5H14C14.8284 15.5 15.5 14.8284 15.5 14V5.58031C15.5 5.04202 15.2116 4.545 14.7442 4.27794L8.74421 0.849369Z" fill="currentColor"/></g><defs><clipPath id="mail-open_svg__clip0_435_9004"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`
};
