/* 🤖 this file was generated by svg-to-ts */

export type PrizmIcons16Type =
  | 'agenda_fill'
  | 'airplane_side_view'
  | 'airplane_top_view'
  | 'alarm_clock'
  | 'alarm_plus'
  | 'align_bottom'
  | 'align_center_h'
  | 'align_center_v'
  | 'align_center'
  | 'align_justify'
  | 'align_left'
  | 'align_right'
  | 'align_top'
  | 'ambulance_side_view'
  | 'android_pill'
  | 'android'
  | 'angle_left_right_arrows_down'
  | 'angle_left_right'
  | 'arrange_send_to_back'
  | 'array_fill'
  | 'arrow_bold_down'
  | 'arrow_bold_left'
  | 'arrow_bold_right'
  | 'arrow_bold_up'
  | 'arrow_daw'
  | 'arrow_down_between_lines'
  | 'arrow_down_from_double_line'
  | 'arrow_down_from_line'
  | 'arrow_down_in_circle_empty'
  | 'arrow_down_to_bracket'
  | 'arrow_down_to_double_line'
  | 'arrow_down_to_line'
  | 'arrow_down_wide_short'
  | 'arrow_down'
  | 'arrow_left_between_lines'
  | 'arrow_left_down'
  | 'arrow_left_from_bracket'
  | 'arrow_left_in_circle_empty'
  | 'arrow_left_up'
  | 'arrow_left'
  | 'arrow_right_between_lines'
  | 'arrow_right_down'
  | 'arrow_right_from_bracket'
  | 'arrow_right_in_circle_empty'
  | 'arrow_right_up'
  | 'arrow_right'
  | 'arrow_rotate_left'
  | 'arrow_rotate_right'
  | 'arrow_turn_down_left'
  | 'arrow_turn_down_right'
  | 'arrow_turn_left_down'
  | 'arrow_turn_left_up'
  | 'arrow_turn_right_down'
  | 'arrow_turn_right_up'
  | 'arrow_turn_up_left'
  | 'arrow_turn_up_right'
  | 'arrow_up_arrow_down_h'
  | 'arrow_up_arrow_down_v'
  | 'arrow_up_between_lines'
  | 'arrow_up_from_bracket'
  | 'arrow_up_from_double_line'
  | 'arrow_up_from_line'
  | 'arrow_up_in_circle_empty'
  | 'arrow_up_to_dotted_line'
  | 'arrow_up_to_double_line'
  | 'arrow_up_to_line'
  | 'arrow_up_wide_short'
  | 'arrow_up'
  | 'arrows_all_directions'
  | 'arrows_compare'
  | 'arrows_cross'
  | 'arrows_direction_to_the_lines'
  | 'arrows_inside'
  | 'arrows_left_right_brackets'
  | 'arrows_left_right_to_lines'
  | 'arrows_maximize'
  | 'arrows_minimize'
  | 'arrows_out'
  | 'arrows_repeat_h'
  | 'arrows_repeat_v'
  | 'arrows_rotate_h'
  | 'arrows_rotate_v'
  | 'arrows_shuffle'
  | 'arrows_swap_h'
  | 'arrows_swap_v'
  | 'arrows_up_down_to_lines'
  | 'at_sign'
  | 'audio_speakers'
  | 'award'
  | 'bag'
  | 'balloon'
  | 'ban'
  | 'bar_axis'
  | 'bar_basic'
  | 'bar_columns_axis_x'
  | 'bar_columns'
  | 'bar_histogram'
  | 'bar_square'
  | 'bar_stacked_axis'
  | 'bar_stacked'
  | 'barcode'
  | 'bars_sort'
  | 'bars'
  | 'battery_bolt'
  | 'battery_empty'
  | 'battery_exclametion_mark'
  | 'battery_full'
  | 'battery_half'
  | 'battery_minus'
  | 'battery_plus'
  | 'battery_quarter'
  | 'battery_three_quarters'
  | 'bdrv_administration'
  | 'bell_fill'
  | 'bell_plus'
  | 'bell_ring_fill'
  | 'bell_ring'
  | 'bell_slash'
  | 'bell'
  | 'bezier_curve'
  | 'bitcoin'
  | 'block_lines'
  | 'bluetooth'
  | 'boiler_hot_water_gas_and_oil'
  | 'boiler'
  | 'bold'
  | 'book_stack'
  | 'book_check'
  | 'book_closed'
  | 'book_open_plus'
  | 'book_open_re_arrow_left'
  | 'book_open_re_arrow_right'
  | 'book_open_text'
  | 'book_open_with_page'
  | 'book_open'
  | 'bookmark_check_fill'
  | 'bookmark_check'
  | 'bookmark_cross_fill'
  | 'bookmark_cross'
  | 'bookmark_fill'
  | 'bookmark_music_fill'
  | 'bookmark_music'
  | 'bookmark_plus_fill'
  | 'bookmark_plus'
  | 'bookmark'
  | 'border_all'
  | 'border_bottom'
  | 'border_center_h'
  | 'border_center_v'
  | 'border_inner'
  | 'border_left'
  | 'border_none'
  | 'border_outer'
  | 'border_right'
  | 'border_top_left'
  | 'border_top'
  | 'box_open_arrow_down'
  | 'box'
  | 'brackets_curly'
  | 'brackets_square'
  | 'broom'
  | 'browser'
  | 'brush'
  | 'bubble_message_add'
  | 'bubble_message_attention'
  | 'bubble_message_circle'
  | 'bubble_message_empty'
  | 'bubble_message_off'
  | 'bubble_message_question'
  | 'bubble_message_text'
  | 'bubble_message'
  | 'burn'
  | 'calculator_arrow_rotate_left'
  | 'calculator_function'
  | 'calculator'
  | 'calendar_blank'
  | 'calendar_check'
  | 'calendar_clock'
  | 'calendar_deleted'
  | 'calendar_event'
  | 'calendar_plus'
  | 'calendar_question'
  | 'calendar_range'
  | 'calendar_today'
  | 'calendar'
  | 'calibration_characteristics_zql'
  | 'camera_front'
  | 'camera_movie_cross'
  | 'camera_movie'
  | 'camera'
  | 'car_jeep_side_view'
  | 'car_light_side_view'
  | 'carbon'
  | 'carousel_fill'
  | 'cart_flatbed_container'
  | 'cart_plus'
  | 'cart'
  | 'cellphone_wireless'
  | 'cellphone'
  | 'charts_iqc_zql'
  | 'check_double'
  | 'checkerboard'
  | 'chek'
  | 'chevron_down_to_double_line'
  | 'chevron_down'
  | 'chevron_left'
  | 'chevron_mini_left'
  | 'chevron_mini_right'
  | 'chevron_right_above_double_line'
  | 'chevron_right'
  | 'chevron_up'
  | 'chevrons_double_down'
  | 'chevrons_double_left'
  | 'chevrons_double_mini_left'
  | 'chevrons_double_mini_right'
  | 'chevrons_double_right'
  | 'chevrons_double_up'
  | 'chevrons_inside_horizontally'
  | 'chevrons_inside_vertically'
  | 'chevrons_outside_horizontally'
  | 'chevrons_outside_vertically'
  | 'circle_chek_empty'
  | 'circle_chek_fill'
  | 'circle_exclamation_empty'
  | 'circle_exclamation_fill'
  | 'circle_in_hexagon'
  | 'circle_info_empty'
  | 'circle_info_fill'
  | 'circle_music'
  | 'circle_plus_fill'
  | 'circle_plus'
  | 'circle_question_empty'
  | 'circle_question_fill'
  | 'circle_square_fill'
  | 'circle_square_in_square'
  | 'circle_square'
  | 'circle_xmark_fill'
  | 'circle_xmark'
  | 'circles_line_left_up_circle_right_down_fill'
  | 'circles_line_left_up_circle_right_down'
  | 'clapperboard_cross'
  | 'clapperboard_open'
  | 'clock_add'
  | 'clock_arrow_down'
  | 'clock_arrow_right'
  | 'clock_arrow_up'
  | 'clock_deleted'
  | 'clock_exclamation'
  | 'clock_line_end'
  | 'clock_rotate_left'
  | 'clock_rotate_right'
  | 'clock'
  | 'cloud_arrow_down'
  | 'cloud_arrow_up_inside'
  | 'cloud_arrow_up'
  | 'cloud_check'
  | 'cloud'
  | 'code_download'
  | 'code_simple'
  | 'code'
  | 'collage_fill'
  | 'collection'
  | 'collector'
  | 'column_fill'
  | 'column'
  | 'compass'
  | 'component'
  | 'concrete_mixer_side_view'
  | 'container_v_1'
  | 'container_v_2'
  | 'containers'
  | 'control_charts_zql'
  | 'copy_column'
  | 'copy_row'
  | 'copy'
  | 'crane'
  | 'credit_card_plus'
  | 'credit_card_slash'
  | 'credit_card'
  | 'crop'
  | 'crosshairs_dot'
  | 'crosshairs_simple'
  | 'cube_empty'
  | 'cube_fill'
  | 'cubes'
  | 'dashboard_fill'
  | 'dashboard_variant_fill'
  | 'database_chek'
  | 'database_json'
  | 'database_magnifying_glass'
  | 'database_minus'
  | 'database_plus'
  | 'database_sql'
  | 'database_xmark'
  | 'database'
  | 'day_fill'
  | 'decagram_chek_empty'
  | 'decagram_chek_fill'
  | 'decagram_exclamation_empty'
  | 'decagram_exclamation_fill'
  | 'default_ico'
  | 'delete_content'
  | 'desktop_tower'
  | 'discrete_set'
  | 'dollar_slash'
  | 'dollar'
  | 'doughnut'
  | 'droplet_slash'
  | 'droplet'
  | 'early_version'
  | 'earth'
  | 'editor_alfavit'
  | 'editor_down'
  | 'editor_right'
  | 'electrics'
  | 'ellipsis_grid'
  | 'ellipsis_h'
  | 'ellipsis_v'
  | 'energy_check'
  | 'energy_slash'
  | 'energy'
  | 'equipment_zql'
  | 'eraser'
  | 'ethernet'
  | 'exchanger'
  | 'exclamation'
  | 'eye_closed'
  | 'eye_slash'
  | 'eye'
  | 'face_frown'
  | 'face_smile'
  | 'factory_pipe'
  | 'factory_pipes'
  | 'factory'
  | 'fan'
  | 'file_arrow_down_left'
  | 'file_arrow_down'
  | 'file_arrow_up'
  | 'file_arrow'
  | 'file_arrows_up_right'
  | 'file_camera'
  | 'file_cross_out'
  | 'file_cross'
  | 'file_doc'
  | 'file_docx'
  | 'file_dot'
  | 'file_empty'
  | 'file_exclamation'
  | 'file_eye'
  | 'file_filled'
  | 'file_image'
  | 'file_magnifying_glass'
  | 'file_minus'
  | 'file_music'
  | 'file_pdf'
  | 'file_pen'
  | 'file_play'
  | 'file_plus'
  | 'file_ppt'
  | 'file_pptx'
  | 'file_txt'
  | 'file_up_right'
  | 'file_xls'
  | 'file_xlsx'
  | 'files_mode'
  | 'fill'
  | 'film_cross'
  | 'film'
  | 'filter_gear'
  | 'filter_ontology'
  | 'filter'
  | 'finance_scanner'
  | 'fire'
  | 'flag_fill_red'
  | 'flag_fill'
  | 'flag'
  | 'flask_round_potion'
  | 'flask'
  | 'floppy_cross_out'
  | 'floppy_cross'
  | 'floppy_pen'
  | 'floppy_star'
  | 'floppy'
  | 'folder_open'
  | 'folder_underline_minus'
  | 'folder_underline_plus'
  | 'folder_underline'
  | 'folder_arrow_down_left'
  | 'folder_arrow_down'
  | 'folder_arrow_up_right'
  | 'folder_cross'
  | 'folder_dot'
  | 'folder_minus'
  | 'folder_plus'
  | 'folder'
  | 'forvard_step'
  | 'forward'
  | 'fuel_oil_tank'
  | 'function'
  | 'gantt'
  | 'gas_monitoring'
  | 'gas_pump'
  | 'gas'
  | 'gauge'
  | 'gear_5_edge'
  | 'gear_8_edge'
  | 'gear_cooling'
  | 'generator'
  | 'gift'
  | 'git_lab'
  | 'globe'
  | 'grid_fill'
  | 'grid'
  | 'grip_dots_vertical'
  | 'hard_drive_outline'
  | 'hash_dash'
  | 'hash'
  | 'hashtag'
  | 'headline_fill'
  | 'headphones'
  | 'heart_empty'
  | 'heart_fill'
  | 'helicopter_side_view'
  | 'hexagon_exclamation_empty'
  | 'hexagon_exclamation_fill'
  | 'hexagon_fill'
  | 'hexagon'
  | 'hexagons_axis'
  | 'hexagons'
  | 'histogram_axis'
  | 'house_mini'
  | 'house'
  | 'image'
  | 'indent_arrow_left'
  | 'indent_arrow_right'
  | 'infinity'
  | 'info'
  | 'input_device'
  | 'instagram'
  | 'italic'
  | 'key'
  | 'keyboard_close'
  | 'keyboard'
  | 'label_cross'
  | 'label_exclamation_mark'
  | 'label_fill'
  | 'label_magnifying_glass'
  | 'label_plus'
  | 'label_question'
  | 'label_text'
  | 'label'
  | 'lan_connect'
  | 'lan_disconnect'
  | 'lan_pending'
  | 'laptop_phone_slash'
  | 'laptop_phone'
  | 'laptop_slash'
  | 'laptop'
  | 'layer_group_slash'
  | 'layer_group'
  | 'layer_network'
  | 'letter_day'
  | 'letter_hour'
  | 'letter_minute'
  | 'letter_month'
  | 'letter_second'
  | 'letter_time'
  | 'letter_year'
  | 'library_plus'
  | 'lightbulb'
  | 'line_axis_arrow_down'
  | 'line_axis_x'
  | 'line_axis'
  | 'line_down'
  | 'line_height'
  | 'line_multiple_y_axis_x'
  | 'line_multiple_y_axis'
  | 'line_up'
  | 'line'
  | 'link_break'
  | 'link_minus'
  | 'link_plus'
  | 'link_simple_h'
  | 'link_simple'
  | 'list_square'
  | 'list_fill'
  | 'list_ol'
  | 'list_tree_archive'
  | 'list_tree'
  | 'list_ul'
  | 'list'
  | 'lng_storage'
  | 'loader'
  | 'location_arrow'
  | 'location_directly'
  | 'location_dot'
  | 'location_minus'
  | 'location_plus'
  | 'location_slash'
  | 'location_user'
  | 'lock'
  | 'logo_grey_z'
  | 'magic_wand'
  | 'magnifying_glass_exclamation'
  | 'magnifying_glass_minus'
  | 'magnifying_glass_ontology'
  | 'magnifying_glass_plus'
  | 'magnifying_glass_tags_words'
  | 'magnifying_glass_top_from_bracket'
  | 'magnifying_glass_triangle_down'
  | 'magnifying_glass_xmark'
  | 'magnifying_glass'
  | 'mail_open'
  | 'mail'
  | 'mailbox'
  | 'map_base'
  | 'map_marker_date_v_1'
  | 'map_marker_date_v_2'
  | 'map_pin'
  | 'map'
  | 'medical'
  | 'merge'
  | 'messaging_telegram_send'
  | 'messaging_telegram'
  | 'microphone_slash'
  | 'microphone'
  | 'minibus_side_view'
  | 'minus_circle_fill'
  | 'minus_circle'
  | 'minus'
  | 'module_fill'
  | 'monitor'
  | 'moon'
  | 'music_slash'
  | 'music'
  | 'network_external_link'
  | 'network_v_1'
  | 'network_v_2'
  | 'network_v_3'
  | 'network_wired'
  | 'ni_fi_logo'
  | 'normdocs_zql'
  | 'npm'
  | 'object_down_subtract'
  | 'object_exclude'
  | 'object_intersect'
  | 'object_selection'
  | 'object_union'
  | 'object_up_subtract'
  | 'object'
  | 'oil_barrel'
  | 'oil_canister'
  | 'oil_droplet_arrows_all'
  | 'oil_droplet_arrows_repeat_h'
  | 'oil_droplet_chek'
  | 'oil_droplet'
  | 'oil_field'
  | 'oil_tank'
  | 'ontology'
  | 'owl'
  | 'palette'
  | 'panel_down'
  | 'panel_left'
  | 'panel_right'
  | 'panel_top'
  | 'pantone'
  | 'paperclip_vertical'
  | 'paperclip'
  | 'pause'
  | 'paver_side_view'
  | 'pen_hammer'
  | 'pencil_arrow_right'
  | 'pencil_line_bottom'
  | 'pencil_triangle_down'
  | 'pencil_triangle_left'
  | 'pencil'
  | 'pentagon_fill'
  | 'pentagon'
  | 'percent'
  | 'phone_active_call'
  | 'phone_cancelled'
  | 'phone_minus'
  | 'phone_off'
  | 'phone_paused'
  | 'phone_plus'
  | 'phone'
  | 'pi'
  | 'pie_line_nested'
  | 'pie_line'
  | 'pie_pentagon'
  | 'pie_several_parts'
  | 'pie_simple'
  | 'pie'
  | 'pipe_node_side_view'
  | 'pipe_sensor'
  | 'pipe_slash'
  | 'pipe_valve'
  | 'pipeline_v_1'
  | 'pipeline_v_2'
  | 'pipette'
  | 'plane'
  | 'play_back'
  | 'play'
  | 'plus_column_right'
  | 'plus_column_top'
  | 'plus_triangle_down'
  | 'plus'
  | 'polyline'
  | 'portfel'
  | 'power'
  | 'premises_zql'
  | 'press'
  | 'printer'
  | 'process'
  | 'pulse'
  | 'pump_triangle_down'
  | 'pump'
  | 'push_button_cellphone'
  | 'qr'
  | 'question'
  | 'quilt_fill'
  | 'radiation'
  | 'railcar_hopper_side_view'
  | 'railcar_side_view'
  | 'range'
  | 'replay'
  | 'respirator_v_1'
  | 'respirator_v_2'
  | 'respirator_v_3'
  | 'respirator_v_4'
  | 'respirator_v_5'
  | 'respirator_v_6'
  | 'return_step'
  | 'return'
  | 'rhombus_fill'
  | 'rhombus'
  | 'ring_in_square'
  | 'ruler_index_zql'
  | 'ruler'
  | 'sample_logs_zql'
  | 'sample_templates_zql'
  | 'sandglass'
  | 'scatter_axis'
  | 'scatter_basic'
  | 'scatter'
  | 'scissors'
  | 'seedling_circle'
  | 'seedling_rectangle'
  | 'seedling'
  | 'selection_checked_empty'
  | 'send_backward'
  | 'send_forward'
  | 'separator'
  | 'sequential_fill'
  | 'server_network_close'
  | 'server_network_download'
  | 'server_network_minus'
  | 'server_network_plus'
  | 'server_network_security'
  | 'server_network_upload'
  | 'server_network'
  | 'server_shield'
  | 'server_slash_up_line'
  | 'server_slash'
  | 'server_up_line'
  | 'server'
  | 'shape_link_fill'
  | 'shape_link'
  | 'shape_plus'
  | 'share_left'
  | 'share_right'
  | 'shareing'
  | 'shield_exclamation'
  | 'shield_slash'
  | 'shield'
  | 'ship_front_view'
  | 'ship_side_view'
  | 'shopping_box'
  | 'shovel'
  | 'sigma'
  | 'signal_access_point'
  | 'signal_off'
  | 'signal_radio_tower'
  | 'signal'
  | 'sliders_h'
  | 'sliders_v'
  | 'snake_cup'
  | 'snowflake_up_to_bracket'
  | 'snowflake'
  | 'sort_filter_remove'
  | 'specification'
  | 'specs_zql'
  | 'speed_reduction_cooling'
  | 'square_arrows_curve_right_down'
  | 'square_arrows_curve_up_right'
  | 'square_bracket_curly_left'
  | 'square_bracket_curly_right'
  | 'square_bracket_left'
  | 'square_bracket_right'
  | 'square_circle_plus_triangle_fill'
  | 'square_circle_triangle_cross_fill'
  | 'square_circle_triangle_cross'
  | 'square_divide'
  | 'square_excel'
  | 'square_exclamation_empty'
  | 'square_exclamation_fill'
  | 'square_fill'
  | 'square_hexagon_circle_fill'
  | 'square_hexagon_circle'
  | 'square_in_square'
  | 'square_info_empty'
  | 'square_info_fill'
  | 'square_minus'
  | 'square_multiply'
  | 'square_music_double'
  | 'square_music'
  | 'square_percent'
  | 'square_plus'
  | 'square_powerpoint'
  | 'square_question_empty'
  | 'square_question_fill'
  | 'square_triangle_circle_triangle_fill'
  | 'square_triangle_circle_triangle'
  | 'square_word'
  | 'star_empty'
  | 'star_fill'
  | 'star_half_fill'
  | 'star_line'
  | 'steam_boiler'
  | 'steam_turbine'
  | 'steam'
  | 'stop'
  | 'stopwatch'
  | 'storage'
  | 'strikethrough'
  | 'subskrit_down'
  | 'subskrit_up'
  | 'sumbol_asterisk'
  | 'sun'
  | 'support_man'
  | 'table_down'
  | 'table_gear'
  | 'table_magnifying_glass'
  | 'table_right'
  | 'table_transpose_right'
  | 'table_transpose_top'
  | 'table_transpose'
  | 'table'
  | 'tablet_iqc_zql'
  | 'tablet'
  | 'tank'
  | 'tankcar_oil_side_view'
  | 'tankcar_side_view'
  | 'techs_zql'
  | 'temperature_minus'
  | 'temperature_plus'
  | 'temperature'
  | 'template'
  | 'text_color'
  | 'text'
  | 'thumb_down'
  | 'thumb_up'
  | 'thumbtack_directly'
  | 'thumbtack'
  | 'touchpad'
  | 'train_cargo'
  | 'train_passenger'
  | 'transmitter'
  | 'trash_empty'
  | 'trash'
  | 'triangle_circle_square_fill'
  | 'triangle_circle_square'
  | 'triangle_cross_empty'
  | 'triangle_down'
  | 'triangle_exclamation_empty'
  | 'triangle_exclamation_fill'
  | 'triangle_fill'
  | 'triangle_info_empty'
  | 'triangle_info_fill'
  | 'triangle_left'
  | 'triangle_plus_empty'
  | 'triangle_right'
  | 'triangle_up_down'
  | 'triangle_up'
  | 'triangle'
  | 'truck_dump_side_view'
  | 'truck_empty_side_view'
  | 'truck_garbage_side_view'
  | 'truck_gasoline_side_view'
  | 'truck_side_view'
  | 'tv'
  | 'umbrella'
  | 'underlined'
  | 'union'
  | 'unlock'
  | 'user_arrows_swap'
  | 'user_card'
  | 'user_check'
  | 'user_circle'
  | 'user_cross'
  | 'user_gear'
  | 'user_group'
  | 'user_location'
  | 'user_minus'
  | 'user_plus'
  | 'user_shield'
  | 'user_worker'
  | 'user'
  | 'users_arrow_right'
  | 'users_arrow_up_zql'
  | 'users_gear'
  | 'users_key'
  | 'users_location'
  | 'users_minus'
  | 'users_plus'
  | 'users'
  | 'vector_circle_one_point'
  | 'vector_circle_two_point'
  | 'vector_circle'
  | 'vector_line'
  | 'vector_point'
  | 'vector_polygon'
  | 'vector_rectangle'
  | 'vector_square'
  | 'vector_triangle'
  | 'vectors_radius'
  | 'vial_flask'
  | 'vial_plus'
  | 'vial_rotate_left'
  | 'vial_xmark'
  | 'vial'
  | 'video_cross'
  | 'video_slash'
  | 'video'
  | 'voicemail'
  | 'volume_cross'
  | 'volume_low'
  | 'volume_minus'
  | 'volume_off'
  | 'volume_plus'
  | 'volume_slash'
  | 'volume'
  | 'wallet'
  | 'watch'
  | 'water_heater'
  | 'water_pump'
  | 'webcam'
  | 'wifi_off'
  | 'wifi'
  | 'window'
  | 'wrench'
  | 'xmark_column_right'
  | 'xmark_column_top'
  | 'xmark';
export const PrizmIcons16Type = {
  agenda_fill: 'agenda_fill' as PrizmIcons16Type,
  airplane_side_view: 'airplane_side_view' as PrizmIcons16Type,
  airplane_top_view: 'airplane_top_view' as PrizmIcons16Type,
  alarm_clock: 'alarm_clock' as PrizmIcons16Type,
  alarm_plus: 'alarm_plus' as PrizmIcons16Type,
  align_bottom: 'align_bottom' as PrizmIcons16Type,
  align_center_h: 'align_center_h' as PrizmIcons16Type,
  align_center_v: 'align_center_v' as PrizmIcons16Type,
  align_center: 'align_center' as PrizmIcons16Type,
  align_justify: 'align_justify' as PrizmIcons16Type,
  align_left: 'align_left' as PrizmIcons16Type,
  align_right: 'align_right' as PrizmIcons16Type,
  align_top: 'align_top' as PrizmIcons16Type,
  ambulance_side_view: 'ambulance_side_view' as PrizmIcons16Type,
  android_pill: 'android_pill' as PrizmIcons16Type,
  android: 'android' as PrizmIcons16Type,
  angle_left_right_arrows_down: 'angle_left_right_arrows_down' as PrizmIcons16Type,
  angle_left_right: 'angle_left_right' as PrizmIcons16Type,
  arrange_send_to_back: 'arrange_send_to_back' as PrizmIcons16Type,
  array_fill: 'array_fill' as PrizmIcons16Type,
  arrow_bold_down: 'arrow_bold_down' as PrizmIcons16Type,
  arrow_bold_left: 'arrow_bold_left' as PrizmIcons16Type,
  arrow_bold_right: 'arrow_bold_right' as PrizmIcons16Type,
  arrow_bold_up: 'arrow_bold_up' as PrizmIcons16Type,
  arrow_daw: 'arrow_daw' as PrizmIcons16Type,
  arrow_down_between_lines: 'arrow_down_between_lines' as PrizmIcons16Type,
  arrow_down_from_double_line: 'arrow_down_from_double_line' as PrizmIcons16Type,
  arrow_down_from_line: 'arrow_down_from_line' as PrizmIcons16Type,
  arrow_down_in_circle_empty: 'arrow_down_in_circle_empty' as PrizmIcons16Type,
  arrow_down_to_bracket: 'arrow_down_to_bracket' as PrizmIcons16Type,
  arrow_down_to_double_line: 'arrow_down_to_double_line' as PrizmIcons16Type,
  arrow_down_to_line: 'arrow_down_to_line' as PrizmIcons16Type,
  arrow_down_wide_short: 'arrow_down_wide_short' as PrizmIcons16Type,
  arrow_down: 'arrow_down' as PrizmIcons16Type,
  arrow_left_between_lines: 'arrow_left_between_lines' as PrizmIcons16Type,
  arrow_left_down: 'arrow_left_down' as PrizmIcons16Type,
  arrow_left_from_bracket: 'arrow_left_from_bracket' as PrizmIcons16Type,
  arrow_left_in_circle_empty: 'arrow_left_in_circle_empty' as PrizmIcons16Type,
  arrow_left_up: 'arrow_left_up' as PrizmIcons16Type,
  arrow_left: 'arrow_left' as PrizmIcons16Type,
  arrow_right_between_lines: 'arrow_right_between_lines' as PrizmIcons16Type,
  arrow_right_down: 'arrow_right_down' as PrizmIcons16Type,
  arrow_right_from_bracket: 'arrow_right_from_bracket' as PrizmIcons16Type,
  arrow_right_in_circle_empty: 'arrow_right_in_circle_empty' as PrizmIcons16Type,
  arrow_right_up: 'arrow_right_up' as PrizmIcons16Type,
  arrow_right: 'arrow_right' as PrizmIcons16Type,
  arrow_rotate_left: 'arrow_rotate_left' as PrizmIcons16Type,
  arrow_rotate_right: 'arrow_rotate_right' as PrizmIcons16Type,
  arrow_turn_down_left: 'arrow_turn_down_left' as PrizmIcons16Type,
  arrow_turn_down_right: 'arrow_turn_down_right' as PrizmIcons16Type,
  arrow_turn_left_down: 'arrow_turn_left_down' as PrizmIcons16Type,
  arrow_turn_left_up: 'arrow_turn_left_up' as PrizmIcons16Type,
  arrow_turn_right_down: 'arrow_turn_right_down' as PrizmIcons16Type,
  arrow_turn_right_up: 'arrow_turn_right_up' as PrizmIcons16Type,
  arrow_turn_up_left: 'arrow_turn_up_left' as PrizmIcons16Type,
  arrow_turn_up_right: 'arrow_turn_up_right' as PrizmIcons16Type,
  arrow_up_arrow_down_h: 'arrow_up_arrow_down_h' as PrizmIcons16Type,
  arrow_up_arrow_down_v: 'arrow_up_arrow_down_v' as PrizmIcons16Type,
  arrow_up_between_lines: 'arrow_up_between_lines' as PrizmIcons16Type,
  arrow_up_from_bracket: 'arrow_up_from_bracket' as PrizmIcons16Type,
  arrow_up_from_double_line: 'arrow_up_from_double_line' as PrizmIcons16Type,
  arrow_up_from_line: 'arrow_up_from_line' as PrizmIcons16Type,
  arrow_up_in_circle_empty: 'arrow_up_in_circle_empty' as PrizmIcons16Type,
  arrow_up_to_dotted_line: 'arrow_up_to_dotted_line' as PrizmIcons16Type,
  arrow_up_to_double_line: 'arrow_up_to_double_line' as PrizmIcons16Type,
  arrow_up_to_line: 'arrow_up_to_line' as PrizmIcons16Type,
  arrow_up_wide_short: 'arrow_up_wide_short' as PrizmIcons16Type,
  arrow_up: 'arrow_up' as PrizmIcons16Type,
  arrows_all_directions: 'arrows_all_directions' as PrizmIcons16Type,
  arrows_compare: 'arrows_compare' as PrizmIcons16Type,
  arrows_cross: 'arrows_cross' as PrizmIcons16Type,
  arrows_direction_to_the_lines: 'arrows_direction_to_the_lines' as PrizmIcons16Type,
  arrows_inside: 'arrows_inside' as PrizmIcons16Type,
  arrows_left_right_brackets: 'arrows_left_right_brackets' as PrizmIcons16Type,
  arrows_left_right_to_lines: 'arrows_left_right_to_lines' as PrizmIcons16Type,
  arrows_maximize: 'arrows_maximize' as PrizmIcons16Type,
  arrows_minimize: 'arrows_minimize' as PrizmIcons16Type,
  arrows_out: 'arrows_out' as PrizmIcons16Type,
  arrows_repeat_h: 'arrows_repeat_h' as PrizmIcons16Type,
  arrows_repeat_v: 'arrows_repeat_v' as PrizmIcons16Type,
  arrows_rotate_h: 'arrows_rotate_h' as PrizmIcons16Type,
  arrows_rotate_v: 'arrows_rotate_v' as PrizmIcons16Type,
  arrows_shuffle: 'arrows_shuffle' as PrizmIcons16Type,
  arrows_swap_h: 'arrows_swap_h' as PrizmIcons16Type,
  arrows_swap_v: 'arrows_swap_v' as PrizmIcons16Type,
  arrows_up_down_to_lines: 'arrows_up_down_to_lines' as PrizmIcons16Type,
  at_sign: 'at_sign' as PrizmIcons16Type,
  audio_speakers: 'audio_speakers' as PrizmIcons16Type,
  award: 'award' as PrizmIcons16Type,
  bag: 'bag' as PrizmIcons16Type,
  balloon: 'balloon' as PrizmIcons16Type,
  ban: 'ban' as PrizmIcons16Type,
  bar_axis: 'bar_axis' as PrizmIcons16Type,
  bar_basic: 'bar_basic' as PrizmIcons16Type,
  bar_columns_axis_x: 'bar_columns_axis_x' as PrizmIcons16Type,
  bar_columns: 'bar_columns' as PrizmIcons16Type,
  bar_histogram: 'bar_histogram' as PrizmIcons16Type,
  bar_square: 'bar_square' as PrizmIcons16Type,
  bar_stacked_axis: 'bar_stacked_axis' as PrizmIcons16Type,
  bar_stacked: 'bar_stacked' as PrizmIcons16Type,
  barcode: 'barcode' as PrizmIcons16Type,
  bars_sort: 'bars_sort' as PrizmIcons16Type,
  bars: 'bars' as PrizmIcons16Type,
  battery_bolt: 'battery_bolt' as PrizmIcons16Type,
  battery_empty: 'battery_empty' as PrizmIcons16Type,
  battery_exclametion_mark: 'battery_exclametion_mark' as PrizmIcons16Type,
  battery_full: 'battery_full' as PrizmIcons16Type,
  battery_half: 'battery_half' as PrizmIcons16Type,
  battery_minus: 'battery_minus' as PrizmIcons16Type,
  battery_plus: 'battery_plus' as PrizmIcons16Type,
  battery_quarter: 'battery_quarter' as PrizmIcons16Type,
  battery_three_quarters: 'battery_three_quarters' as PrizmIcons16Type,
  bdrv_administration: 'bdrv_administration' as PrizmIcons16Type,
  bell_fill: 'bell_fill' as PrizmIcons16Type,
  bell_plus: 'bell_plus' as PrizmIcons16Type,
  bell_ring_fill: 'bell_ring_fill' as PrizmIcons16Type,
  bell_ring: 'bell_ring' as PrizmIcons16Type,
  bell_slash: 'bell_slash' as PrizmIcons16Type,
  bell: 'bell' as PrizmIcons16Type,
  bezier_curve: 'bezier_curve' as PrizmIcons16Type,
  bitcoin: 'bitcoin' as PrizmIcons16Type,
  block_lines: 'block_lines' as PrizmIcons16Type,
  bluetooth: 'bluetooth' as PrizmIcons16Type,
  boiler_hot_water_gas_and_oil: 'boiler_hot_water_gas_and_oil' as PrizmIcons16Type,
  boiler: 'boiler' as PrizmIcons16Type,
  bold: 'bold' as PrizmIcons16Type,
  book_stack: 'book_stack' as PrizmIcons16Type,
  book_check: 'book_check' as PrizmIcons16Type,
  book_closed: 'book_closed' as PrizmIcons16Type,
  book_open_plus: 'book_open_plus' as PrizmIcons16Type,
  book_open_re_arrow_left: 'book_open_re_arrow_left' as PrizmIcons16Type,
  book_open_re_arrow_right: 'book_open_re_arrow_right' as PrizmIcons16Type,
  book_open_text: 'book_open_text' as PrizmIcons16Type,
  book_open_with_page: 'book_open_with_page' as PrizmIcons16Type,
  book_open: 'book_open' as PrizmIcons16Type,
  bookmark_check_fill: 'bookmark_check_fill' as PrizmIcons16Type,
  bookmark_check: 'bookmark_check' as PrizmIcons16Type,
  bookmark_cross_fill: 'bookmark_cross_fill' as PrizmIcons16Type,
  bookmark_cross: 'bookmark_cross' as PrizmIcons16Type,
  bookmark_fill: 'bookmark_fill' as PrizmIcons16Type,
  bookmark_music_fill: 'bookmark_music_fill' as PrizmIcons16Type,
  bookmark_music: 'bookmark_music' as PrizmIcons16Type,
  bookmark_plus_fill: 'bookmark_plus_fill' as PrizmIcons16Type,
  bookmark_plus: 'bookmark_plus' as PrizmIcons16Type,
  bookmark: 'bookmark' as PrizmIcons16Type,
  border_all: 'border_all' as PrizmIcons16Type,
  border_bottom: 'border_bottom' as PrizmIcons16Type,
  border_center_h: 'border_center_h' as PrizmIcons16Type,
  border_center_v: 'border_center_v' as PrizmIcons16Type,
  border_inner: 'border_inner' as PrizmIcons16Type,
  border_left: 'border_left' as PrizmIcons16Type,
  border_none: 'border_none' as PrizmIcons16Type,
  border_outer: 'border_outer' as PrizmIcons16Type,
  border_right: 'border_right' as PrizmIcons16Type,
  border_top_left: 'border_top_left' as PrizmIcons16Type,
  border_top: 'border_top' as PrizmIcons16Type,
  box_open_arrow_down: 'box_open_arrow_down' as PrizmIcons16Type,
  box: 'box' as PrizmIcons16Type,
  brackets_curly: 'brackets_curly' as PrizmIcons16Type,
  brackets_square: 'brackets_square' as PrizmIcons16Type,
  broom: 'broom' as PrizmIcons16Type,
  browser: 'browser' as PrizmIcons16Type,
  brush: 'brush' as PrizmIcons16Type,
  bubble_message_add: 'bubble_message_add' as PrizmIcons16Type,
  bubble_message_attention: 'bubble_message_attention' as PrizmIcons16Type,
  bubble_message_circle: 'bubble_message_circle' as PrizmIcons16Type,
  bubble_message_empty: 'bubble_message_empty' as PrizmIcons16Type,
  bubble_message_off: 'bubble_message_off' as PrizmIcons16Type,
  bubble_message_question: 'bubble_message_question' as PrizmIcons16Type,
  bubble_message_text: 'bubble_message_text' as PrizmIcons16Type,
  bubble_message: 'bubble_message' as PrizmIcons16Type,
  burn: 'burn' as PrizmIcons16Type,
  calculator_arrow_rotate_left: 'calculator_arrow_rotate_left' as PrizmIcons16Type,
  calculator_function: 'calculator_function' as PrizmIcons16Type,
  calculator: 'calculator' as PrizmIcons16Type,
  calendar_blank: 'calendar_blank' as PrizmIcons16Type,
  calendar_check: 'calendar_check' as PrizmIcons16Type,
  calendar_clock: 'calendar_clock' as PrizmIcons16Type,
  calendar_deleted: 'calendar_deleted' as PrizmIcons16Type,
  calendar_event: 'calendar_event' as PrizmIcons16Type,
  calendar_plus: 'calendar_plus' as PrizmIcons16Type,
  calendar_question: 'calendar_question' as PrizmIcons16Type,
  calendar_range: 'calendar_range' as PrizmIcons16Type,
  calendar_today: 'calendar_today' as PrizmIcons16Type,
  calendar: 'calendar' as PrizmIcons16Type,
  calibration_characteristics_zql: 'calibration_characteristics_zql' as PrizmIcons16Type,
  camera_front: 'camera_front' as PrizmIcons16Type,
  camera_movie_cross: 'camera_movie_cross' as PrizmIcons16Type,
  camera_movie: 'camera_movie' as PrizmIcons16Type,
  camera: 'camera' as PrizmIcons16Type,
  car_jeep_side_view: 'car_jeep_side_view' as PrizmIcons16Type,
  car_light_side_view: 'car_light_side_view' as PrizmIcons16Type,
  carbon: 'carbon' as PrizmIcons16Type,
  carousel_fill: 'carousel_fill' as PrizmIcons16Type,
  cart_flatbed_container: 'cart_flatbed_container' as PrizmIcons16Type,
  cart_plus: 'cart_plus' as PrizmIcons16Type,
  cart: 'cart' as PrizmIcons16Type,
  cellphone_wireless: 'cellphone_wireless' as PrizmIcons16Type,
  cellphone: 'cellphone' as PrizmIcons16Type,
  charts_iqc_zql: 'charts_iqc_zql' as PrizmIcons16Type,
  check_double: 'check_double' as PrizmIcons16Type,
  checkerboard: 'checkerboard' as PrizmIcons16Type,
  chek: 'chek' as PrizmIcons16Type,
  chevron_down_to_double_line: 'chevron_down_to_double_line' as PrizmIcons16Type,
  chevron_down: 'chevron_down' as PrizmIcons16Type,
  chevron_left: 'chevron_left' as PrizmIcons16Type,
  chevron_mini_left: 'chevron_mini_left' as PrizmIcons16Type,
  chevron_mini_right: 'chevron_mini_right' as PrizmIcons16Type,
  chevron_right_above_double_line: 'chevron_right_above_double_line' as PrizmIcons16Type,
  chevron_right: 'chevron_right' as PrizmIcons16Type,
  chevron_up: 'chevron_up' as PrizmIcons16Type,
  chevrons_double_down: 'chevrons_double_down' as PrizmIcons16Type,
  chevrons_double_left: 'chevrons_double_left' as PrizmIcons16Type,
  chevrons_double_mini_left: 'chevrons_double_mini_left' as PrizmIcons16Type,
  chevrons_double_mini_right: 'chevrons_double_mini_right' as PrizmIcons16Type,
  chevrons_double_right: 'chevrons_double_right' as PrizmIcons16Type,
  chevrons_double_up: 'chevrons_double_up' as PrizmIcons16Type,
  chevrons_inside_horizontally: 'chevrons_inside_horizontally' as PrizmIcons16Type,
  chevrons_inside_vertically: 'chevrons_inside_vertically' as PrizmIcons16Type,
  chevrons_outside_horizontally: 'chevrons_outside_horizontally' as PrizmIcons16Type,
  chevrons_outside_vertically: 'chevrons_outside_vertically' as PrizmIcons16Type,
  circle_chek_empty: 'circle_chek_empty' as PrizmIcons16Type,
  circle_chek_fill: 'circle_chek_fill' as PrizmIcons16Type,
  circle_exclamation_empty: 'circle_exclamation_empty' as PrizmIcons16Type,
  circle_exclamation_fill: 'circle_exclamation_fill' as PrizmIcons16Type,
  circle_in_hexagon: 'circle_in_hexagon' as PrizmIcons16Type,
  circle_info_empty: 'circle_info_empty' as PrizmIcons16Type,
  circle_info_fill: 'circle_info_fill' as PrizmIcons16Type,
  circle_music: 'circle_music' as PrizmIcons16Type,
  circle_plus_fill: 'circle_plus_fill' as PrizmIcons16Type,
  circle_plus: 'circle_plus' as PrizmIcons16Type,
  circle_question_empty: 'circle_question_empty' as PrizmIcons16Type,
  circle_question_fill: 'circle_question_fill' as PrizmIcons16Type,
  circle_square_fill: 'circle_square_fill' as PrizmIcons16Type,
  circle_square_in_square: 'circle_square_in_square' as PrizmIcons16Type,
  circle_square: 'circle_square' as PrizmIcons16Type,
  circle_xmark_fill: 'circle_xmark_fill' as PrizmIcons16Type,
  circle_xmark: 'circle_xmark' as PrizmIcons16Type,
  circles_line_left_up_circle_right_down_fill: 'circles_line_left_up_circle_right_down_fill' as PrizmIcons16Type,
  circles_line_left_up_circle_right_down: 'circles_line_left_up_circle_right_down' as PrizmIcons16Type,
  clapperboard_cross: 'clapperboard_cross' as PrizmIcons16Type,
  clapperboard_open: 'clapperboard_open' as PrizmIcons16Type,
  clock_add: 'clock_add' as PrizmIcons16Type,
  clock_arrow_down: 'clock_arrow_down' as PrizmIcons16Type,
  clock_arrow_right: 'clock_arrow_right' as PrizmIcons16Type,
  clock_arrow_up: 'clock_arrow_up' as PrizmIcons16Type,
  clock_deleted: 'clock_deleted' as PrizmIcons16Type,
  clock_exclamation: 'clock_exclamation' as PrizmIcons16Type,
  clock_line_end: 'clock_line_end' as PrizmIcons16Type,
  clock_rotate_left: 'clock_rotate_left' as PrizmIcons16Type,
  clock_rotate_right: 'clock_rotate_right' as PrizmIcons16Type,
  clock: 'clock' as PrizmIcons16Type,
  cloud_arrow_down: 'cloud_arrow_down' as PrizmIcons16Type,
  cloud_arrow_up_inside: 'cloud_arrow_up_inside' as PrizmIcons16Type,
  cloud_arrow_up: 'cloud_arrow_up' as PrizmIcons16Type,
  cloud_check: 'cloud_check' as PrizmIcons16Type,
  cloud: 'cloud' as PrizmIcons16Type,
  code_download: 'code_download' as PrizmIcons16Type,
  code_simple: 'code_simple' as PrizmIcons16Type,
  code: 'code' as PrizmIcons16Type,
  collage_fill: 'collage_fill' as PrizmIcons16Type,
  collection: 'collection' as PrizmIcons16Type,
  collector: 'collector' as PrizmIcons16Type,
  column_fill: 'column_fill' as PrizmIcons16Type,
  column: 'column' as PrizmIcons16Type,
  compass: 'compass' as PrizmIcons16Type,
  component: 'component' as PrizmIcons16Type,
  concrete_mixer_side_view: 'concrete_mixer_side_view' as PrizmIcons16Type,
  container_v_1: 'container_v_1' as PrizmIcons16Type,
  container_v_2: 'container_v_2' as PrizmIcons16Type,
  containers: 'containers' as PrizmIcons16Type,
  control_charts_zql: 'control_charts_zql' as PrizmIcons16Type,
  copy_column: 'copy_column' as PrizmIcons16Type,
  copy_row: 'copy_row' as PrizmIcons16Type,
  copy: 'copy' as PrizmIcons16Type,
  crane: 'crane' as PrizmIcons16Type,
  credit_card_plus: 'credit_card_plus' as PrizmIcons16Type,
  credit_card_slash: 'credit_card_slash' as PrizmIcons16Type,
  credit_card: 'credit_card' as PrizmIcons16Type,
  crop: 'crop' as PrizmIcons16Type,
  crosshairs_dot: 'crosshairs_dot' as PrizmIcons16Type,
  crosshairs_simple: 'crosshairs_simple' as PrizmIcons16Type,
  cube_empty: 'cube_empty' as PrizmIcons16Type,
  cube_fill: 'cube_fill' as PrizmIcons16Type,
  cubes: 'cubes' as PrizmIcons16Type,
  dashboard_fill: 'dashboard_fill' as PrizmIcons16Type,
  dashboard_variant_fill: 'dashboard_variant_fill' as PrizmIcons16Type,
  database_chek: 'database_chek' as PrizmIcons16Type,
  database_json: 'database_json' as PrizmIcons16Type,
  database_magnifying_glass: 'database_magnifying_glass' as PrizmIcons16Type,
  database_minus: 'database_minus' as PrizmIcons16Type,
  database_plus: 'database_plus' as PrizmIcons16Type,
  database_sql: 'database_sql' as PrizmIcons16Type,
  database_xmark: 'database_xmark' as PrizmIcons16Type,
  database: 'database' as PrizmIcons16Type,
  day_fill: 'day_fill' as PrizmIcons16Type,
  decagram_chek_empty: 'decagram_chek_empty' as PrizmIcons16Type,
  decagram_chek_fill: 'decagram_chek_fill' as PrizmIcons16Type,
  decagram_exclamation_empty: 'decagram_exclamation_empty' as PrizmIcons16Type,
  decagram_exclamation_fill: 'decagram_exclamation_fill' as PrizmIcons16Type,
  default_ico: 'default_ico' as PrizmIcons16Type,
  delete_content: 'delete_content' as PrizmIcons16Type,
  desktop_tower: 'desktop_tower' as PrizmIcons16Type,
  discrete_set: 'discrete_set' as PrizmIcons16Type,
  dollar_slash: 'dollar_slash' as PrizmIcons16Type,
  dollar: 'dollar' as PrizmIcons16Type,
  doughnut: 'doughnut' as PrizmIcons16Type,
  droplet_slash: 'droplet_slash' as PrizmIcons16Type,
  droplet: 'droplet' as PrizmIcons16Type,
  early_version: 'early_version' as PrizmIcons16Type,
  earth: 'earth' as PrizmIcons16Type,
  editor_alfavit: 'editor_alfavit' as PrizmIcons16Type,
  editor_down: 'editor_down' as PrizmIcons16Type,
  editor_right: 'editor_right' as PrizmIcons16Type,
  electrics: 'electrics' as PrizmIcons16Type,
  ellipsis_grid: 'ellipsis_grid' as PrizmIcons16Type,
  ellipsis_h: 'ellipsis_h' as PrizmIcons16Type,
  ellipsis_v: 'ellipsis_v' as PrizmIcons16Type,
  energy_check: 'energy_check' as PrizmIcons16Type,
  energy_slash: 'energy_slash' as PrizmIcons16Type,
  energy: 'energy' as PrizmIcons16Type,
  equipment_zql: 'equipment_zql' as PrizmIcons16Type,
  eraser: 'eraser' as PrizmIcons16Type,
  ethernet: 'ethernet' as PrizmIcons16Type,
  exchanger: 'exchanger' as PrizmIcons16Type,
  exclamation: 'exclamation' as PrizmIcons16Type,
  eye_closed: 'eye_closed' as PrizmIcons16Type,
  eye_slash: 'eye_slash' as PrizmIcons16Type,
  eye: 'eye' as PrizmIcons16Type,
  face_frown: 'face_frown' as PrizmIcons16Type,
  face_smile: 'face_smile' as PrizmIcons16Type,
  factory_pipe: 'factory_pipe' as PrizmIcons16Type,
  factory_pipes: 'factory_pipes' as PrizmIcons16Type,
  factory: 'factory' as PrizmIcons16Type,
  fan: 'fan' as PrizmIcons16Type,
  file_arrow_down_left: 'file_arrow_down_left' as PrizmIcons16Type,
  file_arrow_down: 'file_arrow_down' as PrizmIcons16Type,
  file_arrow_up: 'file_arrow_up' as PrizmIcons16Type,
  file_arrow: 'file_arrow' as PrizmIcons16Type,
  file_arrows_up_right: 'file_arrows_up_right' as PrizmIcons16Type,
  file_camera: 'file_camera' as PrizmIcons16Type,
  file_cross_out: 'file_cross_out' as PrizmIcons16Type,
  file_cross: 'file_cross' as PrizmIcons16Type,
  file_doc: 'file_doc' as PrizmIcons16Type,
  file_docx: 'file_docx' as PrizmIcons16Type,
  file_dot: 'file_dot' as PrizmIcons16Type,
  file_empty: 'file_empty' as PrizmIcons16Type,
  file_exclamation: 'file_exclamation' as PrizmIcons16Type,
  file_eye: 'file_eye' as PrizmIcons16Type,
  file_filled: 'file_filled' as PrizmIcons16Type,
  file_image: 'file_image' as PrizmIcons16Type,
  file_magnifying_glass: 'file_magnifying_glass' as PrizmIcons16Type,
  file_minus: 'file_minus' as PrizmIcons16Type,
  file_music: 'file_music' as PrizmIcons16Type,
  file_pdf: 'file_pdf' as PrizmIcons16Type,
  file_pen: 'file_pen' as PrizmIcons16Type,
  file_play: 'file_play' as PrizmIcons16Type,
  file_plus: 'file_plus' as PrizmIcons16Type,
  file_ppt: 'file_ppt' as PrizmIcons16Type,
  file_pptx: 'file_pptx' as PrizmIcons16Type,
  file_txt: 'file_txt' as PrizmIcons16Type,
  file_up_right: 'file_up_right' as PrizmIcons16Type,
  file_xls: 'file_xls' as PrizmIcons16Type,
  file_xlsx: 'file_xlsx' as PrizmIcons16Type,
  files_mode: 'files_mode' as PrizmIcons16Type,
  fill: 'fill' as PrizmIcons16Type,
  film_cross: 'film_cross' as PrizmIcons16Type,
  film: 'film' as PrizmIcons16Type,
  filter_gear: 'filter_gear' as PrizmIcons16Type,
  filter_ontology: 'filter_ontology' as PrizmIcons16Type,
  filter: 'filter' as PrizmIcons16Type,
  finance_scanner: 'finance_scanner' as PrizmIcons16Type,
  fire: 'fire' as PrizmIcons16Type,
  flag_fill_red: 'flag_fill_red' as PrizmIcons16Type,
  flag_fill: 'flag_fill' as PrizmIcons16Type,
  flag: 'flag' as PrizmIcons16Type,
  flask_round_potion: 'flask_round_potion' as PrizmIcons16Type,
  flask: 'flask' as PrizmIcons16Type,
  floppy_cross_out: 'floppy_cross_out' as PrizmIcons16Type,
  floppy_cross: 'floppy_cross' as PrizmIcons16Type,
  floppy_pen: 'floppy_pen' as PrizmIcons16Type,
  floppy_star: 'floppy_star' as PrizmIcons16Type,
  floppy: 'floppy' as PrizmIcons16Type,
  folder_open: 'folder_open' as PrizmIcons16Type,
  folder_underline_minus: 'folder_underline_minus' as PrizmIcons16Type,
  folder_underline_plus: 'folder_underline_plus' as PrizmIcons16Type,
  folder_underline: 'folder_underline' as PrizmIcons16Type,
  folder_arrow_down_left: 'folder_arrow_down_left' as PrizmIcons16Type,
  folder_arrow_down: 'folder_arrow_down' as PrizmIcons16Type,
  folder_arrow_up_right: 'folder_arrow_up_right' as PrizmIcons16Type,
  folder_cross: 'folder_cross' as PrizmIcons16Type,
  folder_dot: 'folder_dot' as PrizmIcons16Type,
  folder_minus: 'folder_minus' as PrizmIcons16Type,
  folder_plus: 'folder_plus' as PrizmIcons16Type,
  folder: 'folder' as PrizmIcons16Type,
  forvard_step: 'forvard_step' as PrizmIcons16Type,
  forward: 'forward' as PrizmIcons16Type,
  fuel_oil_tank: 'fuel_oil_tank' as PrizmIcons16Type,
  function: 'function' as PrizmIcons16Type,
  gantt: 'gantt' as PrizmIcons16Type,
  gas_monitoring: 'gas_monitoring' as PrizmIcons16Type,
  gas_pump: 'gas_pump' as PrizmIcons16Type,
  gas: 'gas' as PrizmIcons16Type,
  gauge: 'gauge' as PrizmIcons16Type,
  gear_5_edge: 'gear_5_edge' as PrizmIcons16Type,
  gear_8_edge: 'gear_8_edge' as PrizmIcons16Type,
  gear_cooling: 'gear_cooling' as PrizmIcons16Type,
  generator: 'generator' as PrizmIcons16Type,
  gift: 'gift' as PrizmIcons16Type,
  git_lab: 'git_lab' as PrizmIcons16Type,
  globe: 'globe' as PrizmIcons16Type,
  grid_fill: 'grid_fill' as PrizmIcons16Type,
  grid: 'grid' as PrizmIcons16Type,
  grip_dots_vertical: 'grip_dots_vertical' as PrizmIcons16Type,
  hard_drive_outline: 'hard_drive_outline' as PrizmIcons16Type,
  hash_dash: 'hash_dash' as PrizmIcons16Type,
  hash: 'hash' as PrizmIcons16Type,
  hashtag: 'hashtag' as PrizmIcons16Type,
  headline_fill: 'headline_fill' as PrizmIcons16Type,
  headphones: 'headphones' as PrizmIcons16Type,
  heart_empty: 'heart_empty' as PrizmIcons16Type,
  heart_fill: 'heart_fill' as PrizmIcons16Type,
  helicopter_side_view: 'helicopter_side_view' as PrizmIcons16Type,
  hexagon_exclamation_empty: 'hexagon_exclamation_empty' as PrizmIcons16Type,
  hexagon_exclamation_fill: 'hexagon_exclamation_fill' as PrizmIcons16Type,
  hexagon_fill: 'hexagon_fill' as PrizmIcons16Type,
  hexagon: 'hexagon' as PrizmIcons16Type,
  hexagons_axis: 'hexagons_axis' as PrizmIcons16Type,
  hexagons: 'hexagons' as PrizmIcons16Type,
  histogram_axis: 'histogram_axis' as PrizmIcons16Type,
  house_mini: 'house_mini' as PrizmIcons16Type,
  house: 'house' as PrizmIcons16Type,
  image: 'image' as PrizmIcons16Type,
  indent_arrow_left: 'indent_arrow_left' as PrizmIcons16Type,
  indent_arrow_right: 'indent_arrow_right' as PrizmIcons16Type,
  infinity: 'infinity' as PrizmIcons16Type,
  info: 'info' as PrizmIcons16Type,
  input_device: 'input_device' as PrizmIcons16Type,
  instagram: 'instagram' as PrizmIcons16Type,
  italic: 'italic' as PrizmIcons16Type,
  key: 'key' as PrizmIcons16Type,
  keyboard_close: 'keyboard_close' as PrizmIcons16Type,
  keyboard: 'keyboard' as PrizmIcons16Type,
  label_cross: 'label_cross' as PrizmIcons16Type,
  label_exclamation_mark: 'label_exclamation_mark' as PrizmIcons16Type,
  label_fill: 'label_fill' as PrizmIcons16Type,
  label_magnifying_glass: 'label_magnifying_glass' as PrizmIcons16Type,
  label_plus: 'label_plus' as PrizmIcons16Type,
  label_question: 'label_question' as PrizmIcons16Type,
  label_text: 'label_text' as PrizmIcons16Type,
  label: 'label' as PrizmIcons16Type,
  lan_connect: 'lan_connect' as PrizmIcons16Type,
  lan_disconnect: 'lan_disconnect' as PrizmIcons16Type,
  lan_pending: 'lan_pending' as PrizmIcons16Type,
  laptop_phone_slash: 'laptop_phone_slash' as PrizmIcons16Type,
  laptop_phone: 'laptop_phone' as PrizmIcons16Type,
  laptop_slash: 'laptop_slash' as PrizmIcons16Type,
  laptop: 'laptop' as PrizmIcons16Type,
  layer_group_slash: 'layer_group_slash' as PrizmIcons16Type,
  layer_group: 'layer_group' as PrizmIcons16Type,
  layer_network: 'layer_network' as PrizmIcons16Type,
  letter_day: 'letter_day' as PrizmIcons16Type,
  letter_hour: 'letter_hour' as PrizmIcons16Type,
  letter_minute: 'letter_minute' as PrizmIcons16Type,
  letter_month: 'letter_month' as PrizmIcons16Type,
  letter_second: 'letter_second' as PrizmIcons16Type,
  letter_time: 'letter_time' as PrizmIcons16Type,
  letter_year: 'letter_year' as PrizmIcons16Type,
  library_plus: 'library_plus' as PrizmIcons16Type,
  lightbulb: 'lightbulb' as PrizmIcons16Type,
  line_axis_arrow_down: 'line_axis_arrow_down' as PrizmIcons16Type,
  line_axis_x: 'line_axis_x' as PrizmIcons16Type,
  line_axis: 'line_axis' as PrizmIcons16Type,
  line_down: 'line_down' as PrizmIcons16Type,
  line_height: 'line_height' as PrizmIcons16Type,
  line_multiple_y_axis_x: 'line_multiple_y_axis_x' as PrizmIcons16Type,
  line_multiple_y_axis: 'line_multiple_y_axis' as PrizmIcons16Type,
  line_up: 'line_up' as PrizmIcons16Type,
  line: 'line' as PrizmIcons16Type,
  link_break: 'link_break' as PrizmIcons16Type,
  link_minus: 'link_minus' as PrizmIcons16Type,
  link_plus: 'link_plus' as PrizmIcons16Type,
  link_simple_h: 'link_simple_h' as PrizmIcons16Type,
  link_simple: 'link_simple' as PrizmIcons16Type,
  list_square: 'list_square' as PrizmIcons16Type,
  list_fill: 'list_fill' as PrizmIcons16Type,
  list_ol: 'list_ol' as PrizmIcons16Type,
  list_tree_archive: 'list_tree_archive' as PrizmIcons16Type,
  list_tree: 'list_tree' as PrizmIcons16Type,
  list_ul: 'list_ul' as PrizmIcons16Type,
  list: 'list' as PrizmIcons16Type,
  lng_storage: 'lng_storage' as PrizmIcons16Type,
  loader: 'loader' as PrizmIcons16Type,
  location_arrow: 'location_arrow' as PrizmIcons16Type,
  location_directly: 'location_directly' as PrizmIcons16Type,
  location_dot: 'location_dot' as PrizmIcons16Type,
  location_minus: 'location_minus' as PrizmIcons16Type,
  location_plus: 'location_plus' as PrizmIcons16Type,
  location_slash: 'location_slash' as PrizmIcons16Type,
  location_user: 'location_user' as PrizmIcons16Type,
  lock: 'lock' as PrizmIcons16Type,
  logo_grey_z: 'logo_grey_z' as PrizmIcons16Type,
  magic_wand: 'magic_wand' as PrizmIcons16Type,
  magnifying_glass_exclamation: 'magnifying_glass_exclamation' as PrizmIcons16Type,
  magnifying_glass_minus: 'magnifying_glass_minus' as PrizmIcons16Type,
  magnifying_glass_ontology: 'magnifying_glass_ontology' as PrizmIcons16Type,
  magnifying_glass_plus: 'magnifying_glass_plus' as PrizmIcons16Type,
  magnifying_glass_tags_words: 'magnifying_glass_tags_words' as PrizmIcons16Type,
  magnifying_glass_top_from_bracket: 'magnifying_glass_top_from_bracket' as PrizmIcons16Type,
  magnifying_glass_triangle_down: 'magnifying_glass_triangle_down' as PrizmIcons16Type,
  magnifying_glass_xmark: 'magnifying_glass_xmark' as PrizmIcons16Type,
  magnifying_glass: 'magnifying_glass' as PrizmIcons16Type,
  mail_open: 'mail_open' as PrizmIcons16Type,
  mail: 'mail' as PrizmIcons16Type,
  mailbox: 'mailbox' as PrizmIcons16Type,
  map_base: 'map_base' as PrizmIcons16Type,
  map_marker_date_v_1: 'map_marker_date_v_1' as PrizmIcons16Type,
  map_marker_date_v_2: 'map_marker_date_v_2' as PrizmIcons16Type,
  map_pin: 'map_pin' as PrizmIcons16Type,
  map: 'map' as PrizmIcons16Type,
  medical: 'medical' as PrizmIcons16Type,
  merge: 'merge' as PrizmIcons16Type,
  messaging_telegram_send: 'messaging_telegram_send' as PrizmIcons16Type,
  messaging_telegram: 'messaging_telegram' as PrizmIcons16Type,
  microphone_slash: 'microphone_slash' as PrizmIcons16Type,
  microphone: 'microphone' as PrizmIcons16Type,
  minibus_side_view: 'minibus_side_view' as PrizmIcons16Type,
  minus_circle_fill: 'minus_circle_fill' as PrizmIcons16Type,
  minus_circle: 'minus_circle' as PrizmIcons16Type,
  minus: 'minus' as PrizmIcons16Type,
  module_fill: 'module_fill' as PrizmIcons16Type,
  monitor: 'monitor' as PrizmIcons16Type,
  moon: 'moon' as PrizmIcons16Type,
  music_slash: 'music_slash' as PrizmIcons16Type,
  music: 'music' as PrizmIcons16Type,
  network_external_link: 'network_external_link' as PrizmIcons16Type,
  network_v_1: 'network_v_1' as PrizmIcons16Type,
  network_v_2: 'network_v_2' as PrizmIcons16Type,
  network_v_3: 'network_v_3' as PrizmIcons16Type,
  network_wired: 'network_wired' as PrizmIcons16Type,
  ni_fi_logo: 'ni_fi_logo' as PrizmIcons16Type,
  normdocs_zql: 'normdocs_zql' as PrizmIcons16Type,
  npm: 'npm' as PrizmIcons16Type,
  object_down_subtract: 'object_down_subtract' as PrizmIcons16Type,
  object_exclude: 'object_exclude' as PrizmIcons16Type,
  object_intersect: 'object_intersect' as PrizmIcons16Type,
  object_selection: 'object_selection' as PrizmIcons16Type,
  object_union: 'object_union' as PrizmIcons16Type,
  object_up_subtract: 'object_up_subtract' as PrizmIcons16Type,
  object: 'object' as PrizmIcons16Type,
  oil_barrel: 'oil_barrel' as PrizmIcons16Type,
  oil_canister: 'oil_canister' as PrizmIcons16Type,
  oil_droplet_arrows_all: 'oil_droplet_arrows_all' as PrizmIcons16Type,
  oil_droplet_arrows_repeat_h: 'oil_droplet_arrows_repeat_h' as PrizmIcons16Type,
  oil_droplet_chek: 'oil_droplet_chek' as PrizmIcons16Type,
  oil_droplet: 'oil_droplet' as PrizmIcons16Type,
  oil_field: 'oil_field' as PrizmIcons16Type,
  oil_tank: 'oil_tank' as PrizmIcons16Type,
  ontology: 'ontology' as PrizmIcons16Type,
  owl: 'owl' as PrizmIcons16Type,
  palette: 'palette' as PrizmIcons16Type,
  panel_down: 'panel_down' as PrizmIcons16Type,
  panel_left: 'panel_left' as PrizmIcons16Type,
  panel_right: 'panel_right' as PrizmIcons16Type,
  panel_top: 'panel_top' as PrizmIcons16Type,
  pantone: 'pantone' as PrizmIcons16Type,
  paperclip_vertical: 'paperclip_vertical' as PrizmIcons16Type,
  paperclip: 'paperclip' as PrizmIcons16Type,
  pause: 'pause' as PrizmIcons16Type,
  paver_side_view: 'paver_side_view' as PrizmIcons16Type,
  pen_hammer: 'pen_hammer' as PrizmIcons16Type,
  pencil_arrow_right: 'pencil_arrow_right' as PrizmIcons16Type,
  pencil_line_bottom: 'pencil_line_bottom' as PrizmIcons16Type,
  pencil_triangle_down: 'pencil_triangle_down' as PrizmIcons16Type,
  pencil_triangle_left: 'pencil_triangle_left' as PrizmIcons16Type,
  pencil: 'pencil' as PrizmIcons16Type,
  pentagon_fill: 'pentagon_fill' as PrizmIcons16Type,
  pentagon: 'pentagon' as PrizmIcons16Type,
  percent: 'percent' as PrizmIcons16Type,
  phone_active_call: 'phone_active_call' as PrizmIcons16Type,
  phone_cancelled: 'phone_cancelled' as PrizmIcons16Type,
  phone_minus: 'phone_minus' as PrizmIcons16Type,
  phone_off: 'phone_off' as PrizmIcons16Type,
  phone_paused: 'phone_paused' as PrizmIcons16Type,
  phone_plus: 'phone_plus' as PrizmIcons16Type,
  phone: 'phone' as PrizmIcons16Type,
  pi: 'pi' as PrizmIcons16Type,
  pie_line_nested: 'pie_line_nested' as PrizmIcons16Type,
  pie_line: 'pie_line' as PrizmIcons16Type,
  pie_pentagon: 'pie_pentagon' as PrizmIcons16Type,
  pie_several_parts: 'pie_several_parts' as PrizmIcons16Type,
  pie_simple: 'pie_simple' as PrizmIcons16Type,
  pie: 'pie' as PrizmIcons16Type,
  pipe_node_side_view: 'pipe_node_side_view' as PrizmIcons16Type,
  pipe_sensor: 'pipe_sensor' as PrizmIcons16Type,
  pipe_slash: 'pipe_slash' as PrizmIcons16Type,
  pipe_valve: 'pipe_valve' as PrizmIcons16Type,
  pipeline_v_1: 'pipeline_v_1' as PrizmIcons16Type,
  pipeline_v_2: 'pipeline_v_2' as PrizmIcons16Type,
  pipette: 'pipette' as PrizmIcons16Type,
  plane: 'plane' as PrizmIcons16Type,
  play_back: 'play_back' as PrizmIcons16Type,
  play: 'play' as PrizmIcons16Type,
  plus_column_right: 'plus_column_right' as PrizmIcons16Type,
  plus_column_top: 'plus_column_top' as PrizmIcons16Type,
  plus_triangle_down: 'plus_triangle_down' as PrizmIcons16Type,
  plus: 'plus' as PrizmIcons16Type,
  polyline: 'polyline' as PrizmIcons16Type,
  portfel: 'portfel' as PrizmIcons16Type,
  power: 'power' as PrizmIcons16Type,
  premises_zql: 'premises_zql' as PrizmIcons16Type,
  press: 'press' as PrizmIcons16Type,
  printer: 'printer' as PrizmIcons16Type,
  process: 'process' as PrizmIcons16Type,
  pulse: 'pulse' as PrizmIcons16Type,
  pump_triangle_down: 'pump_triangle_down' as PrizmIcons16Type,
  pump: 'pump' as PrizmIcons16Type,
  push_button_cellphone: 'push_button_cellphone' as PrizmIcons16Type,
  qr: 'qr' as PrizmIcons16Type,
  question: 'question' as PrizmIcons16Type,
  quilt_fill: 'quilt_fill' as PrizmIcons16Type,
  radiation: 'radiation' as PrizmIcons16Type,
  railcar_hopper_side_view: 'railcar_hopper_side_view' as PrizmIcons16Type,
  railcar_side_view: 'railcar_side_view' as PrizmIcons16Type,
  range: 'range' as PrizmIcons16Type,
  replay: 'replay' as PrizmIcons16Type,
  respirator_v_1: 'respirator_v_1' as PrizmIcons16Type,
  respirator_v_2: 'respirator_v_2' as PrizmIcons16Type,
  respirator_v_3: 'respirator_v_3' as PrizmIcons16Type,
  respirator_v_4: 'respirator_v_4' as PrizmIcons16Type,
  respirator_v_5: 'respirator_v_5' as PrizmIcons16Type,
  respirator_v_6: 'respirator_v_6' as PrizmIcons16Type,
  return_step: 'return_step' as PrizmIcons16Type,
  return: 'return' as PrizmIcons16Type,
  rhombus_fill: 'rhombus_fill' as PrizmIcons16Type,
  rhombus: 'rhombus' as PrizmIcons16Type,
  ring_in_square: 'ring_in_square' as PrizmIcons16Type,
  ruler_index_zql: 'ruler_index_zql' as PrizmIcons16Type,
  ruler: 'ruler' as PrizmIcons16Type,
  sample_logs_zql: 'sample_logs_zql' as PrizmIcons16Type,
  sample_templates_zql: 'sample_templates_zql' as PrizmIcons16Type,
  sandglass: 'sandglass' as PrizmIcons16Type,
  scatter_axis: 'scatter_axis' as PrizmIcons16Type,
  scatter_basic: 'scatter_basic' as PrizmIcons16Type,
  scatter: 'scatter' as PrizmIcons16Type,
  scissors: 'scissors' as PrizmIcons16Type,
  seedling_circle: 'seedling_circle' as PrizmIcons16Type,
  seedling_rectangle: 'seedling_rectangle' as PrizmIcons16Type,
  seedling: 'seedling' as PrizmIcons16Type,
  selection_checked_empty: 'selection_checked_empty' as PrizmIcons16Type,
  send_backward: 'send_backward' as PrizmIcons16Type,
  send_forward: 'send_forward' as PrizmIcons16Type,
  separator: 'separator' as PrizmIcons16Type,
  sequential_fill: 'sequential_fill' as PrizmIcons16Type,
  server_network_close: 'server_network_close' as PrizmIcons16Type,
  server_network_download: 'server_network_download' as PrizmIcons16Type,
  server_network_minus: 'server_network_minus' as PrizmIcons16Type,
  server_network_plus: 'server_network_plus' as PrizmIcons16Type,
  server_network_security: 'server_network_security' as PrizmIcons16Type,
  server_network_upload: 'server_network_upload' as PrizmIcons16Type,
  server_network: 'server_network' as PrizmIcons16Type,
  server_shield: 'server_shield' as PrizmIcons16Type,
  server_slash_up_line: 'server_slash_up_line' as PrizmIcons16Type,
  server_slash: 'server_slash' as PrizmIcons16Type,
  server_up_line: 'server_up_line' as PrizmIcons16Type,
  server: 'server' as PrizmIcons16Type,
  shape_link_fill: 'shape_link_fill' as PrizmIcons16Type,
  shape_link: 'shape_link' as PrizmIcons16Type,
  shape_plus: 'shape_plus' as PrizmIcons16Type,
  share_left: 'share_left' as PrizmIcons16Type,
  share_right: 'share_right' as PrizmIcons16Type,
  shareing: 'shareing' as PrizmIcons16Type,
  shield_exclamation: 'shield_exclamation' as PrizmIcons16Type,
  shield_slash: 'shield_slash' as PrizmIcons16Type,
  shield: 'shield' as PrizmIcons16Type,
  ship_front_view: 'ship_front_view' as PrizmIcons16Type,
  ship_side_view: 'ship_side_view' as PrizmIcons16Type,
  shopping_box: 'shopping_box' as PrizmIcons16Type,
  shovel: 'shovel' as PrizmIcons16Type,
  sigma: 'sigma' as PrizmIcons16Type,
  signal_access_point: 'signal_access_point' as PrizmIcons16Type,
  signal_off: 'signal_off' as PrizmIcons16Type,
  signal_radio_tower: 'signal_radio_tower' as PrizmIcons16Type,
  signal: 'signal' as PrizmIcons16Type,
  sliders_h: 'sliders_h' as PrizmIcons16Type,
  sliders_v: 'sliders_v' as PrizmIcons16Type,
  snake_cup: 'snake_cup' as PrizmIcons16Type,
  snowflake_up_to_bracket: 'snowflake_up_to_bracket' as PrizmIcons16Type,
  snowflake: 'snowflake' as PrizmIcons16Type,
  sort_filter_remove: 'sort_filter_remove' as PrizmIcons16Type,
  specification: 'specification' as PrizmIcons16Type,
  specs_zql: 'specs_zql' as PrizmIcons16Type,
  speed_reduction_cooling: 'speed_reduction_cooling' as PrizmIcons16Type,
  square_arrows_curve_right_down: 'square_arrows_curve_right_down' as PrizmIcons16Type,
  square_arrows_curve_up_right: 'square_arrows_curve_up_right' as PrizmIcons16Type,
  square_bracket_curly_left: 'square_bracket_curly_left' as PrizmIcons16Type,
  square_bracket_curly_right: 'square_bracket_curly_right' as PrizmIcons16Type,
  square_bracket_left: 'square_bracket_left' as PrizmIcons16Type,
  square_bracket_right: 'square_bracket_right' as PrizmIcons16Type,
  square_circle_plus_triangle_fill: 'square_circle_plus_triangle_fill' as PrizmIcons16Type,
  square_circle_triangle_cross_fill: 'square_circle_triangle_cross_fill' as PrizmIcons16Type,
  square_circle_triangle_cross: 'square_circle_triangle_cross' as PrizmIcons16Type,
  square_divide: 'square_divide' as PrizmIcons16Type,
  square_excel: 'square_excel' as PrizmIcons16Type,
  square_exclamation_empty: 'square_exclamation_empty' as PrizmIcons16Type,
  square_exclamation_fill: 'square_exclamation_fill' as PrizmIcons16Type,
  square_fill: 'square_fill' as PrizmIcons16Type,
  square_hexagon_circle_fill: 'square_hexagon_circle_fill' as PrizmIcons16Type,
  square_hexagon_circle: 'square_hexagon_circle' as PrizmIcons16Type,
  square_in_square: 'square_in_square' as PrizmIcons16Type,
  square_info_empty: 'square_info_empty' as PrizmIcons16Type,
  square_info_fill: 'square_info_fill' as PrizmIcons16Type,
  square_minus: 'square_minus' as PrizmIcons16Type,
  square_multiply: 'square_multiply' as PrizmIcons16Type,
  square_music_double: 'square_music_double' as PrizmIcons16Type,
  square_music: 'square_music' as PrizmIcons16Type,
  square_percent: 'square_percent' as PrizmIcons16Type,
  square_plus: 'square_plus' as PrizmIcons16Type,
  square_powerpoint: 'square_powerpoint' as PrizmIcons16Type,
  square_question_empty: 'square_question_empty' as PrizmIcons16Type,
  square_question_fill: 'square_question_fill' as PrizmIcons16Type,
  square_triangle_circle_triangle_fill: 'square_triangle_circle_triangle_fill' as PrizmIcons16Type,
  square_triangle_circle_triangle: 'square_triangle_circle_triangle' as PrizmIcons16Type,
  square_word: 'square_word' as PrizmIcons16Type,
  star_empty: 'star_empty' as PrizmIcons16Type,
  star_fill: 'star_fill' as PrizmIcons16Type,
  star_half_fill: 'star_half_fill' as PrizmIcons16Type,
  star_line: 'star_line' as PrizmIcons16Type,
  steam_boiler: 'steam_boiler' as PrizmIcons16Type,
  steam_turbine: 'steam_turbine' as PrizmIcons16Type,
  steam: 'steam' as PrizmIcons16Type,
  stop: 'stop' as PrizmIcons16Type,
  stopwatch: 'stopwatch' as PrizmIcons16Type,
  storage: 'storage' as PrizmIcons16Type,
  strikethrough: 'strikethrough' as PrizmIcons16Type,
  subskrit_down: 'subskrit_down' as PrizmIcons16Type,
  subskrit_up: 'subskrit_up' as PrizmIcons16Type,
  sumbol_asterisk: 'sumbol_asterisk' as PrizmIcons16Type,
  sun: 'sun' as PrizmIcons16Type,
  support_man: 'support_man' as PrizmIcons16Type,
  table_down: 'table_down' as PrizmIcons16Type,
  table_gear: 'table_gear' as PrizmIcons16Type,
  table_magnifying_glass: 'table_magnifying_glass' as PrizmIcons16Type,
  table_right: 'table_right' as PrizmIcons16Type,
  table_transpose_right: 'table_transpose_right' as PrizmIcons16Type,
  table_transpose_top: 'table_transpose_top' as PrizmIcons16Type,
  table_transpose: 'table_transpose' as PrizmIcons16Type,
  table: 'table' as PrizmIcons16Type,
  tablet_iqc_zql: 'tablet_iqc_zql' as PrizmIcons16Type,
  tablet: 'tablet' as PrizmIcons16Type,
  tank: 'tank' as PrizmIcons16Type,
  tankcar_oil_side_view: 'tankcar_oil_side_view' as PrizmIcons16Type,
  tankcar_side_view: 'tankcar_side_view' as PrizmIcons16Type,
  techs_zql: 'techs_zql' as PrizmIcons16Type,
  temperature_minus: 'temperature_minus' as PrizmIcons16Type,
  temperature_plus: 'temperature_plus' as PrizmIcons16Type,
  temperature: 'temperature' as PrizmIcons16Type,
  template: 'template' as PrizmIcons16Type,
  text_color: 'text_color' as PrizmIcons16Type,
  text: 'text' as PrizmIcons16Type,
  thumb_down: 'thumb_down' as PrizmIcons16Type,
  thumb_up: 'thumb_up' as PrizmIcons16Type,
  thumbtack_directly: 'thumbtack_directly' as PrizmIcons16Type,
  thumbtack: 'thumbtack' as PrizmIcons16Type,
  touchpad: 'touchpad' as PrizmIcons16Type,
  train_cargo: 'train_cargo' as PrizmIcons16Type,
  train_passenger: 'train_passenger' as PrizmIcons16Type,
  transmitter: 'transmitter' as PrizmIcons16Type,
  trash_empty: 'trash_empty' as PrizmIcons16Type,
  trash: 'trash' as PrizmIcons16Type,
  triangle_circle_square_fill: 'triangle_circle_square_fill' as PrizmIcons16Type,
  triangle_circle_square: 'triangle_circle_square' as PrizmIcons16Type,
  triangle_cross_empty: 'triangle_cross_empty' as PrizmIcons16Type,
  triangle_down: 'triangle_down' as PrizmIcons16Type,
  triangle_exclamation_empty: 'triangle_exclamation_empty' as PrizmIcons16Type,
  triangle_exclamation_fill: 'triangle_exclamation_fill' as PrizmIcons16Type,
  triangle_fill: 'triangle_fill' as PrizmIcons16Type,
  triangle_info_empty: 'triangle_info_empty' as PrizmIcons16Type,
  triangle_info_fill: 'triangle_info_fill' as PrizmIcons16Type,
  triangle_left: 'triangle_left' as PrizmIcons16Type,
  triangle_plus_empty: 'triangle_plus_empty' as PrizmIcons16Type,
  triangle_right: 'triangle_right' as PrizmIcons16Type,
  triangle_up_down: 'triangle_up_down' as PrizmIcons16Type,
  triangle_up: 'triangle_up' as PrizmIcons16Type,
  triangle: 'triangle' as PrizmIcons16Type,
  truck_dump_side_view: 'truck_dump_side_view' as PrizmIcons16Type,
  truck_empty_side_view: 'truck_empty_side_view' as PrizmIcons16Type,
  truck_garbage_side_view: 'truck_garbage_side_view' as PrizmIcons16Type,
  truck_gasoline_side_view: 'truck_gasoline_side_view' as PrizmIcons16Type,
  truck_side_view: 'truck_side_view' as PrizmIcons16Type,
  tv: 'tv' as PrizmIcons16Type,
  umbrella: 'umbrella' as PrizmIcons16Type,
  underlined: 'underlined' as PrizmIcons16Type,
  union: 'union' as PrizmIcons16Type,
  unlock: 'unlock' as PrizmIcons16Type,
  user_arrows_swap: 'user_arrows_swap' as PrizmIcons16Type,
  user_card: 'user_card' as PrizmIcons16Type,
  user_check: 'user_check' as PrizmIcons16Type,
  user_circle: 'user_circle' as PrizmIcons16Type,
  user_cross: 'user_cross' as PrizmIcons16Type,
  user_gear: 'user_gear' as PrizmIcons16Type,
  user_group: 'user_group' as PrizmIcons16Type,
  user_location: 'user_location' as PrizmIcons16Type,
  user_minus: 'user_minus' as PrizmIcons16Type,
  user_plus: 'user_plus' as PrizmIcons16Type,
  user_shield: 'user_shield' as PrizmIcons16Type,
  user_worker: 'user_worker' as PrizmIcons16Type,
  user: 'user' as PrizmIcons16Type,
  users_arrow_right: 'users_arrow_right' as PrizmIcons16Type,
  users_arrow_up_zql: 'users_arrow_up_zql' as PrizmIcons16Type,
  users_gear: 'users_gear' as PrizmIcons16Type,
  users_key: 'users_key' as PrizmIcons16Type,
  users_location: 'users_location' as PrizmIcons16Type,
  users_minus: 'users_minus' as PrizmIcons16Type,
  users_plus: 'users_plus' as PrizmIcons16Type,
  users: 'users' as PrizmIcons16Type,
  vector_circle_one_point: 'vector_circle_one_point' as PrizmIcons16Type,
  vector_circle_two_point: 'vector_circle_two_point' as PrizmIcons16Type,
  vector_circle: 'vector_circle' as PrizmIcons16Type,
  vector_line: 'vector_line' as PrizmIcons16Type,
  vector_point: 'vector_point' as PrizmIcons16Type,
  vector_polygon: 'vector_polygon' as PrizmIcons16Type,
  vector_rectangle: 'vector_rectangle' as PrizmIcons16Type,
  vector_square: 'vector_square' as PrizmIcons16Type,
  vector_triangle: 'vector_triangle' as PrizmIcons16Type,
  vectors_radius: 'vectors_radius' as PrizmIcons16Type,
  vial_flask: 'vial_flask' as PrizmIcons16Type,
  vial_plus: 'vial_plus' as PrizmIcons16Type,
  vial_rotate_left: 'vial_rotate_left' as PrizmIcons16Type,
  vial_xmark: 'vial_xmark' as PrizmIcons16Type,
  vial: 'vial' as PrizmIcons16Type,
  video_cross: 'video_cross' as PrizmIcons16Type,
  video_slash: 'video_slash' as PrizmIcons16Type,
  video: 'video' as PrizmIcons16Type,
  voicemail: 'voicemail' as PrizmIcons16Type,
  volume_cross: 'volume_cross' as PrizmIcons16Type,
  volume_low: 'volume_low' as PrizmIcons16Type,
  volume_minus: 'volume_minus' as PrizmIcons16Type,
  volume_off: 'volume_off' as PrizmIcons16Type,
  volume_plus: 'volume_plus' as PrizmIcons16Type,
  volume_slash: 'volume_slash' as PrizmIcons16Type,
  volume: 'volume' as PrizmIcons16Type,
  wallet: 'wallet' as PrizmIcons16Type,
  watch: 'watch' as PrizmIcons16Type,
  water_heater: 'water_heater' as PrizmIcons16Type,
  water_pump: 'water_pump' as PrizmIcons16Type,
  webcam: 'webcam' as PrizmIcons16Type,
  wifi_off: 'wifi_off' as PrizmIcons16Type,
  wifi: 'wifi' as PrizmIcons16Type,
  window: 'window' as PrizmIcons16Type,
  wrench: 'wrench' as PrizmIcons16Type,
  xmark_column_right: 'xmark_column_right' as PrizmIcons16Type,
  xmark_column_top: 'xmark_column_top' as PrizmIcons16Type,
  xmark: 'xmark' as PrizmIcons16Type
};
export interface PrizmIcons {
  name: PrizmIcons16Enum;
  data: string;
}
export enum PrizmIcons16Enum {
  AGENDA_FILL = 'agenda_fill',
  AIRPLANE_SIDE_VIEW = 'airplane_side_view',
  AIRPLANE_TOP_VIEW = 'airplane_top_view',
  ALARM_CLOCK = 'alarm_clock',
  ALARM_PLUS = 'alarm_plus',
  ALIGN_BOTTOM = 'align_bottom',
  ALIGN_CENTER_H = 'align_center_h',
  ALIGN_CENTER_V = 'align_center_v',
  ALIGN_CENTER = 'align_center',
  ALIGN_JUSTIFY = 'align_justify',
  ALIGN_LEFT = 'align_left',
  ALIGN_RIGHT = 'align_right',
  ALIGN_TOP = 'align_top',
  AMBULANCE_SIDE_VIEW = 'ambulance_side_view',
  ANDROID_PILL = 'android_pill',
  ANDROID = 'android',
  ANGLE_LEFT_RIGHT_ARROWS_DOWN = 'angle_left_right_arrows_down',
  ANGLE_LEFT_RIGHT = 'angle_left_right',
  ARRANGE_SEND_TO_BACK = 'arrange_send_to_back',
  ARRAY_FILL = 'array_fill',
  ARROW_BOLD_DOWN = 'arrow_bold_down',
  ARROW_BOLD_LEFT = 'arrow_bold_left',
  ARROW_BOLD_RIGHT = 'arrow_bold_right',
  ARROW_BOLD_UP = 'arrow_bold_up',
  ARROW_DAW = 'arrow_daw',
  ARROW_DOWN_BETWEEN_LINES = 'arrow_down_between_lines',
  ARROW_DOWN_FROM_DOUBLE_LINE = 'arrow_down_from_double_line',
  ARROW_DOWN_FROM_LINE = 'arrow_down_from_line',
  ARROW_DOWN_IN_CIRCLE_EMPTY = 'arrow_down_in_circle_empty',
  ARROW_DOWN_TO_BRACKET = 'arrow_down_to_bracket',
  ARROW_DOWN_TO_DOUBLE_LINE = 'arrow_down_to_double_line',
  ARROW_DOWN_TO_LINE = 'arrow_down_to_line',
  ARROW_DOWN_WIDE_SHORT = 'arrow_down_wide_short',
  ARROW_DOWN = 'arrow_down',
  ARROW_LEFT_BETWEEN_LINES = 'arrow_left_between_lines',
  ARROW_LEFT_DOWN = 'arrow_left_down',
  ARROW_LEFT_FROM_BRACKET = 'arrow_left_from_bracket',
  ARROW_LEFT_IN_CIRCLE_EMPTY = 'arrow_left_in_circle_empty',
  ARROW_LEFT_UP = 'arrow_left_up',
  ARROW_LEFT = 'arrow_left',
  ARROW_RIGHT_BETWEEN_LINES = 'arrow_right_between_lines',
  ARROW_RIGHT_DOWN = 'arrow_right_down',
  ARROW_RIGHT_FROM_BRACKET = 'arrow_right_from_bracket',
  ARROW_RIGHT_IN_CIRCLE_EMPTY = 'arrow_right_in_circle_empty',
  ARROW_RIGHT_UP = 'arrow_right_up',
  ARROW_RIGHT = 'arrow_right',
  ARROW_ROTATE_LEFT = 'arrow_rotate_left',
  ARROW_ROTATE_RIGHT = 'arrow_rotate_right',
  ARROW_TURN_DOWN_LEFT = 'arrow_turn_down_left',
  ARROW_TURN_DOWN_RIGHT = 'arrow_turn_down_right',
  ARROW_TURN_LEFT_DOWN = 'arrow_turn_left_down',
  ARROW_TURN_LEFT_UP = 'arrow_turn_left_up',
  ARROW_TURN_RIGHT_DOWN = 'arrow_turn_right_down',
  ARROW_TURN_RIGHT_UP = 'arrow_turn_right_up',
  ARROW_TURN_UP_LEFT = 'arrow_turn_up_left',
  ARROW_TURN_UP_RIGHT = 'arrow_turn_up_right',
  ARROW_UP_ARROW_DOWN_H = 'arrow_up_arrow_down_h',
  ARROW_UP_ARROW_DOWN_V = 'arrow_up_arrow_down_v',
  ARROW_UP_BETWEEN_LINES = 'arrow_up_between_lines',
  ARROW_UP_FROM_BRACKET = 'arrow_up_from_bracket',
  ARROW_UP_FROM_DOUBLE_LINE = 'arrow_up_from_double_line',
  ARROW_UP_FROM_LINE = 'arrow_up_from_line',
  ARROW_UP_IN_CIRCLE_EMPTY = 'arrow_up_in_circle_empty',
  ARROW_UP_TO_DOTTED_LINE = 'arrow_up_to_dotted_line',
  ARROW_UP_TO_DOUBLE_LINE = 'arrow_up_to_double_line',
  ARROW_UP_TO_LINE = 'arrow_up_to_line',
  ARROW_UP_WIDE_SHORT = 'arrow_up_wide_short',
  ARROW_UP = 'arrow_up',
  ARROWS_ALL_DIRECTIONS = 'arrows_all_directions',
  ARROWS_COMPARE = 'arrows_compare',
  ARROWS_CROSS = 'arrows_cross',
  ARROWS_DIRECTION_TO_THE_LINES = 'arrows_direction_to_the_lines',
  ARROWS_INSIDE = 'arrows_inside',
  ARROWS_LEFT_RIGHT_BRACKETS = 'arrows_left_right_brackets',
  ARROWS_LEFT_RIGHT_TO_LINES = 'arrows_left_right_to_lines',
  ARROWS_MAXIMIZE = 'arrows_maximize',
  ARROWS_MINIMIZE = 'arrows_minimize',
  ARROWS_OUT = 'arrows_out',
  ARROWS_REPEAT_H = 'arrows_repeat_h',
  ARROWS_REPEAT_V = 'arrows_repeat_v',
  ARROWS_ROTATE_H = 'arrows_rotate_h',
  ARROWS_ROTATE_V = 'arrows_rotate_v',
  ARROWS_SHUFFLE = 'arrows_shuffle',
  ARROWS_SWAP_H = 'arrows_swap_h',
  ARROWS_SWAP_V = 'arrows_swap_v',
  ARROWS_UP_DOWN_TO_LINES = 'arrows_up_down_to_lines',
  AT_SIGN = 'at_sign',
  AUDIO_SPEAKERS = 'audio_speakers',
  AWARD = 'award',
  BAG = 'bag',
  BALLOON = 'balloon',
  BAN = 'ban',
  BAR_AXIS = 'bar_axis',
  BAR_BASIC = 'bar_basic',
  BAR_COLUMNS_AXIS_X = 'bar_columns_axis_x',
  BAR_COLUMNS = 'bar_columns',
  BAR_HISTOGRAM = 'bar_histogram',
  BAR_SQUARE = 'bar_square',
  BAR_STACKED_AXIS = 'bar_stacked_axis',
  BAR_STACKED = 'bar_stacked',
  BARCODE = 'barcode',
  BARS_SORT = 'bars_sort',
  BARS = 'bars',
  BATTERY_BOLT = 'battery_bolt',
  BATTERY_EMPTY = 'battery_empty',
  BATTERY_EXCLAMETION_MARK = 'battery_exclametion_mark',
  BATTERY_FULL = 'battery_full',
  BATTERY_HALF = 'battery_half',
  BATTERY_MINUS = 'battery_minus',
  BATTERY_PLUS = 'battery_plus',
  BATTERY_QUARTER = 'battery_quarter',
  BATTERY_THREE_QUARTERS = 'battery_three_quarters',
  BDRV_ADMINISTRATION = 'bdrv_administration',
  BELL_FILL = 'bell_fill',
  BELL_PLUS = 'bell_plus',
  BELL_RING_FILL = 'bell_ring_fill',
  BELL_RING = 'bell_ring',
  BELL_SLASH = 'bell_slash',
  BELL = 'bell',
  BEZIER_CURVE = 'bezier_curve',
  BITCOIN = 'bitcoin',
  BLOCK_LINES = 'block_lines',
  BLUETOOTH = 'bluetooth',
  BOILER_HOT_WATER_GAS_AND_OIL = 'boiler_hot_water_gas_and_oil',
  BOILER = 'boiler',
  BOLD = 'bold',
  BOOK_STACK = 'book_stack',
  BOOK_CHECK = 'book_check',
  BOOK_CLOSED = 'book_closed',
  BOOK_OPEN_PLUS = 'book_open_plus',
  BOOK_OPEN_RE_ARROW_LEFT = 'book_open_re_arrow_left',
  BOOK_OPEN_RE_ARROW_RIGHT = 'book_open_re_arrow_right',
  BOOK_OPEN_TEXT = 'book_open_text',
  BOOK_OPEN_WITH_PAGE = 'book_open_with_page',
  BOOK_OPEN = 'book_open',
  BOOKMARK_CHECK_FILL = 'bookmark_check_fill',
  BOOKMARK_CHECK = 'bookmark_check',
  BOOKMARK_CROSS_FILL = 'bookmark_cross_fill',
  BOOKMARK_CROSS = 'bookmark_cross',
  BOOKMARK_FILL = 'bookmark_fill',
  BOOKMARK_MUSIC_FILL = 'bookmark_music_fill',
  BOOKMARK_MUSIC = 'bookmark_music',
  BOOKMARK_PLUS_FILL = 'bookmark_plus_fill',
  BOOKMARK_PLUS = 'bookmark_plus',
  BOOKMARK = 'bookmark',
  BORDER_ALL = 'border_all',
  BORDER_BOTTOM = 'border_bottom',
  BORDER_CENTER_H = 'border_center_h',
  BORDER_CENTER_V = 'border_center_v',
  BORDER_INNER = 'border_inner',
  BORDER_LEFT = 'border_left',
  BORDER_NONE = 'border_none',
  BORDER_OUTER = 'border_outer',
  BORDER_RIGHT = 'border_right',
  BORDER_TOP_LEFT = 'border_top_left',
  BORDER_TOP = 'border_top',
  BOX_OPEN_ARROW_DOWN = 'box_open_arrow_down',
  BOX = 'box',
  BRACKETS_CURLY = 'brackets_curly',
  BRACKETS_SQUARE = 'brackets_square',
  BROOM = 'broom',
  BROWSER = 'browser',
  BRUSH = 'brush',
  BUBBLE_MESSAGE_ADD = 'bubble_message_add',
  BUBBLE_MESSAGE_ATTENTION = 'bubble_message_attention',
  BUBBLE_MESSAGE_CIRCLE = 'bubble_message_circle',
  BUBBLE_MESSAGE_EMPTY = 'bubble_message_empty',
  BUBBLE_MESSAGE_OFF = 'bubble_message_off',
  BUBBLE_MESSAGE_QUESTION = 'bubble_message_question',
  BUBBLE_MESSAGE_TEXT = 'bubble_message_text',
  BUBBLE_MESSAGE = 'bubble_message',
  BURN = 'burn',
  CALCULATOR_ARROW_ROTATE_LEFT = 'calculator_arrow_rotate_left',
  CALCULATOR_FUNCTION = 'calculator_function',
  CALCULATOR = 'calculator',
  CALENDAR_BLANK = 'calendar_blank',
  CALENDAR_CHECK = 'calendar_check',
  CALENDAR_CLOCK = 'calendar_clock',
  CALENDAR_DELETED = 'calendar_deleted',
  CALENDAR_EVENT = 'calendar_event',
  CALENDAR_PLUS = 'calendar_plus',
  CALENDAR_QUESTION = 'calendar_question',
  CALENDAR_RANGE = 'calendar_range',
  CALENDAR_TODAY = 'calendar_today',
  CALENDAR = 'calendar',
  CALIBRATION_CHARACTERISTICS_ZQL = 'calibration_characteristics_zql',
  CAMERA_FRONT = 'camera_front',
  CAMERA_MOVIE_CROSS = 'camera_movie_cross',
  CAMERA_MOVIE = 'camera_movie',
  CAMERA = 'camera',
  CAR_JEEP_SIDE_VIEW = 'car_jeep_side_view',
  CAR_LIGHT_SIDE_VIEW = 'car_light_side_view',
  CARBON = 'carbon',
  CAROUSEL_FILL = 'carousel_fill',
  CART_FLATBED_CONTAINER = 'cart_flatbed_container',
  CART_PLUS = 'cart_plus',
  CART = 'cart',
  CELLPHONE_WIRELESS = 'cellphone_wireless',
  CELLPHONE = 'cellphone',
  CHARTS_IQC_ZQL = 'charts_iqc_zql',
  CHECK_DOUBLE = 'check_double',
  CHECKERBOARD = 'checkerboard',
  CHEK = 'chek',
  CHEVRON_DOWN_TO_DOUBLE_LINE = 'chevron_down_to_double_line',
  CHEVRON_DOWN = 'chevron_down',
  CHEVRON_LEFT = 'chevron_left',
  CHEVRON_MINI_LEFT = 'chevron_mini_left',
  CHEVRON_MINI_RIGHT = 'chevron_mini_right',
  CHEVRON_RIGHT_ABOVE_DOUBLE_LINE = 'chevron_right_above_double_line',
  CHEVRON_RIGHT = 'chevron_right',
  CHEVRON_UP = 'chevron_up',
  CHEVRONS_DOUBLE_DOWN = 'chevrons_double_down',
  CHEVRONS_DOUBLE_LEFT = 'chevrons_double_left',
  CHEVRONS_DOUBLE_MINI_LEFT = 'chevrons_double_mini_left',
  CHEVRONS_DOUBLE_MINI_RIGHT = 'chevrons_double_mini_right',
  CHEVRONS_DOUBLE_RIGHT = 'chevrons_double_right',
  CHEVRONS_DOUBLE_UP = 'chevrons_double_up',
  CHEVRONS_INSIDE_HORIZONTALLY = 'chevrons_inside_horizontally',
  CHEVRONS_INSIDE_VERTICALLY = 'chevrons_inside_vertically',
  CHEVRONS_OUTSIDE_HORIZONTALLY = 'chevrons_outside_horizontally',
  CHEVRONS_OUTSIDE_VERTICALLY = 'chevrons_outside_vertically',
  CIRCLE_CHEK_EMPTY = 'circle_chek_empty',
  CIRCLE_CHEK_FILL = 'circle_chek_fill',
  CIRCLE_EXCLAMATION_EMPTY = 'circle_exclamation_empty',
  CIRCLE_EXCLAMATION_FILL = 'circle_exclamation_fill',
  CIRCLE_IN_HEXAGON = 'circle_in_hexagon',
  CIRCLE_INFO_EMPTY = 'circle_info_empty',
  CIRCLE_INFO_FILL = 'circle_info_fill',
  CIRCLE_MUSIC = 'circle_music',
  CIRCLE_PLUS_FILL = 'circle_plus_fill',
  CIRCLE_PLUS = 'circle_plus',
  CIRCLE_QUESTION_EMPTY = 'circle_question_empty',
  CIRCLE_QUESTION_FILL = 'circle_question_fill',
  CIRCLE_SQUARE_FILL = 'circle_square_fill',
  CIRCLE_SQUARE_IN_SQUARE = 'circle_square_in_square',
  CIRCLE_SQUARE = 'circle_square',
  CIRCLE_XMARK_FILL = 'circle_xmark_fill',
  CIRCLE_XMARK = 'circle_xmark',
  CIRCLES_LINE_LEFT_UP_CIRCLE_RIGHT_DOWN_FILL = 'circles_line_left_up_circle_right_down_fill',
  CIRCLES_LINE_LEFT_UP_CIRCLE_RIGHT_DOWN = 'circles_line_left_up_circle_right_down',
  CLAPPERBOARD_CROSS = 'clapperboard_cross',
  CLAPPERBOARD_OPEN = 'clapperboard_open',
  CLOCK_ADD = 'clock_add',
  CLOCK_ARROW_DOWN = 'clock_arrow_down',
  CLOCK_ARROW_RIGHT = 'clock_arrow_right',
  CLOCK_ARROW_UP = 'clock_arrow_up',
  CLOCK_DELETED = 'clock_deleted',
  CLOCK_EXCLAMATION = 'clock_exclamation',
  CLOCK_LINE_END = 'clock_line_end',
  CLOCK_ROTATE_LEFT = 'clock_rotate_left',
  CLOCK_ROTATE_RIGHT = 'clock_rotate_right',
  CLOCK = 'clock',
  CLOUD_ARROW_DOWN = 'cloud_arrow_down',
  CLOUD_ARROW_UP_INSIDE = 'cloud_arrow_up_inside',
  CLOUD_ARROW_UP = 'cloud_arrow_up',
  CLOUD_CHECK = 'cloud_check',
  CLOUD = 'cloud',
  CODE_DOWNLOAD = 'code_download',
  CODE_SIMPLE = 'code_simple',
  CODE = 'code',
  COLLAGE_FILL = 'collage_fill',
  COLLECTION = 'collection',
  COLLECTOR = 'collector',
  COLUMN_FILL = 'column_fill',
  COLUMN = 'column',
  COMPASS = 'compass',
  COMPONENT = 'component',
  CONCRETE_MIXER_SIDE_VIEW = 'concrete_mixer_side_view',
  CONTAINER_V_1 = 'container_v_1',
  CONTAINER_V_2 = 'container_v_2',
  CONTAINERS = 'containers',
  CONTROL_CHARTS_ZQL = 'control_charts_zql',
  COPY_COLUMN = 'copy_column',
  COPY_ROW = 'copy_row',
  COPY = 'copy',
  CRANE = 'crane',
  CREDIT_CARD_PLUS = 'credit_card_plus',
  CREDIT_CARD_SLASH = 'credit_card_slash',
  CREDIT_CARD = 'credit_card',
  CROP = 'crop',
  CROSSHAIRS_DOT = 'crosshairs_dot',
  CROSSHAIRS_SIMPLE = 'crosshairs_simple',
  CUBE_EMPTY = 'cube_empty',
  CUBE_FILL = 'cube_fill',
  CUBES = 'cubes',
  DASHBOARD_FILL = 'dashboard_fill',
  DASHBOARD_VARIANT_FILL = 'dashboard_variant_fill',
  DATABASE_CHEK = 'database_chek',
  DATABASE_JSON = 'database_json',
  DATABASE_MAGNIFYING_GLASS = 'database_magnifying_glass',
  DATABASE_MINUS = 'database_minus',
  DATABASE_PLUS = 'database_plus',
  DATABASE_SQL = 'database_sql',
  DATABASE_XMARK = 'database_xmark',
  DATABASE = 'database',
  DAY_FILL = 'day_fill',
  DECAGRAM_CHEK_EMPTY = 'decagram_chek_empty',
  DECAGRAM_CHEK_FILL = 'decagram_chek_fill',
  DECAGRAM_EXCLAMATION_EMPTY = 'decagram_exclamation_empty',
  DECAGRAM_EXCLAMATION_FILL = 'decagram_exclamation_fill',
  DEFAULT_ICO = 'default_ico',
  DELETE_CONTENT = 'delete_content',
  DESKTOP_TOWER = 'desktop_tower',
  DISCRETE_SET = 'discrete_set',
  DOLLAR_SLASH = 'dollar_slash',
  DOLLAR = 'dollar',
  DOUGHNUT = 'doughnut',
  DROPLET_SLASH = 'droplet_slash',
  DROPLET = 'droplet',
  EARLY_VERSION = 'early_version',
  EARTH = 'earth',
  EDITOR_ALFAVIT = 'editor_alfavit',
  EDITOR_DOWN = 'editor_down',
  EDITOR_RIGHT = 'editor_right',
  ELECTRICS = 'electrics',
  ELLIPSIS_GRID = 'ellipsis_grid',
  ELLIPSIS_H = 'ellipsis_h',
  ELLIPSIS_V = 'ellipsis_v',
  ENERGY_CHECK = 'energy_check',
  ENERGY_SLASH = 'energy_slash',
  ENERGY = 'energy',
  EQUIPMENT_ZQL = 'equipment_zql',
  ERASER = 'eraser',
  ETHERNET = 'ethernet',
  EXCHANGER = 'exchanger',
  EXCLAMATION = 'exclamation',
  EYE_CLOSED = 'eye_closed',
  EYE_SLASH = 'eye_slash',
  EYE = 'eye',
  FACE_FROWN = 'face_frown',
  FACE_SMILE = 'face_smile',
  FACTORY_PIPE = 'factory_pipe',
  FACTORY_PIPES = 'factory_pipes',
  FACTORY = 'factory',
  FAN = 'fan',
  FILE_ARROW_DOWN_LEFT = 'file_arrow_down_left',
  FILE_ARROW_DOWN = 'file_arrow_down',
  FILE_ARROW_UP = 'file_arrow_up',
  FILE_ARROW = 'file_arrow',
  FILE_ARROWS_UP_RIGHT = 'file_arrows_up_right',
  FILE_CAMERA = 'file_camera',
  FILE_CROSS_OUT = 'file_cross_out',
  FILE_CROSS = 'file_cross',
  FILE_DOC = 'file_doc',
  FILE_DOCX = 'file_docx',
  FILE_DOT = 'file_dot',
  FILE_EMPTY = 'file_empty',
  FILE_EXCLAMATION = 'file_exclamation',
  FILE_EYE = 'file_eye',
  FILE_FILLED = 'file_filled',
  FILE_IMAGE = 'file_image',
  FILE_MAGNIFYING_GLASS = 'file_magnifying_glass',
  FILE_MINUS = 'file_minus',
  FILE_MUSIC = 'file_music',
  FILE_PDF = 'file_pdf',
  FILE_PEN = 'file_pen',
  FILE_PLAY = 'file_play',
  FILE_PLUS = 'file_plus',
  FILE_PPT = 'file_ppt',
  FILE_PPTX = 'file_pptx',
  FILE_TXT = 'file_txt',
  FILE_UP_RIGHT = 'file_up_right',
  FILE_XLS = 'file_xls',
  FILE_XLSX = 'file_xlsx',
  FILES_MODE = 'files_mode',
  FILL = 'fill',
  FILM_CROSS = 'film_cross',
  FILM = 'film',
  FILTER_GEAR = 'filter_gear',
  FILTER_ONTOLOGY = 'filter_ontology',
  FILTER = 'filter',
  FINANCE_SCANNER = 'finance_scanner',
  FIRE = 'fire',
  FLAG_FILL_RED = 'flag_fill_red',
  FLAG_FILL = 'flag_fill',
  FLAG = 'flag',
  FLASK_ROUND_POTION = 'flask_round_potion',
  FLASK = 'flask',
  FLOPPY_CROSS_OUT = 'floppy_cross_out',
  FLOPPY_CROSS = 'floppy_cross',
  FLOPPY_PEN = 'floppy_pen',
  FLOPPY_STAR = 'floppy_star',
  FLOPPY = 'floppy',
  FOLDER_OPEN = 'folder_open',
  FOLDER_UNDERLINE_MINUS = 'folder_underline_minus',
  FOLDER_UNDERLINE_PLUS = 'folder_underline_plus',
  FOLDER_UNDERLINE = 'folder_underline',
  FOLDER_ARROW_DOWN_LEFT = 'folder_arrow_down_left',
  FOLDER_ARROW_DOWN = 'folder_arrow_down',
  FOLDER_ARROW_UP_RIGHT = 'folder_arrow_up_right',
  FOLDER_CROSS = 'folder_cross',
  FOLDER_DOT = 'folder_dot',
  FOLDER_MINUS = 'folder_minus',
  FOLDER_PLUS = 'folder_plus',
  FOLDER = 'folder',
  FORVARD_STEP = 'forvard_step',
  FORWARD = 'forward',
  FUEL_OIL_TANK = 'fuel_oil_tank',
  FUNCTION = 'function',
  GANTT = 'gantt',
  GAS_MONITORING = 'gas_monitoring',
  GAS_PUMP = 'gas_pump',
  GAS = 'gas',
  GAUGE = 'gauge',
  GEAR_5_EDGE = 'gear_5_edge',
  GEAR_8_EDGE = 'gear_8_edge',
  GEAR_COOLING = 'gear_cooling',
  GENERATOR = 'generator',
  GIFT = 'gift',
  GIT_LAB = 'git_lab',
  GLOBE = 'globe',
  GRID_FILL = 'grid_fill',
  GRID = 'grid',
  GRIP_DOTS_VERTICAL = 'grip_dots_vertical',
  HARD_DRIVE_OUTLINE = 'hard_drive_outline',
  HASH_DASH = 'hash_dash',
  HASH = 'hash',
  HASHTAG = 'hashtag',
  HEADLINE_FILL = 'headline_fill',
  HEADPHONES = 'headphones',
  HEART_EMPTY = 'heart_empty',
  HEART_FILL = 'heart_fill',
  HELICOPTER_SIDE_VIEW = 'helicopter_side_view',
  HEXAGON_EXCLAMATION_EMPTY = 'hexagon_exclamation_empty',
  HEXAGON_EXCLAMATION_FILL = 'hexagon_exclamation_fill',
  HEXAGON_FILL = 'hexagon_fill',
  HEXAGON = 'hexagon',
  HEXAGONS_AXIS = 'hexagons_axis',
  HEXAGONS = 'hexagons',
  HISTOGRAM_AXIS = 'histogram_axis',
  HOUSE_MINI = 'house_mini',
  HOUSE = 'house',
  IMAGE = 'image',
  INDENT_ARROW_LEFT = 'indent_arrow_left',
  INDENT_ARROW_RIGHT = 'indent_arrow_right',
  INFINITY = 'infinity',
  INFO = 'info',
  INPUT_DEVICE = 'input_device',
  INSTAGRAM = 'instagram',
  ITALIC = 'italic',
  KEY = 'key',
  KEYBOARD_CLOSE = 'keyboard_close',
  KEYBOARD = 'keyboard',
  LABEL_CROSS = 'label_cross',
  LABEL_EXCLAMATION_MARK = 'label_exclamation_mark',
  LABEL_FILL = 'label_fill',
  LABEL_MAGNIFYING_GLASS = 'label_magnifying_glass',
  LABEL_PLUS = 'label_plus',
  LABEL_QUESTION = 'label_question',
  LABEL_TEXT = 'label_text',
  LABEL = 'label',
  LAN_CONNECT = 'lan_connect',
  LAN_DISCONNECT = 'lan_disconnect',
  LAN_PENDING = 'lan_pending',
  LAPTOP_PHONE_SLASH = 'laptop_phone_slash',
  LAPTOP_PHONE = 'laptop_phone',
  LAPTOP_SLASH = 'laptop_slash',
  LAPTOP = 'laptop',
  LAYER_GROUP_SLASH = 'layer_group_slash',
  LAYER_GROUP = 'layer_group',
  LAYER_NETWORK = 'layer_network',
  LETTER_DAY = 'letter_day',
  LETTER_HOUR = 'letter_hour',
  LETTER_MINUTE = 'letter_minute',
  LETTER_MONTH = 'letter_month',
  LETTER_SECOND = 'letter_second',
  LETTER_TIME = 'letter_time',
  LETTER_YEAR = 'letter_year',
  LIBRARY_PLUS = 'library_plus',
  LIGHTBULB = 'lightbulb',
  LINE_AXIS_ARROW_DOWN = 'line_axis_arrow_down',
  LINE_AXIS_X = 'line_axis_x',
  LINE_AXIS = 'line_axis',
  LINE_DOWN = 'line_down',
  LINE_HEIGHT = 'line_height',
  LINE_MULTIPLE_Y_AXIS_X = 'line_multiple_y_axis_x',
  LINE_MULTIPLE_Y_AXIS = 'line_multiple_y_axis',
  LINE_UP = 'line_up',
  LINE = 'line',
  LINK_BREAK = 'link_break',
  LINK_MINUS = 'link_minus',
  LINK_PLUS = 'link_plus',
  LINK_SIMPLE_H = 'link_simple_h',
  LINK_SIMPLE = 'link_simple',
  LIST_SQUARE = 'list_square',
  LIST_FILL = 'list_fill',
  LIST_OL = 'list_ol',
  LIST_TREE_ARCHIVE = 'list_tree_archive',
  LIST_TREE = 'list_tree',
  LIST_UL = 'list_ul',
  LIST = 'list',
  LNG_STORAGE = 'lng_storage',
  LOADER = 'loader',
  LOCATION_ARROW = 'location_arrow',
  LOCATION_DIRECTLY = 'location_directly',
  LOCATION_DOT = 'location_dot',
  LOCATION_MINUS = 'location_minus',
  LOCATION_PLUS = 'location_plus',
  LOCATION_SLASH = 'location_slash',
  LOCATION_USER = 'location_user',
  LOCK = 'lock',
  LOGO_GREY_Z = 'logo_grey_z',
  MAGIC_WAND = 'magic_wand',
  MAGNIFYING_GLASS_EXCLAMATION = 'magnifying_glass_exclamation',
  MAGNIFYING_GLASS_MINUS = 'magnifying_glass_minus',
  MAGNIFYING_GLASS_ONTOLOGY = 'magnifying_glass_ontology',
  MAGNIFYING_GLASS_PLUS = 'magnifying_glass_plus',
  MAGNIFYING_GLASS_TAGS_WORDS = 'magnifying_glass_tags_words',
  MAGNIFYING_GLASS_TOP_FROM_BRACKET = 'magnifying_glass_top_from_bracket',
  MAGNIFYING_GLASS_TRIANGLE_DOWN = 'magnifying_glass_triangle_down',
  MAGNIFYING_GLASS_XMARK = 'magnifying_glass_xmark',
  MAGNIFYING_GLASS = 'magnifying_glass',
  MAIL_OPEN = 'mail_open',
  MAIL = 'mail',
  MAILBOX = 'mailbox',
  MAP_BASE = 'map_base',
  MAP_MARKER_DATE_V_1 = 'map_marker_date_v_1',
  MAP_MARKER_DATE_V_2 = 'map_marker_date_v_2',
  MAP_PIN = 'map_pin',
  MAP = 'map',
  MEDICAL = 'medical',
  MERGE = 'merge',
  MESSAGING_TELEGRAM_SEND = 'messaging_telegram_send',
  MESSAGING_TELEGRAM = 'messaging_telegram',
  MICROPHONE_SLASH = 'microphone_slash',
  MICROPHONE = 'microphone',
  MINIBUS_SIDE_VIEW = 'minibus_side_view',
  MINUS_CIRCLE_FILL = 'minus_circle_fill',
  MINUS_CIRCLE = 'minus_circle',
  MINUS = 'minus',
  MODULE_FILL = 'module_fill',
  MONITOR = 'monitor',
  MOON = 'moon',
  MUSIC_SLASH = 'music_slash',
  MUSIC = 'music',
  NETWORK_EXTERNAL_LINK = 'network_external_link',
  NETWORK_V_1 = 'network_v_1',
  NETWORK_V_2 = 'network_v_2',
  NETWORK_V_3 = 'network_v_3',
  NETWORK_WIRED = 'network_wired',
  NI_FI_LOGO = 'ni_fi_logo',
  NORMDOCS_ZQL = 'normdocs_zql',
  NPM = 'npm',
  OBJECT_DOWN_SUBTRACT = 'object_down_subtract',
  OBJECT_EXCLUDE = 'object_exclude',
  OBJECT_INTERSECT = 'object_intersect',
  OBJECT_SELECTION = 'object_selection',
  OBJECT_UNION = 'object_union',
  OBJECT_UP_SUBTRACT = 'object_up_subtract',
  OBJECT = 'object',
  OIL_BARREL = 'oil_barrel',
  OIL_CANISTER = 'oil_canister',
  OIL_DROPLET_ARROWS_ALL = 'oil_droplet_arrows_all',
  OIL_DROPLET_ARROWS_REPEAT_H = 'oil_droplet_arrows_repeat_h',
  OIL_DROPLET_CHEK = 'oil_droplet_chek',
  OIL_DROPLET = 'oil_droplet',
  OIL_FIELD = 'oil_field',
  OIL_TANK = 'oil_tank',
  ONTOLOGY = 'ontology',
  OWL = 'owl',
  PALETTE = 'palette',
  PANEL_DOWN = 'panel_down',
  PANEL_LEFT = 'panel_left',
  PANEL_RIGHT = 'panel_right',
  PANEL_TOP = 'panel_top',
  PANTONE = 'pantone',
  PAPERCLIP_VERTICAL = 'paperclip_vertical',
  PAPERCLIP = 'paperclip',
  PAUSE = 'pause',
  PAVER_SIDE_VIEW = 'paver_side_view',
  PEN_HAMMER = 'pen_hammer',
  PENCIL_ARROW_RIGHT = 'pencil_arrow_right',
  PENCIL_LINE_BOTTOM = 'pencil_line_bottom',
  PENCIL_TRIANGLE_DOWN = 'pencil_triangle_down',
  PENCIL_TRIANGLE_LEFT = 'pencil_triangle_left',
  PENCIL = 'pencil',
  PENTAGON_FILL = 'pentagon_fill',
  PENTAGON = 'pentagon',
  PERCENT = 'percent',
  PHONE_ACTIVE_CALL = 'phone_active_call',
  PHONE_CANCELLED = 'phone_cancelled',
  PHONE_MINUS = 'phone_minus',
  PHONE_OFF = 'phone_off',
  PHONE_PAUSED = 'phone_paused',
  PHONE_PLUS = 'phone_plus',
  PHONE = 'phone',
  PI = 'pi',
  PIE_LINE_NESTED = 'pie_line_nested',
  PIE_LINE = 'pie_line',
  PIE_PENTAGON = 'pie_pentagon',
  PIE_SEVERAL_PARTS = 'pie_several_parts',
  PIE_SIMPLE = 'pie_simple',
  PIE = 'pie',
  PIPE_NODE_SIDE_VIEW = 'pipe_node_side_view',
  PIPE_SENSOR = 'pipe_sensor',
  PIPE_SLASH = 'pipe_slash',
  PIPE_VALVE = 'pipe_valve',
  PIPELINE_V_1 = 'pipeline_v_1',
  PIPELINE_V_2 = 'pipeline_v_2',
  PIPETTE = 'pipette',
  PLANE = 'plane',
  PLAY_BACK = 'play_back',
  PLAY = 'play',
  PLUS_COLUMN_RIGHT = 'plus_column_right',
  PLUS_COLUMN_TOP = 'plus_column_top',
  PLUS_TRIANGLE_DOWN = 'plus_triangle_down',
  PLUS = 'plus',
  POLYLINE = 'polyline',
  PORTFEL = 'portfel',
  POWER = 'power',
  PREMISES_ZQL = 'premises_zql',
  PRESS = 'press',
  PRINTER = 'printer',
  PROCESS = 'process',
  PULSE = 'pulse',
  PUMP_TRIANGLE_DOWN = 'pump_triangle_down',
  PUMP = 'pump',
  PUSH_BUTTON_CELLPHONE = 'push_button_cellphone',
  QR = 'qr',
  QUESTION = 'question',
  QUILT_FILL = 'quilt_fill',
  RADIATION = 'radiation',
  RAILCAR_HOPPER_SIDE_VIEW = 'railcar_hopper_side_view',
  RAILCAR_SIDE_VIEW = 'railcar_side_view',
  RANGE = 'range',
  REPLAY = 'replay',
  RESPIRATOR_V_1 = 'respirator_v_1',
  RESPIRATOR_V_2 = 'respirator_v_2',
  RESPIRATOR_V_3 = 'respirator_v_3',
  RESPIRATOR_V_4 = 'respirator_v_4',
  RESPIRATOR_V_5 = 'respirator_v_5',
  RESPIRATOR_V_6 = 'respirator_v_6',
  RETURN_STEP = 'return_step',
  RETURN = 'return',
  RHOMBUS_FILL = 'rhombus_fill',
  RHOMBUS = 'rhombus',
  RING_IN_SQUARE = 'ring_in_square',
  RULER_INDEX_ZQL = 'ruler_index_zql',
  RULER = 'ruler',
  SAMPLE_LOGS_ZQL = 'sample_logs_zql',
  SAMPLE_TEMPLATES_ZQL = 'sample_templates_zql',
  SANDGLASS = 'sandglass',
  SCATTER_AXIS = 'scatter_axis',
  SCATTER_BASIC = 'scatter_basic',
  SCATTER = 'scatter',
  SCISSORS = 'scissors',
  SEEDLING_CIRCLE = 'seedling_circle',
  SEEDLING_RECTANGLE = 'seedling_rectangle',
  SEEDLING = 'seedling',
  SELECTION_CHECKED_EMPTY = 'selection_checked_empty',
  SEND_BACKWARD = 'send_backward',
  SEND_FORWARD = 'send_forward',
  SEPARATOR = 'separator',
  SEQUENTIAL_FILL = 'sequential_fill',
  SERVER_NETWORK_CLOSE = 'server_network_close',
  SERVER_NETWORK_DOWNLOAD = 'server_network_download',
  SERVER_NETWORK_MINUS = 'server_network_minus',
  SERVER_NETWORK_PLUS = 'server_network_plus',
  SERVER_NETWORK_SECURITY = 'server_network_security',
  SERVER_NETWORK_UPLOAD = 'server_network_upload',
  SERVER_NETWORK = 'server_network',
  SERVER_SHIELD = 'server_shield',
  SERVER_SLASH_UP_LINE = 'server_slash_up_line',
  SERVER_SLASH = 'server_slash',
  SERVER_UP_LINE = 'server_up_line',
  SERVER = 'server',
  SHAPE_LINK_FILL = 'shape_link_fill',
  SHAPE_LINK = 'shape_link',
  SHAPE_PLUS = 'shape_plus',
  SHARE_LEFT = 'share_left',
  SHARE_RIGHT = 'share_right',
  SHAREING = 'shareing',
  SHIELD_EXCLAMATION = 'shield_exclamation',
  SHIELD_SLASH = 'shield_slash',
  SHIELD = 'shield',
  SHIP_FRONT_VIEW = 'ship_front_view',
  SHIP_SIDE_VIEW = 'ship_side_view',
  SHOPPING_BOX = 'shopping_box',
  SHOVEL = 'shovel',
  SIGMA = 'sigma',
  SIGNAL_ACCESS_POINT = 'signal_access_point',
  SIGNAL_OFF = 'signal_off',
  SIGNAL_RADIO_TOWER = 'signal_radio_tower',
  SIGNAL = 'signal',
  SLIDERS_H = 'sliders_h',
  SLIDERS_V = 'sliders_v',
  SNAKE_CUP = 'snake_cup',
  SNOWFLAKE_UP_TO_BRACKET = 'snowflake_up_to_bracket',
  SNOWFLAKE = 'snowflake',
  SORT_FILTER_REMOVE = 'sort_filter_remove',
  SPECIFICATION = 'specification',
  SPECS_ZQL = 'specs_zql',
  SPEED_REDUCTION_COOLING = 'speed_reduction_cooling',
  SQUARE_ARROWS_CURVE_RIGHT_DOWN = 'square_arrows_curve_right_down',
  SQUARE_ARROWS_CURVE_UP_RIGHT = 'square_arrows_curve_up_right',
  SQUARE_BRACKET_CURLY_LEFT = 'square_bracket_curly_left',
  SQUARE_BRACKET_CURLY_RIGHT = 'square_bracket_curly_right',
  SQUARE_BRACKET_LEFT = 'square_bracket_left',
  SQUARE_BRACKET_RIGHT = 'square_bracket_right',
  SQUARE_CIRCLE_PLUS_TRIANGLE_FILL = 'square_circle_plus_triangle_fill',
  SQUARE_CIRCLE_TRIANGLE_CROSS_FILL = 'square_circle_triangle_cross_fill',
  SQUARE_CIRCLE_TRIANGLE_CROSS = 'square_circle_triangle_cross',
  SQUARE_DIVIDE = 'square_divide',
  SQUARE_EXCEL = 'square_excel',
  SQUARE_EXCLAMATION_EMPTY = 'square_exclamation_empty',
  SQUARE_EXCLAMATION_FILL = 'square_exclamation_fill',
  SQUARE_FILL = 'square_fill',
  SQUARE_HEXAGON_CIRCLE_FILL = 'square_hexagon_circle_fill',
  SQUARE_HEXAGON_CIRCLE = 'square_hexagon_circle',
  SQUARE_IN_SQUARE = 'square_in_square',
  SQUARE_INFO_EMPTY = 'square_info_empty',
  SQUARE_INFO_FILL = 'square_info_fill',
  SQUARE_MINUS = 'square_minus',
  SQUARE_MULTIPLY = 'square_multiply',
  SQUARE_MUSIC_DOUBLE = 'square_music_double',
  SQUARE_MUSIC = 'square_music',
  SQUARE_PERCENT = 'square_percent',
  SQUARE_PLUS = 'square_plus',
  SQUARE_POWERPOINT = 'square_powerpoint',
  SQUARE_QUESTION_EMPTY = 'square_question_empty',
  SQUARE_QUESTION_FILL = 'square_question_fill',
  SQUARE_TRIANGLE_CIRCLE_TRIANGLE_FILL = 'square_triangle_circle_triangle_fill',
  SQUARE_TRIANGLE_CIRCLE_TRIANGLE = 'square_triangle_circle_triangle',
  SQUARE_WORD = 'square_word',
  STAR_EMPTY = 'star_empty',
  STAR_FILL = 'star_fill',
  STAR_HALF_FILL = 'star_half_fill',
  STAR_LINE = 'star_line',
  STEAM_BOILER = 'steam_boiler',
  STEAM_TURBINE = 'steam_turbine',
  STEAM = 'steam',
  STOP = 'stop',
  STOPWATCH = 'stopwatch',
  STORAGE = 'storage',
  STRIKETHROUGH = 'strikethrough',
  SUBSKRIT_DOWN = 'subskrit_down',
  SUBSKRIT_UP = 'subskrit_up',
  SUMBOL_ASTERISK = 'sumbol_asterisk',
  SUN = 'sun',
  SUPPORT_MAN = 'support_man',
  TABLE_DOWN = 'table_down',
  TABLE_GEAR = 'table_gear',
  TABLE_MAGNIFYING_GLASS = 'table_magnifying_glass',
  TABLE_RIGHT = 'table_right',
  TABLE_TRANSPOSE_RIGHT = 'table_transpose_right',
  TABLE_TRANSPOSE_TOP = 'table_transpose_top',
  TABLE_TRANSPOSE = 'table_transpose',
  TABLE = 'table',
  TABLET_IQC_ZQL = 'tablet_iqc_zql',
  TABLET = 'tablet',
  TANK = 'tank',
  TANKCAR_OIL_SIDE_VIEW = 'tankcar_oil_side_view',
  TANKCAR_SIDE_VIEW = 'tankcar_side_view',
  TECHS_ZQL = 'techs_zql',
  TEMPERATURE_MINUS = 'temperature_minus',
  TEMPERATURE_PLUS = 'temperature_plus',
  TEMPERATURE = 'temperature',
  TEMPLATE = 'template',
  TEXT_COLOR = 'text_color',
  TEXT = 'text',
  THUMB_DOWN = 'thumb_down',
  THUMB_UP = 'thumb_up',
  THUMBTACK_DIRECTLY = 'thumbtack_directly',
  THUMBTACK = 'thumbtack',
  TOUCHPAD = 'touchpad',
  TRAIN_CARGO = 'train_cargo',
  TRAIN_PASSENGER = 'train_passenger',
  TRANSMITTER = 'transmitter',
  TRASH_EMPTY = 'trash_empty',
  TRASH = 'trash',
  TRIANGLE_CIRCLE_SQUARE_FILL = 'triangle_circle_square_fill',
  TRIANGLE_CIRCLE_SQUARE = 'triangle_circle_square',
  TRIANGLE_CROSS_EMPTY = 'triangle_cross_empty',
  TRIANGLE_DOWN = 'triangle_down',
  TRIANGLE_EXCLAMATION_EMPTY = 'triangle_exclamation_empty',
  TRIANGLE_EXCLAMATION_FILL = 'triangle_exclamation_fill',
  TRIANGLE_FILL = 'triangle_fill',
  TRIANGLE_INFO_EMPTY = 'triangle_info_empty',
  TRIANGLE_INFO_FILL = 'triangle_info_fill',
  TRIANGLE_LEFT = 'triangle_left',
  TRIANGLE_PLUS_EMPTY = 'triangle_plus_empty',
  TRIANGLE_RIGHT = 'triangle_right',
  TRIANGLE_UP_DOWN = 'triangle_up_down',
  TRIANGLE_UP = 'triangle_up',
  TRIANGLE = 'triangle',
  TRUCK_DUMP_SIDE_VIEW = 'truck_dump_side_view',
  TRUCK_EMPTY_SIDE_VIEW = 'truck_empty_side_view',
  TRUCK_GARBAGE_SIDE_VIEW = 'truck_garbage_side_view',
  TRUCK_GASOLINE_SIDE_VIEW = 'truck_gasoline_side_view',
  TRUCK_SIDE_VIEW = 'truck_side_view',
  TV = 'tv',
  UMBRELLA = 'umbrella',
  UNDERLINED = 'underlined',
  UNION = 'union',
  UNLOCK = 'unlock',
  USER_ARROWS_SWAP = 'user_arrows_swap',
  USER_CARD = 'user_card',
  USER_CHECK = 'user_check',
  USER_CIRCLE = 'user_circle',
  USER_CROSS = 'user_cross',
  USER_GEAR = 'user_gear',
  USER_GROUP = 'user_group',
  USER_LOCATION = 'user_location',
  USER_MINUS = 'user_minus',
  USER_PLUS = 'user_plus',
  USER_SHIELD = 'user_shield',
  USER_WORKER = 'user_worker',
  USER = 'user',
  USERS_ARROW_RIGHT = 'users_arrow_right',
  USERS_ARROW_UP_ZQL = 'users_arrow_up_zql',
  USERS_GEAR = 'users_gear',
  USERS_KEY = 'users_key',
  USERS_LOCATION = 'users_location',
  USERS_MINUS = 'users_minus',
  USERS_PLUS = 'users_plus',
  USERS = 'users',
  VECTOR_CIRCLE_ONE_POINT = 'vector_circle_one_point',
  VECTOR_CIRCLE_TWO_POINT = 'vector_circle_two_point',
  VECTOR_CIRCLE = 'vector_circle',
  VECTOR_LINE = 'vector_line',
  VECTOR_POINT = 'vector_point',
  VECTOR_POLYGON = 'vector_polygon',
  VECTOR_RECTANGLE = 'vector_rectangle',
  VECTOR_SQUARE = 'vector_square',
  VECTOR_TRIANGLE = 'vector_triangle',
  VECTORS_RADIUS = 'vectors_radius',
  VIAL_FLASK = 'vial_flask',
  VIAL_PLUS = 'vial_plus',
  VIAL_ROTATE_LEFT = 'vial_rotate_left',
  VIAL_XMARK = 'vial_xmark',
  VIAL = 'vial',
  VIDEO_CROSS = 'video_cross',
  VIDEO_SLASH = 'video_slash',
  VIDEO = 'video',
  VOICEMAIL = 'voicemail',
  VOLUME_CROSS = 'volume_cross',
  VOLUME_LOW = 'volume_low',
  VOLUME_MINUS = 'volume_minus',
  VOLUME_OFF = 'volume_off',
  VOLUME_PLUS = 'volume_plus',
  VOLUME_SLASH = 'volume_slash',
  VOLUME = 'volume',
  WALLET = 'wallet',
  WATCH = 'watch',
  WATER_HEATER = 'water_heater',
  WATER_PUMP = 'water_pump',
  WEBCAM = 'webcam',
  WIFI_OFF = 'wifi_off',
  WIFI = 'wifi',
  WINDOW = 'window',
  WRENCH = 'wrench',
  XMARK_COLUMN_RIGHT = 'xmark_column_right',
  XMARK_COLUMN_TOP = 'xmark_column_top',
  XMARK = 'xmark'
}
