/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsCircleSquare: {
  name: 'circle_square';
  data: string;
} = {
  name: 'circle_square',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_430_11595)"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.5 5C1.5 3.067 3.067 1.5 5 1.5C6.933 1.5 8.5 3.067 8.5 5C8.5 6.933 6.933 8.5 5 8.5C3.067 8.5 1.5 6.933 1.5 5ZM5 0.5C2.51472 0.5 0.5 2.51472 0.5 5C0.5 7.48528 2.51472 9.5 5 9.5C7.48528 9.5 9.5 7.48528 9.5 5C9.5 2.51472 7.48528 0.5 5 0.5ZM10 8.5C9.17157 8.5 8.5 9.17157 8.5 10V14C8.5 14.8284 9.17157 15.5 10 15.5H14C14.8284 15.5 15.5 14.8284 15.5 14V10C15.5 9.17157 14.8284 8.5 14 8.5H10ZM9.5 10C9.5 9.72386 9.72386 9.5 10 9.5H14C14.2761 9.5 14.5 9.72386 14.5 10V14C14.5 14.2761 14.2761 14.5 14 14.5H10C9.72386 14.5 9.5 14.2761 9.5 14V10Z" fill="#6E778C"/></g><defs><clipPath id="clip0_430_11595"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`,
};
