/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsBarBasic: {
  name: 'bar_basic';
  data: string;
} = {
  name: 'bar_basic',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_382_12644)"><path fill-rule="evenodd" clip-rule="evenodd" d="M15.5 1C15.5 0.723858 15.2761 0.5 15 0.5C14.7239 0.5 14.5 0.723858 14.5 1V15C14.5 15.2761 14.7239 15.5 15 15.5C15.2761 15.5 15.5 15.2761 15.5 15V1ZM10.5 4C10.5 3.72386 10.2761 3.5 10 3.5C9.72386 3.5 9.5 3.72386 9.5 4L9.5 15C9.5 15.2761 9.72386 15.5 10 15.5C10.2761 15.5 10.5 15.2761 10.5 15L10.5 4ZM5 7.5C5.27614 7.5 5.5 7.72386 5.5 8L5.5 15C5.5 15.2761 5.27614 15.5 5 15.5C4.72386 15.5 4.5 15.2761 4.5 15L4.5 8C4.5 7.72386 4.72386 7.5 5 7.5ZM1.5 11C1.5 10.7239 1.27614 10.5 1 10.5C0.723858 10.5 0.5 10.7239 0.5 11V15C0.5 15.2761 0.723858 15.5 1 15.5C1.27614 15.5 1.5 15.2761 1.5 15L1.5 11Z" fill="#6E778C"/></g><defs><clipPath id="clip0_382_12644"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`,
};
