/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSquareArrowsCurveRightDown: {
  name: 'square-arrows-curve-right-down';
  data: string;
} = {
  name: 'square-arrows-curve-right-down',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.5 2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 0 0-1H2A1.5 1.5 0 0 0 .5 2v12A1.5 1.5 0 0 0 2 15.5h12a1.5 1.5 0 0 0 1.5-1.5V4a.5.5 0 0 0-1 0v10a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V2Zm3.146 6.354a.5.5 0 1 1 .708-.708l1.191 1.192c.127-1.61.543-3.428 1.535-4.96C9.344 1.928 11.506.5 15 .5a.5.5 0 0 1 0 1c-3.172 0-5.01 1.271-6.08 2.922C8.008 5.828 7.63 7.549 7.529 9.1L9.243 8.07a.5.5 0 0 1 .514.858l-2.5 1.5a.5.5 0 0 1-.61-.075l-2-2Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`
};
