/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsTempPoiDifference: {
  name: 'temp-poi-difference';
  data: string;
} = {
  name: 'temp-poi-difference',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M8 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2ZM.5 4A1.5 1.5 0 0 1 2 2.5h2A1.5 1.5 0 0 1 5.5 4v8A1.5 1.5 0 0 1 4 13.5H2A1.5 1.5 0 0 1 .5 12V4ZM2 3.5a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5V4a.5.5 0 0 0-.5-.5H2Zm8.5.5A1.5 1.5 0 0 1 12 2.5h2A1.5 1.5 0 0 1 15.5 4v8a1.5 1.5 0 0 1-1.5 1.5h-2a1.5 1.5 0 0 1-1.5-1.5V4Zm1.5-.5a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5V4a.5.5 0 0 0-.5-.5h-2ZM9 5a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM8 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm1 2a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-1 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z" fill="currentColor"/></svg>`
};
