/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsBezierCurve: {
  name: 'bezier-curve';
  data: string;
} = {
  name: 'bezier-curve',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M10 3a1 1 0 1 0-.966-.741l-.888.887A.503.503 0 0 0 8.1 3.2a3.5 3.5 0 0 0-4.9 4.9.503.503 0 0 0-.054.046l-.887.888A1.001 1.001 0 0 0 1 10a1 1 0 1 0 1.966-.259l.888-.887A.503.503 0 0 0 3.9 8.8c.322.242.687.43 1.082.55A11.45 11.45 0 0 0 3.5 15a.5.5 0 0 0 1 0c0-2.018.569-3.901 1.554-5.5A3.5 3.5 0 0 0 9.5 6.054 10.449 10.449 0 0 1 15 4.5a.5.5 0 0 0 0-1 11.45 11.45 0 0 0-5.65 1.482A3.488 3.488 0 0 0 8.8 3.9a.503.503 0 0 0 .054-.046l.887-.888c.083.022.17.034.259.034Zm-4 .5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5Z" fill="currentColor"/></svg>`,
};
