/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsTempLocationLocalizationDownList: {
  name: 'temp-location-localization-down-list';
  data: string;
} = {
  name: 'temp-location-localization-down-list',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M9.136 1.599c.242.326.518.73.794 1.197.71 1.2 1.44 2.849 1.555 4.704h2.996a6.503 6.503 0 0 0-5.345-5.901Zm1.123 8.28c.112-.445.19-.906.223-1.379H5.518c.113 1.613.753 3.082 1.412 4.195A12.987 12.987 0 0 0 8 14.235c.162-.2.366-.465.588-.787a.5.5 0 1 1 .824.567c-.096.138-.188.267-.276.386.246-.043.486-.1.721-.17a.5.5 0 1 1 .286.958 7.5 7.5 0 1 1 5.047-5.047.5.5 0 1 1-.96-.285c.13-.434.215-.889.251-1.357h-2.996a8.92 8.92 0 0 1-.256 1.622.5.5 0 0 1-.97-.244ZM9.07 3.304c.66 1.113 1.3 2.582 1.413 4.195H5.518c.113-1.613.753-3.082 1.412-4.195A12.986 12.986 0 0 1 8 1.765l.077.096c.27.34.632.834.993 1.444Zm-3-.51c-.71 1.2-1.439 2.85-1.553 4.705H1.519a6.503 6.503 0 0 1 5.345-5.901c-.242.326-.518.73-.794 1.197ZM1.52 8.5h2.997c.114 1.855.843 3.505 1.554 4.704.276.467.552.87.794 1.197A6.503 6.503 0 0 1 1.519 8.5ZM12.5 15 10 12h5l-2.5 3Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
