/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSnakeCup: {
  name: 'snake-cup';
  data: string;
} = {
  name: 'snake-cup',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M14 4c-1.677 0-3.298.833-4.106 2.447a1 1 0 1 1-1.788-.894C9.298 3.167 11.676 2 14 2a7 7 0 0 1 7 7v.005c-.003 5.3-4.478 9.498-10 9.954V20h4a1 1 0 1 1 0 2H5a1 1 0 0 1-1-1c0-1.318.885-2.34 1.95-2.979.845-.507 1.901-.843 3.05-.968V15.93a7.005 7.005 0 0 1-5.904-5.768C2.884 8.893 3.95 8 5 8h10c1.05 0 2.116.893 1.904 2.16A7.005 7.005 0 0 1 11 15.93v1.022c4.58-.446 8-3.919 8-7.952v-.004A5 5 0 0 0 14 4ZM9 19.068c-.806.113-1.501.356-2.021.668a3.236 3.236 0 0 0-.38.264H9v-.932ZM10 14a5.002 5.002 0 0 1-4.9-4h9.8a5.002 5.002 0 0 1-4.9 4Zm-5-4h-.001Z" fill="currentColor"/></svg>`
};
