/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsPulse: {
  name: 'pulse';
  data: string;
} = {
  name: 'pulse',
  data: `<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M7.95409 6.56478C8.83236 5.0278 11.1273 5.30551 11.6136 7.00761L14.3094 16.4429L16.8438 12.0077C17.1999 11.3846 17.8626 11 18.5803 11H21C21.5523 11 22 11.4477 22 12C22 12.5523 21.5523 13 21 13H18.5803L16.0459 17.4352C15.1676 18.9722 12.8727 18.6945 12.3864 16.9924L9.69057 7.55706L7.15616 11.9923C6.80008 12.6154 6.13739 13 5.41968 13H3C2.44772 13 2 12.5523 2 12C2 11.4477 2.44772 11 3 11H5.41968L7.95409 6.56478Z" fill="currentColor"/></svg>`,
};
