/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSquareBracketCurlyLeft: {
  name: 'square_bracket_curly_left';
  data: string;
} = {
  name: 'square_bracket_curly_left',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#square-bracket-curly-left_svg__clip0_389_13139)"><rect x="1" y="1" width="14" height="14" rx="1" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/><path d="M10 4H8V7L6 8L8 9V12H10" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/></g><defs><clipPath id="square-bracket-curly-left_svg__clip0_389_13139"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`,
};
