/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsShapeLink: {
  name: 'shape_link';
  data: string;
} = {
  name: 'shape_link',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#shape-link_svg__clip0_430_11614)"><path fill-rule="evenodd" clip-rule="evenodd" d="M0.5 1C0.5 0.723858 0.723858 0.5 1 0.5H7C7.27614 0.5 7.5 0.723858 7.5 1V7C7.5 7.27614 7.27614 7.5 7 7.5H1C0.723858 7.5 0.5 7.27614 0.5 7V1ZM1.5 1.5V6.5H6.5V1.5H1.5ZM7.5 9.20711L9.20711 7.5H15C15.2761 7.5 15.5 7.27614 15.5 7V1C15.5 0.723858 15.2761 0.5 15 0.5H9C8.72386 0.5 8.5 0.723858 8.5 1V6.79289L6.79289 8.5H1C0.723858 8.5 0.5 8.72386 0.5 9V15C0.5 15.2761 0.723858 15.5 1 15.5H7C7.27614 15.5 7.5 15.2761 7.5 15V9.20711ZM1.5 14.5V9.5H6.5V14.5H1.5ZM9.5 1.5V6.5H14.5V1.5H9.5ZM9 8.5C8.72386 8.5 8.5 8.72386 8.5 9V15C8.5 15.2761 8.72386 15.5 9 15.5H15C15.2761 15.5 15.5 15.2761 15.5 15V9C15.5 8.72386 15.2761 8.5 15 8.5H9ZM9.5 14.5V9.5H14.5V14.5H9.5Z" fill="currentColor"/></g><defs><clipPath id="shape-link_svg__clip0_430_11614"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`,
};
