/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsTruckDumpSideView: {
  name: 'truck-dump-side-view';
  data: string;
} = {
  name: 'truck-dump-side-view',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M8.115 2a.5.5 0 0 1 .5-.5H10a.5.5 0 0 1 0 1h-.885V9a.5.5 0 0 1-.55.497L.949 8.72A.5.5 0 0 1 .5 8.222V4.333a.5.5 0 0 1 .45-.497l7.165-.732V2Zm0 2.11L1.5 4.784V7.77l6.615.675V4.11ZM10.5 4a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .39.188l2 2.5a.5.5 0 0 1 .11.312V9a.5.5 0 0 1-.5.5h-4a.5.5 0 0 1-.5-.5V4ZM13 9.5a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm-1.5-5v4h3V6.675L12.76 4.5H11.5ZM1.5 11a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0ZM2 9.5A1.5 1.5 0 1 0 3.5 11a1.5 1.5 0 1 0 3 0 1.5 1.5 0 0 0-3 0A1.5 1.5 0 0 0 2 9.5Zm3 1a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1Zm7.5.5a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0Z" fill="currentColor"/></svg>`
};
