/* 🤖 this file was generated by svg-to-ts */
import { prizmIconsAgendaFill } from './prizmIcons-agenda-fill.icon';
import { prizmIconsAirplaneSideView } from './prizmIcons-airplane-side-view.icon';
import { prizmIconsAirplaneTopView } from './prizmIcons-airplane-top-view.icon';
import { prizmIconsAlarmClock } from './prizmIcons-alarm-clock.icon';
import { prizmIconsAlarmPlus } from './prizmIcons-alarm-plus.icon';
import { prizmIconsAlignBottom } from './prizmIcons-align-bottom.icon';
import { prizmIconsAlignCenterH } from './prizmIcons-align-center-h.icon';
import { prizmIconsAlignCenterV } from './prizmIcons-align-center-v.icon';
import { prizmIconsAlignCenter } from './prizmIcons-align-center.icon';
import { prizmIconsAlignJustify } from './prizmIcons-align-justify.icon';
import { prizmIconsAlignLeft } from './prizmIcons-align-left.icon';
import { prizmIconsAlignRight } from './prizmIcons-align-right.icon';
import { prizmIconsAlignTop } from './prizmIcons-align-top.icon';
import { prizmIconsAmbulanceSideView } from './prizmIcons-ambulance-side-view.icon';
import { prizmIconsAndroidPill } from './prizmIcons-android-pill.icon';
import { prizmIconsAndroid } from './prizmIcons-android.icon';
import { prizmIconsAngleLeftRightArrowsDown } from './prizmIcons-angle-left-right-arrows-down.icon';
import { prizmIconsAngleLeftRight } from './prizmIcons-angle-left-right.icon';
import { prizmIconsAngleLeft } from './prizmIcons-angle-left.icon';
import { prizmIconsAngleRight } from './prizmIcons-angle-right.icon';
import { prizmIconsArrangeSendToBack } from './prizmIcons-arrange-send-to-back.icon';
import { prizmIconsArrayFill } from './prizmIcons-array-fill.icon';
import { prizmIconsArrowBoldDown } from './prizmIcons-arrow-bold-down.icon';
import { prizmIconsArrowBoldLeft } from './prizmIcons-arrow-bold-left.icon';
import { prizmIconsArrowBoldRight } from './prizmIcons-arrow-bold-right.icon';
import { prizmIconsArrowBoldUp } from './prizmIcons-arrow-bold-up.icon';
import { prizmIconsArrowDaw } from './prizmIcons-arrow-daw.icon';
import { prizmIconsArrowDownBetweenLines } from './prizmIcons-arrow-down-between-lines.icon';
import { prizmIconsArrowDownFromDoubleLine } from './prizmIcons-arrow-down-from-double-line.icon';
import { prizmIconsArrowDownFromLine } from './prizmIcons-arrow-down-from-line.icon';
import { prizmIconsArrowDownInCircleEmpty } from './prizmIcons-arrow-down-in-circle-empty.icon';
import { prizmIconsArrowDownToBracket } from './prizmIcons-arrow-down-to-bracket.icon';
import { prizmIconsArrowDownToDoubleLine } from './prizmIcons-arrow-down-to-double-line.icon';
import { prizmIconsArrowDownToLine } from './prizmIcons-arrow-down-to-line.icon';
import { prizmIconsArrowDownWideShort } from './prizmIcons-arrow-down-wide-short.icon';
import { prizmIconsArrowDown } from './prizmIcons-arrow-down.icon';
import { prizmIconsArrowLeftBetweenLines } from './prizmIcons-arrow-left-between-lines.icon';
import { prizmIconsArrowLeftDown } from './prizmIcons-arrow-left-down.icon';
import { prizmIconsArrowLeftFromBracket } from './prizmIcons-arrow-left-from-bracket.icon';
import { prizmIconsArrowLeftInCircleEmpty } from './prizmIcons-arrow-left-in-circle-empty.icon';
import { prizmIconsArrowLeftUp } from './prizmIcons-arrow-left-up.icon';
import { prizmIconsArrowLeft } from './prizmIcons-arrow-left.icon';
import { prizmIconsArrowRightBetweenLines } from './prizmIcons-arrow-right-between-lines.icon';
import { prizmIconsArrowRightDown } from './prizmIcons-arrow-right-down.icon';
import { prizmIconsArrowRightFromBracket } from './prizmIcons-arrow-right-from-bracket.icon';
import { prizmIconsArrowRightInCircleEmpty } from './prizmIcons-arrow-right-in-circle-empty.icon';
import { prizmIconsArrowRightUp } from './prizmIcons-arrow-right-up.icon';
import { prizmIconsArrowRight } from './prizmIcons-arrow-right.icon';
import { prizmIconsArrowRotateLeft } from './prizmIcons-arrow-rotate-left.icon';
import { prizmIconsArrowRotateRight } from './prizmIcons-arrow-rotate-right.icon';
import { prizmIconsArrowTurnDownLeft } from './prizmIcons-arrow-turn-down-left.icon';
import { prizmIconsArrowTurnDownRight } from './prizmIcons-arrow-turn-down-right.icon';
import { prizmIconsArrowTurnLeftDown } from './prizmIcons-arrow-turn-left-down.icon';
import { prizmIconsArrowTurnLeftUp } from './prizmIcons-arrow-turn-left-up.icon';
import { prizmIconsArrowTurnRightDown } from './prizmIcons-arrow-turn-right-down.icon';
import { prizmIconsArrowTurnRightUp } from './prizmIcons-arrow-turn-right-up.icon';
import { prizmIconsArrowTurnUpLeft } from './prizmIcons-arrow-turn-up-left.icon';
import { prizmIconsArrowTurnUpRight } from './prizmIcons-arrow-turn-up-right.icon';
import { prizmIconsArrowUpArrowDownH } from './prizmIcons-arrow-up-arrow-down-h.icon';
import { prizmIconsArrowUpArrowDownV } from './prizmIcons-arrow-up-arrow-down-v.icon';
import { prizmIconsArrowUpBetweenLines } from './prizmIcons-arrow-up-between-lines.icon';
import { prizmIconsArrowUpFromBracket } from './prizmIcons-arrow-up-from-bracket.icon';
import { prizmIconsArrowUpFromDoubleLine } from './prizmIcons-arrow-up-from-double-line.icon';
import { prizmIconsArrowUpFromLine } from './prizmIcons-arrow-up-from-line.icon';
import { prizmIconsArrowUpInCircleEmpty } from './prizmIcons-arrow-up-in-circle-empty.icon';
import { prizmIconsArrowUpToDottedLine } from './prizmIcons-arrow-up-to-dotted-line.icon';
import { prizmIconsArrowUpToDoubleLine } from './prizmIcons-arrow-up-to-double-line.icon';
import { prizmIconsArrowUpToLine } from './prizmIcons-arrow-up-to-line.icon';
import { prizmIconsArrowUpWideShort } from './prizmIcons-arrow-up-wide-short.icon';
import { prizmIconsArrowUp } from './prizmIcons-arrow-up.icon';
import { prizmIconsArrowsAllDirections } from './prizmIcons-arrows-all-directions.icon';
import { prizmIconsArrowsCompare } from './prizmIcons-arrows-compare.icon';
import { prizmIconsArrowsCross } from './prizmIcons-arrows-cross.icon';
import { prizmIconsArrowsDirectionToTheLines } from './prizmIcons-arrows-direction-to-the-lines.icon';
import { prizmIconsArrowsInside } from './prizmIcons-arrows-inside.icon';
import { prizmIconsArrowsLeftRightBrackets } from './prizmIcons-arrows-left-right-brackets.icon';
import { prizmIconsArrowsLeftRightToLines } from './prizmIcons-arrows-left-right-to-lines.icon';
import { prizmIconsArrowsMaximize } from './prizmIcons-arrows-maximize.icon';
import { prizmIconsArrowsMinimize } from './prizmIcons-arrows-minimize.icon';
import { prizmIconsArrowsOut } from './prizmIcons-arrows-out.icon';
import { prizmIconsArrowsRepeatH } from './prizmIcons-arrows-repeat-h.icon';
import { prizmIconsArrowsRepeatV } from './prizmIcons-arrows-repeat-v.icon';
import { prizmIconsArrowsRotateH } from './prizmIcons-arrows-rotate-h.icon';
import { prizmIconsArrowsRotateV } from './prizmIcons-arrows-rotate-v.icon';
import { prizmIconsArrowsShuffle } from './prizmIcons-arrows-shuffle.icon';
import { prizmIconsArrowsSwapH } from './prizmIcons-arrows-swap-h.icon';
import { prizmIconsArrowsSwapV } from './prizmIcons-arrows-swap-v.icon';
import { prizmIconsArrowsUpDownToLines } from './prizmIcons-arrows-up-down-to-lines.icon';
import { prizmIconsAtSign } from './prizmIcons-at-sign.icon';
import { prizmIconsAudioSpeakers } from './prizmIcons-audio-speakers.icon';
import { prizmIconsAward } from './prizmIcons-award.icon';
import { prizmIconsBag } from './prizmIcons-bag.icon';
import { prizmIconsBalloon } from './prizmIcons-balloon.icon';
import { prizmIconsBan } from './prizmIcons-ban.icon';
import { prizmIconsBarAxis } from './prizmIcons-bar-axis.icon';
import { prizmIconsBarBasic } from './prizmIcons-bar-basic.icon';
import { prizmIconsBarColumnsAxisX } from './prizmIcons-bar-columns-axis-x.icon';
import { prizmIconsBarColumns } from './prizmIcons-bar-columns.icon';
import { prizmIconsBarHistogram } from './prizmIcons-bar-histogram.icon';
import { prizmIconsBarSquare } from './prizmIcons-bar-square.icon';
import { prizmIconsBarStackedAxis } from './prizmIcons-bar-stacked-axis.icon';
import { prizmIconsBarStacked } from './prizmIcons-bar-stacked.icon';
import { prizmIconsBarcode } from './prizmIcons-barcode.icon';
import { prizmIconsBarsSort } from './prizmIcons-bars-sort.icon';
import { prizmIconsBars } from './prizmIcons-bars.icon';
import { prizmIconsBatteryBolt } from './prizmIcons-battery-bolt.icon';
import { prizmIconsBatteryEmpty } from './prizmIcons-battery-empty.icon';
import { prizmIconsBatteryExclametionMark } from './prizmIcons-battery-exclametion-mark.icon';
import { prizmIconsBatteryFull } from './prizmIcons-battery-full.icon';
import { prizmIconsBatteryHalf } from './prizmIcons-battery-half.icon';
import { prizmIconsBatteryMinus } from './prizmIcons-battery-minus.icon';
import { prizmIconsBatteryPlus } from './prizmIcons-battery-plus.icon';
import { prizmIconsBatteryQuarter } from './prizmIcons-battery-quarter.icon';
import { prizmIconsBatteryThreeQuarters } from './prizmIcons-battery-three-quarters.icon';
import { prizmIconsBdrvAdministration } from './prizmIcons-bdrv-administration.icon';
import { prizmIconsBellFill } from './prizmIcons-bell-fill.icon';
import { prizmIconsBellPlus } from './prizmIcons-bell-plus.icon';
import { prizmIconsBellRingFill } from './prizmIcons-bell-ring-fill.icon';
import { prizmIconsBellRing } from './prizmIcons-bell-ring.icon';
import { prizmIconsBellSlash } from './prizmIcons-bell-slash.icon';
import { prizmIconsBell } from './prizmIcons-bell.icon';
import { prizmIconsBezierCurve } from './prizmIcons-bezier-curve.icon';
import { prizmIconsBitcoin } from './prizmIcons-bitcoin.icon';
import { prizmIconsBluetooth } from './prizmIcons-bluetooth.icon';
import { prizmIconsBoilerHotWaterGasAndOil } from './prizmIcons-boiler-hot-water-gas-and-oil.icon';
import { prizmIconsBoiler } from './prizmIcons-boiler.icon';
import { prizmIconsBold } from './prizmIcons-bold.icon';
import { prizmIconsBookStack } from './prizmIcons-book_stack.icon';
import { prizmIconsBookCheck } from './prizmIcons-book-check.icon';
import { prizmIconsBookClosed } from './prizmIcons-book-closed.icon';
import { prizmIconsBookOpenPlus } from './prizmIcons-book-open-plus.icon';
import { prizmIconsBookOpenReArrowLeft } from './prizmIcons-book-open-re-arrow-left.icon';
import { prizmIconsBookOpenReArrowRight } from './prizmIcons-book-open-re-arrow-right.icon';
import { prizmIconsBookOpenText } from './prizmIcons-book-open-text.icon';
import { prizmIconsBookOpenWithPage } from './prizmIcons-book-open-with-page.icon';
import { prizmIconsBookOpen } from './prizmIcons-book-open.icon';
import { prizmIconsBookmarkCheckFill } from './prizmIcons-bookmark-check-fill.icon';
import { prizmIconsBookmarkCheck } from './prizmIcons-bookmark-check.icon';
import { prizmIconsBookmarkCrossFill } from './prizmIcons-bookmark-cross-fill.icon';
import { prizmIconsBookmarkCross } from './prizmIcons-bookmark-cross.icon';
import { prizmIconsBookmarkFill } from './prizmIcons-bookmark-fill.icon';
import { prizmIconsBookmarkMusicFill } from './prizmIcons-bookmark-music-fill.icon';
import { prizmIconsBookmarkMusic } from './prizmIcons-bookmark-music.icon';
import { prizmIconsBookmarkPlusFill } from './prizmIcons-bookmark-plus-fill.icon';
import { prizmIconsBookmarkPlus } from './prizmIcons-bookmark-plus.icon';
import { prizmIconsBookmark } from './prizmIcons-bookmark.icon';
import { prizmIconsBorderAll } from './prizmIcons-border-all.icon';
import { prizmIconsBorderBottom } from './prizmIcons-border-bottom.icon';
import { prizmIconsBorderCenterH } from './prizmIcons-border-center-h.icon';
import { prizmIconsBorderCenterV } from './prizmIcons-border-center-v.icon';
import { prizmIconsBorderInner } from './prizmIcons-border-inner.icon';
import { prizmIconsBorderLeft } from './prizmIcons-border-left.icon';
import { prizmIconsBorderNone } from './prizmIcons-border-none.icon';
import { prizmIconsBorderOuter } from './prizmIcons-border-outer.icon';
import { prizmIconsBorderRight } from './prizmIcons-border-right.icon';
import { prizmIconsBorderTopLeft } from './prizmIcons-border-top-left.icon';
import { prizmIconsBorderTop } from './prizmIcons-border-top.icon';
import { prizmIconsBoxOpenArrowDown } from './prizmIcons-box-open-arrow-down.icon';
import { prizmIconsBox } from './prizmIcons-box.icon';
import { prizmIconsBracketsCurly } from './prizmIcons-brackets-curly.icon';
import { prizmIconsBracketsSquare } from './prizmIcons-brackets-square.icon';
import { prizmIconsBroom } from './prizmIcons-broom.icon';
import { prizmIconsBrowser } from './prizmIcons-browser.icon';
import { prizmIconsBrush } from './prizmIcons-brush.icon';
import { prizmIconsBubbleMessageAdd } from './prizmIcons-bubble-message-add.icon';
import { prizmIconsBubbleMessageAttention } from './prizmIcons-bubble-message-attention.icon';
import { prizmIconsBubbleMessageCircle } from './prizmIcons-bubble-message-circle.icon';
import { prizmIconsBubbleMessageEmpty } from './prizmIcons-bubble-message-empty.icon';
import { prizmIconsBubbleMessageOff } from './prizmIcons-bubble-message-off.icon';
import { prizmIconsBubbleMessageQuestion } from './prizmIcons-bubble-message-question.icon';
import { prizmIconsBubbleMessageText } from './prizmIcons-bubble-message-text.icon';
import { prizmIconsBubbleMessage } from './prizmIcons-bubble-message.icon';
import { prizmIconsBurn } from './prizmIcons-burn.icon';
import { prizmIconsCalculatorArrowRotateLeft } from './prizmIcons-calculator-arrow-rotate-left.icon';
import { prizmIconsCalculatorFunction } from './prizmIcons-calculator-function.icon';
import { prizmIconsCalculator } from './prizmIcons-calculator.icon';
import { prizmIconsCalendarBlank } from './prizmIcons-calendar-blank.icon';
import { prizmIconsCalendarCheck } from './prizmIcons-calendar-check.icon';
import { prizmIconsCalendarClock } from './prizmIcons-calendar-clock.icon';
import { prizmIconsCalendarDeleted } from './prizmIcons-calendar-deleted.icon';
import { prizmIconsCalendarEvent } from './prizmIcons-calendar-event.icon';
import { prizmIconsCalendarPlus } from './prizmIcons-calendar-plus.icon';
import { prizmIconsCalendarQuestion } from './prizmIcons-calendar-question.icon';
import { prizmIconsCalendarRange } from './prizmIcons-calendar-range.icon';
import { prizmIconsCalendarToday } from './prizmIcons-calendar-today.icon';
import { prizmIconsCalendar } from './prizmIcons-calendar.icon';
import { prizmIconsCalibrationCharacteristicsZql } from './prizmIcons-calibration-characteristics-zql.icon';
import { prizmIconsCameraFront } from './prizmIcons-camera-front.icon';
import { prizmIconsCameraMovieCross } from './prizmIcons-camera-movie-cross.icon';
import { prizmIconsCameraMovie } from './prizmIcons-camera-movie.icon';
import { prizmIconsCamera } from './prizmIcons-camera.icon';
import { prizmIconsCarJeepSideView } from './prizmIcons-car-jeep-side-view.icon';
import { prizmIconsCarLightSideView } from './prizmIcons-car-light-side-view.icon';
import { prizmIconsCarbon } from './prizmIcons-carbon.icon';
import { prizmIconsCarouselFill } from './prizmIcons-carousel-fill.icon';
import { prizmIconsCartFlatbedContainer } from './prizmIcons-cart-flatbed-container.icon';
import { prizmIconsCartPlus } from './prizmIcons-cart-plus.icon';
import { prizmIconsCart } from './prizmIcons-cart.icon';
import { prizmIconsCellphoneWireless } from './prizmIcons-cellphone-wireless.icon';
import { prizmIconsCellphone } from './prizmIcons-cellphone.icon';
import { prizmIconsChartsIqcZql } from './prizmIcons-charts-iqc-zql.icon';
import { prizmIconsCheckDouble } from './prizmIcons-check-double.icon';
import { prizmIconsCheckerboard } from './prizmIcons-checkerboard.icon';
import { prizmIconsChek } from './prizmIcons-chek.icon';
import { prizmIconsChevronDownToDoubleLine } from './prizmIcons-chevron-down-to-double-line.icon';
import { prizmIconsChevronDown } from './prizmIcons-chevron-down.icon';
import { prizmIconsChevronLeft } from './prizmIcons-chevron-left.icon';
import { prizmIconsChevronMiniLeft } from './prizmIcons-chevron-mini-left.icon';
import { prizmIconsChevronMiniRight } from './prizmIcons-chevron-mini-right.icon';
import { prizmIconsChevronRightAboveDoubleLine } from './prizmIcons-chevron-right-above-double-line.icon';
import { prizmIconsChevronRight } from './prizmIcons-chevron-right.icon';
import { prizmIconsChevronUp } from './prizmIcons-chevron-up.icon';
import { prizmIconsChevronsDoubleDown } from './prizmIcons-chevrons-double-down.icon';
import { prizmIconsChevronsDoubleLeft } from './prizmIcons-chevrons-double-left.icon';
import { prizmIconsChevronsDoubleMiniLeft } from './prizmIcons-chevrons-double-mini-left.icon';
import { prizmIconsChevronsDoubleMiniRight } from './prizmIcons-chevrons-double-mini-right.icon';
import { prizmIconsChevronsDoubleRight } from './prizmIcons-chevrons-double-right.icon';
import { prizmIconsChevronsDoubleUp } from './prizmIcons-chevrons-double-up.icon';
import { prizmIconsChevronsInsideHorizontally } from './prizmIcons-chevrons-inside_horizontally.icon';
import { prizmIconsChevronsInsideVertically } from './prizmIcons-chevrons-inside_vertically.icon';
import { prizmIconsChevronsOutsideHorizontally } from './prizmIcons-chevrons-outside_horizontally.icon';
import { prizmIconsChevronsOutsideVertically } from './prizmIcons-chevrons-outside_vertically.icon';
import { prizmIconsCircleChekEmpty } from './prizmIcons-circle-chek-empty.icon';
import { prizmIconsCircleChekFill } from './prizmIcons-circle-chek-fill.icon';
import { prizmIconsCircleExclamationEmpty } from './prizmIcons-circle-exclamation-empty.icon';
import { prizmIconsCircleExclamationFill } from './prizmIcons-circle-exclamation-fill.icon';
import { prizmIconsCircleInHexagon } from './prizmIcons-circle-in-hexagon.icon';
import { prizmIconsCircleInfoEmpty } from './prizmIcons-circle-info-empty.icon';
import { prizmIconsCircleInfoFill } from './prizmIcons-circle-info-fill.icon';
import { prizmIconsCircleMusic } from './prizmIcons-circle-music.icon';
import { prizmIconsCirclePlusFill } from './prizmIcons-circle-plus-fill.icon';
import { prizmIconsCirclePlus } from './prizmIcons-circle-plus.icon';
import { prizmIconsCircleQuestionEmpty } from './prizmIcons-circle-question-empty.icon';
import { prizmIconsCircleQuestionFill } from './prizmIcons-circle-question-fill.icon';
import { prizmIconsCircleSquareFill } from './prizmIcons-circle-square-fill.icon';
import { prizmIconsCircleSquareInSquare } from './prizmIcons-circle-square-in-square.icon';
import { prizmIconsCircleSquare } from './prizmIcons-circle-square.icon';
import { prizmIconsCircleXmarkFill } from './prizmIcons-circle-xmark-fill.icon';
import { prizmIconsCircleXmark } from './prizmIcons-circle-xmark.icon';
import { prizmIconsCirclesLineLeftUpCircleRightDownFill } from './prizmIcons-circles-line-left-up-circle-right-down-fill.icon';
import { prizmIconsCirclesLineLeftUpCircleRightDown } from './prizmIcons-circles-line-left-up-circle-right-down.icon';
import { prizmIconsClapperboardCross } from './prizmIcons-clapperboard-cross.icon';
import { prizmIconsClapperboardOpen } from './prizmIcons-clapperboard-open.icon';
import { prizmIconsClockAdd } from './prizmIcons-clock-add.icon';
import { prizmIconsClockArrowDown } from './prizmIcons-clock-arrow-down.icon';
import { prizmIconsClockArrowRight } from './prizmIcons-clock-arrow-right.icon';
import { prizmIconsClockArrowUp } from './prizmIcons-clock-arrow-up.icon';
import { prizmIconsClockDeleted } from './prizmIcons-clock-deleted.icon';
import { prizmIconsClockExclamation } from './prizmIcons-clock-exclamation.icon';
import { prizmIconsClockLineEnd } from './prizmIcons-clock-line-end.icon';
import { prizmIconsClockRotateLeft } from './prizmIcons-clock-rotate-left.icon';
import { prizmIconsClockRotateRight } from './prizmIcons-clock-rotate-right.icon';
import { prizmIconsClock } from './prizmIcons-clock.icon';
import { prizmIconsCloudArrowDown } from './prizmIcons-cloud-arrow_down.icon';
import { prizmIconsCloudArrowUpInside } from './prizmIcons-cloud-arrow_up_inside.icon';
import { prizmIconsCloudArrowUp } from './prizmIcons-cloud-arrow_up.icon';
import { prizmIconsCloudCheck } from './prizmIcons-cloud-check.icon';
import { prizmIconsCloud } from './prizmIcons-cloud.icon';
import { prizmIconsCodeDownload } from './prizmIcons-code-download.icon';
import { prizmIconsCodeSimple } from './prizmIcons-code-simple.icon';
import { prizmIconsCode } from './prizmIcons-code.icon';
import { prizmIconsCollageFill } from './prizmIcons-collage-fill.icon';
import { prizmIconsCollection } from './prizmIcons-collection.icon';
import { prizmIconsCollector } from './prizmIcons-collector.icon';
import { prizmIconsColumnFill } from './prizmIcons-column-fill.icon';
import { prizmIconsColumn } from './prizmIcons-column.icon';
import { prizmIconsCompass } from './prizmIcons-compass.icon';
import { prizmIconsComponent } from './prizmIcons-component.icon';
import { prizmIconsConcreteMixerSideView } from './prizmIcons-concrete-mixer-side-view.icon';
import { prizmIconsContainerV1 } from './prizmIcons-container-v1.icon';
import { prizmIconsContainerV2 } from './prizmIcons-container-v2.icon';
import { prizmIconsContainers } from './prizmIcons-containers.icon';
import { prizmIconsControlChartsZql } from './prizmIcons-control-charts-zql.icon';
import { prizmIconsCopyColumn } from './prizmIcons-copy-column.icon';
import { prizmIconsCopyRow } from './prizmIcons-copy-row.icon';
import { prizmIconsCopy } from './prizmIcons-copy.icon';
import { prizmIconsCrane } from './prizmIcons-crane.icon';
import { prizmIconsCreditCardPlus } from './prizmIcons-credit-card-plus.icon';
import { prizmIconsCreditCardSlash } from './prizmIcons-credit-card-slash.icon';
import { prizmIconsCreditCard } from './prizmIcons-credit-card.icon';
import { prizmIconsCrop } from './prizmIcons-crop.icon';
import { prizmIconsCrosshairsDot } from './prizmIcons-crosshairs-dot.icon';
import { prizmIconsCrosshairsSimple } from './prizmIcons-crosshairs-simple.icon';
import { prizmIconsCubeEmpty } from './prizmIcons-cube-empty.icon';
import { prizmIconsCubeFill } from './prizmIcons-cube-fill.icon';
import { prizmIconsCubes } from './prizmIcons-cubes.icon';
import { prizmIconsDashboardFill } from './prizmIcons-dashboard-fill.icon';
import { prizmIconsDashboardVariantFill } from './prizmIcons-dashboard-variant-fill.icon';
import { prizmIconsDatabaseChek } from './prizmIcons-database-chek.icon';
import { prizmIconsDatabaseJson } from './prizmIcons-database-json.icon';
import { prizmIconsDatabaseMagnifyingGlass } from './prizmIcons-database-magnifying-glass.icon';
import { prizmIconsDatabaseMinus } from './prizmIcons-database-minus.icon';
import { prizmIconsDatabasePlus } from './prizmIcons-database-plus.icon';
import { prizmIconsDatabaseSql } from './prizmIcons-database-sql.icon';
import { prizmIconsDatabaseXmark } from './prizmIcons-database-xmark.icon';
import { prizmIconsDatabase } from './prizmIcons-database.icon';
import { prizmIconsDayFill } from './prizmIcons-day-fill.icon';
import { prizmIconsDecagramChekEmpty } from './prizmIcons-decagram-chek-empty.icon';
import { prizmIconsDecagramChekFill } from './prizmIcons-decagram-chek-fill.icon';
import { prizmIconsDecagramExclamationEmpty } from './prizmIcons-decagram-exclamation-empty.icon';
import { prizmIconsDecagramExclamationFill } from './prizmIcons-decagram-exclamation-fill.icon';
import { prizmIconsDefaultIco } from './prizmIcons-default-ico.icon';
import { prizmIconsDeleteContent } from './prizmIcons-delete-content.icon';
import { prizmIconsDesktopTower } from './prizmIcons-desktop-tower.icon';
import { prizmIconsDiscreteSet } from './prizmIcons-discrete-set.icon';
import { prizmIconsDollarSlash } from './prizmIcons-dollar-slash.icon';
import { prizmIconsDollar } from './prizmIcons-dollar.icon';
import { prizmIconsDoughnut } from './prizmIcons-doughnut.icon';
import { prizmIconsDropletSlash } from './prizmIcons-droplet-slash.icon';
import { prizmIconsDroplet } from './prizmIcons-droplet.icon';
import { prizmIconsEarlyVersion } from './prizmIcons-early-version.icon';
import { prizmIconsEarth } from './prizmIcons-earth.icon';
import { prizmIconsEditorDown } from './prizmIcons-editor-down.icon';
import { prizmIconsEditorRight } from './prizmIcons-editor-right.icon';
import { prizmIconsElectrics } from './prizmIcons-electrics.icon';
import { prizmIconsEllipsisGrid } from './prizmIcons-ellipsis-grid.icon';
import { prizmIconsEllipsisH } from './prizmIcons-ellipsis-h.icon';
import { prizmIconsEllipsisV } from './prizmIcons-ellipsis-v.icon';
import { prizmIconsEnergyCheck } from './prizmIcons-energy-check.icon';
import { prizmIconsEnergySlash } from './prizmIcons-energy-slash.icon';
import { prizmIconsEnergy } from './prizmIcons-energy.icon';
import { prizmIconsEquipmentZql } from './prizmIcons-equipment-zql.icon';
import { prizmIconsEraser } from './prizmIcons-eraser.icon';
import { prizmIconsEthernet } from './prizmIcons-ethernet.icon';
import { prizmIconsExchanger } from './prizmIcons-exchanger.icon';
import { prizmIconsExclamation } from './prizmIcons-exclamation.icon';
import { prizmIconsEyeClosed } from './prizmIcons-eye-closed.icon';
import { prizmIconsEyeSlash } from './prizmIcons-eye-slash.icon';
import { prizmIconsEye } from './prizmIcons-eye.icon';
import { prizmIconsFaceFrown } from './prizmIcons-face-frown.icon';
import { prizmIconsFaceSmile } from './prizmIcons-face-smile.icon';
import { prizmIconsFactoryPipe } from './prizmIcons-factory-pipe.icon';
import { prizmIconsFactoryPipes } from './prizmIcons-factory-pipes.icon';
import { prizmIconsFactory } from './prizmIcons-factory.icon';
import { prizmIconsFan } from './prizmIcons-fan.icon';
import { prizmIconsFileArrowDownLeft } from './prizmIcons-file-arrow_down_left.icon';
import { prizmIconsFileArrowDown } from './prizmIcons-file-arrow_down.icon';
import { prizmIconsFileArrowUp } from './prizmIcons-file-arrow_up.icon';
import { prizmIconsFileArrow } from './prizmIcons-file-arrow.icon';
import { prizmIconsFileArrowsUpRight } from './prizmIcons-file-arrows_up_right.icon';
import { prizmIconsFileCamera } from './prizmIcons-file-camera.icon';
import { prizmIconsFileCrossOut } from './prizmIcons-file-cross_out.icon';
import { prizmIconsFileCross } from './prizmIcons-file-cross.icon';
import { prizmIconsFileDoc } from './prizmIcons-file-doc.icon';
import { prizmIconsFileDocx } from './prizmIcons-file-docx.icon';
import { prizmIconsFileDot } from './prizmIcons-file-dot.icon';
import { prizmIconsFileEmpty } from './prizmIcons-file-empty.icon';
import { prizmIconsFileExclamation } from './prizmIcons-file-exclamation.icon';
import { prizmIconsFileEye } from './prizmIcons-file-eye.icon';
import { prizmIconsFileFilled } from './prizmIcons-file-filled.icon';
import { prizmIconsFileImage } from './prizmIcons-file-image.icon';
import { prizmIconsFileMagnifyingGlass } from './prizmIcons-file-magnifying_glass.icon';
import { prizmIconsFileMinus } from './prizmIcons-file-minus.icon';
import { prizmIconsFileMusic } from './prizmIcons-file-music.icon';
import { prizmIconsFilePdf } from './prizmIcons-file-pdf.icon';
import { prizmIconsFilePen } from './prizmIcons-file-pen.icon';
import { prizmIconsFilePlay } from './prizmIcons-file-play.icon';
import { prizmIconsFilePlus } from './prizmIcons-file-plus.icon';
import { prizmIconsFilePpt } from './prizmIcons-file-ppt.icon';
import { prizmIconsFilePptx } from './prizmIcons-file-pptx.icon';
import { prizmIconsFileTxt } from './prizmIcons-file-txt.icon';
import { prizmIconsFileUpRight } from './prizmIcons-file-up_right.icon';
import { prizmIconsFileXls } from './prizmIcons-file-xls.icon';
import { prizmIconsFileXlsx } from './prizmIcons-file-xlsx.icon';
import { prizmIconsFilesMode } from './prizmIcons-files-mode.icon';
import { prizmIconsFill } from './prizmIcons-fill.icon';
import { prizmIconsFilmCross } from './prizmIcons-film-cross.icon';
import { prizmIconsFilm } from './prizmIcons-film.icon';
import { prizmIconsFilterGear } from './prizmIcons-filter-gear.icon';
import { prizmIconsFilterOntology } from './prizmIcons-filter-ontology.icon';
import { prizmIconsFilter } from './prizmIcons-filter.icon';
import { prizmIconsFinanceScanner } from './prizmIcons-finance-scanner.icon';
import { prizmIconsFire } from './prizmIcons-fire.icon';
import { prizmIconsFlagFillRed } from './prizmIcons-flag-fill-red.icon';
import { prizmIconsFlagFill } from './prizmIcons-flag-fill.icon';
import { prizmIconsFlag } from './prizmIcons-flag.icon';
import { prizmIconsFlaskRoundPotion } from './prizmIcons-flask-round-potion.icon';
import { prizmIconsFlask } from './prizmIcons-flask.icon';
import { prizmIconsFloppyCrossOut } from './prizmIcons-floppy-cross_out.icon';
import { prizmIconsFloppyCross } from './prizmIcons-floppy-cross.icon';
import { prizmIconsFloppyPen } from './prizmIcons-floppy-pen.icon';
import { prizmIconsFloppyStar } from './prizmIcons-floppy-star.icon';
import { prizmIconsFloppy } from './prizmIcons-floppy.icon';
import { prizmIconsFolderOpen } from './prizmIcons-folder_open.icon';
import { prizmIconsFolderUnderlineMinus } from './prizmIcons-folder_underline-minus.icon';
import { prizmIconsFolderUnderlinePlus } from './prizmIcons-folder_underline-plus.icon';
import { prizmIconsFolderUnderline } from './prizmIcons-folder_underline.icon';
import { prizmIconsFolderArrowDownLeft } from './prizmIcons-folder-arrow_down_left.icon';
import { prizmIconsFolderArrowDown } from './prizmIcons-folder-arrow_down.icon';
import { prizmIconsFolderArrowUpRight } from './prizmIcons-folder-arrow_up_right.icon';
import { prizmIconsFolderCross } from './prizmIcons-folder-cross.icon';
import { prizmIconsFolderDot } from './prizmIcons-folder-dot.icon';
import { prizmIconsFolderMinus } from './prizmIcons-folder-minus.icon';
import { prizmIconsFolderPlus } from './prizmIcons-folder-plus.icon';
import { prizmIconsFolder } from './prizmIcons-folder.icon';
import { prizmIconsForvardStep } from './prizmIcons-forvard-step.icon';
import { prizmIconsForward } from './prizmIcons-forward.icon';
import { prizmIconsFuelOilTank } from './prizmIcons-fuel-oil-tank.icon';
import { prizmIconsFunction } from './prizmIcons-function.icon';
import { prizmIconsGantt } from './prizmIcons-gantt.icon';
import { prizmIconsGasMonitoring } from './prizmIcons-gas-monitoring.icon';
import { prizmIconsGasPump } from './prizmIcons-gas-pump.icon';
import { prizmIconsGas } from './prizmIcons-gas.icon';
import { prizmIconsGauge } from './prizmIcons-gauge.icon';
import { prizmIconsGear5Edge } from './prizmIcons-gear-5-edge.icon';
import { prizmIconsGear8Edge } from './prizmIcons-gear-8-edge.icon';
import { prizmIconsGearCooling } from './prizmIcons-gear-cooling.icon';
import { prizmIconsGenerator } from './prizmIcons-generator.icon';
import { prizmIconsGift } from './prizmIcons-gift.icon';
import { prizmIconsGitLab } from './prizmIcons-git-lab.icon';
import { prizmIconsGlobe } from './prizmIcons-globe.icon';
import { prizmIconsGridFill } from './prizmIcons-grid-fill.icon';
import { prizmIconsGrid } from './prizmIcons-grid.icon';
import { prizmIconsGripDotsVertical } from './prizmIcons-grip-dots-vertical.icon';
import { prizmIconsHardDriveOutline } from './prizmIcons-hard-drive-outline.icon';
import { prizmIconsHashDash } from './prizmIcons-hash-dash.icon';
import { prizmIconsHash } from './prizmIcons-hash.icon';
import { prizmIconsHashtag } from './prizmIcons-hashtag.icon';
import { prizmIconsHeadlineFill } from './prizmIcons-headline-fill.icon';
import { prizmIconsHeadphones } from './prizmIcons-headphones.icon';
import { prizmIconsHeartEmpty } from './prizmIcons-heart-empty.icon';
import { prizmIconsHeartFill } from './prizmIcons-heart-fill.icon';
import { prizmIconsHelicopterSideView } from './prizmIcons-helicopter-side-view.icon';
import { prizmIconsHexagonExclamationEmpty } from './prizmIcons-hexagon-exclamation-empty.icon';
import { prizmIconsHexagonExclamationFill } from './prizmIcons-hexagon-exclamation-fill.icon';
import { prizmIconsHexagonFill } from './prizmIcons-hexagon-fill.icon';
import { prizmIconsHexagon } from './prizmIcons-hexagon.icon';
import { prizmIconsHexagonsAxis } from './prizmIcons-hexagons-axis.icon';
import { prizmIconsHexagons } from './prizmIcons-hexagons.icon';
import { prizmIconsHistogramAxis } from './prizmIcons-histogram-axis.icon';
import { prizmIconsHouseMini } from './prizmIcons-house-mini.icon';
import { prizmIconsHouse } from './prizmIcons-house.icon';
import { prizmIconsImage } from './prizmIcons-image.icon';
import { prizmIconsImportersZql } from './prizmIcons-importers-zql.icon';
import { prizmIconsIndentArrowLeft } from './prizmIcons-indent-arrow-left.icon';
import { prizmIconsIndentArrowRight } from './prizmIcons-indent-arrow-right.icon';
import { prizmIconsInfinity } from './prizmIcons-infinity.icon';
import { prizmIconsInfo } from './prizmIcons-info.icon';
import { prizmIconsInputDevice } from './prizmIcons-input-device.icon';
import { prizmIconsInstagram } from './prizmIcons-instagram.icon';
import { prizmIconsItalic } from './prizmIcons-italic.icon';
import { prizmIconsKey } from './prizmIcons-key.icon';
import { prizmIconsKeyboardClose } from './prizmIcons-keyboard-close.icon';
import { prizmIconsKeyboard } from './prizmIcons-keyboard.icon';
import { prizmIconsLabelCross } from './prizmIcons-label-cross.icon';
import { prizmIconsLabelExclamationMark } from './prizmIcons-label-exclamation-mark.icon';
import { prizmIconsLabelFill } from './prizmIcons-label-fill.icon';
import { prizmIconsLabelMagnifyingGlass } from './prizmIcons-label-magnifying-glass.icon';
import { prizmIconsLabelPlus } from './prizmIcons-label-plus.icon';
import { prizmIconsLabelQuestion } from './prizmIcons-label-question.icon';
import { prizmIconsLabelText } from './prizmIcons-label-text.icon';
import { prizmIconsLabel } from './prizmIcons-label.icon';
import { prizmIconsLanConnect } from './prizmIcons-lan-connect.icon';
import { prizmIconsLanDisconnect } from './prizmIcons-lan-disconnect.icon';
import { prizmIconsLanPending } from './prizmIcons-lan-pending.icon';
import { prizmIconsLaptopPhoneSlash } from './prizmIcons-laptop-phone-slash.icon';
import { prizmIconsLaptopPhone } from './prizmIcons-laptop-phone.icon';
import { prizmIconsLaptopSlash } from './prizmIcons-laptop-slash.icon';
import { prizmIconsLaptop } from './prizmIcons-laptop.icon';
import { prizmIconsLayerGroupSlash } from './prizmIcons-layer-group-slash.icon';
import { prizmIconsLayerGroup } from './prizmIcons-layer-group.icon';
import { prizmIconsLayerNetwork } from './prizmIcons-layer-network.icon';
import { prizmIconsLetterDay } from './prizmIcons-letter-day.icon';
import { prizmIconsLetterHour } from './prizmIcons-letter-hour.icon';
import { prizmIconsLetterMinute } from './prizmIcons-letter-minute.icon';
import { prizmIconsLetterMonth } from './prizmIcons-letter-month.icon';
import { prizmIconsLetterSecond } from './prizmIcons-letter-second.icon';
import { prizmIconsLetterTime } from './prizmIcons-letter-time.icon';
import { prizmIconsLetterYear } from './prizmIcons-letter-year.icon';
import { prizmIconsLibraryPlus } from './prizmIcons-library-plus.icon';
import { prizmIconsLightbulb } from './prizmIcons-lightbulb.icon';
import { prizmIconsLineAxisArrowDown } from './prizmIcons-line-axis-arrow-down.icon';
import { prizmIconsLineAxisX } from './prizmIcons-line-axis-x.icon';
import { prizmIconsLineAxis } from './prizmIcons-line-axis.icon';
import { prizmIconsLineDown } from './prizmIcons-line-down.icon';
import { prizmIconsLineHeight } from './prizmIcons-line-height.icon';
import { prizmIconsLineMultipleYAxisX } from './prizmIcons-line-multiple-y-axis-x.icon';
import { prizmIconsLineMultipleYAxis } from './prizmIcons-line-multiple-y-axis.icon';
import { prizmIconsLineUp } from './prizmIcons-line-up.icon';
import { prizmIconsLine } from './prizmIcons-line.icon';
import { prizmIconsLinkBreak } from './prizmIcons-link-break.icon';
import { prizmIconsLinkMinus } from './prizmIcons-link-minus.icon';
import { prizmIconsLinkPlus } from './prizmIcons-link-plus.icon';
import { prizmIconsLinkSimpleH } from './prizmIcons-link-simple-h.icon';
import { prizmIconsLinkSimple } from './prizmIcons-link-simple.icon';
import { prizmIconsListSquare } from './prizmIcons-list_square.icon';
import { prizmIconsListFill } from './prizmIcons-list-fill.icon';
import { prizmIconsListOl } from './prizmIcons-list-ol.icon';
import { prizmIconsListTreeArchive } from './prizmIcons-list-tree-archive.icon';
import { prizmIconsListTree } from './prizmIcons-list-tree.icon';
import { prizmIconsListUl } from './prizmIcons-list-ul.icon';
import { prizmIconsList } from './prizmIcons-list.icon';
import { prizmIconsLngStorage } from './prizmIcons-lng-storage.icon';
import { prizmIconsLoader } from './prizmIcons-loader.icon';
import { prizmIconsLocationArrow } from './prizmIcons-location-arrow.icon';
import { prizmIconsLocationDirectly } from './prizmIcons-location-directly.icon';
import { prizmIconsLocationDot } from './prizmIcons-location-dot.icon';
import { prizmIconsLocationMinus } from './prizmIcons-location-minus.icon';
import { prizmIconsLocationPlus } from './prizmIcons-location-plus.icon';
import { prizmIconsLocationSlash } from './prizmIcons-location-slash.icon';
import { prizmIconsLocationUser } from './prizmIcons-location-user.icon';
import { prizmIconsLock } from './prizmIcons-lock.icon';
import { prizmIconsLogoGreyZ } from './prizmIcons-logo-grey-z.icon';
import { prizmIconsMagicWand } from './prizmIcons-magic-wand.icon';
import { prizmIconsMagnifyingGlassExclamation } from './prizmIcons-magnifying-glass-exclamation.icon';
import { prizmIconsMagnifyingGlassMinus } from './prizmIcons-magnifying-glass-minus.icon';
import { prizmIconsMagnifyingGlassOntology } from './prizmIcons-magnifying-glass-ontology.icon';
import { prizmIconsMagnifyingGlassPlus } from './prizmIcons-magnifying-glass-plus.icon';
import { prizmIconsMagnifyingGlassTagsWords } from './prizmIcons-magnifying-glass-tags-words.icon';
import { prizmIconsMagnifyingGlassTopFromBracket } from './prizmIcons-magnifying-glass-top-from-bracket.icon';
import { prizmIconsMagnifyingGlassTriangleDown } from './prizmIcons-magnifying-glass-triangle-down.icon';
import { prizmIconsMagnifyingGlassXmark } from './prizmIcons-magnifying-glass-xmark.icon';
import { prizmIconsMagnifyingGlass } from './prizmIcons-magnifying-glass.icon';
import { prizmIconsMailOpen } from './prizmIcons-mail-open.icon';
import { prizmIconsMail } from './prizmIcons-mail.icon';
import { prizmIconsMailbox } from './prizmIcons-mailbox.icon';
import { prizmIconsMapBase } from './prizmIcons-map-base.icon';
import { prizmIconsMapMarkerDateV1 } from './prizmIcons-map-marker-date-v1.icon';
import { prizmIconsMapMarkerDateV2 } from './prizmIcons-map-marker-date-v2.icon';
import { prizmIconsMapPin } from './prizmIcons-map-pin.icon';
import { prizmIconsMap } from './prizmIcons-map.icon';
import { prizmIconsMedical } from './prizmIcons-medical.icon';
import { prizmIconsMerge } from './prizmIcons-merge.icon';
import { prizmIconsMessagingTelegramSend } from './prizmIcons-messaging-telegram-send.icon';
import { prizmIconsMessagingTelegram } from './prizmIcons-messaging-telegram.icon';
import { prizmIconsMicrophoneSlash } from './prizmIcons-microphone-slash.icon';
import { prizmIconsMicrophone } from './prizmIcons-microphone.icon';
import { prizmIconsMinibusSideView } from './prizmIcons-minibus-side-view.icon';
import { prizmIconsMinusCircleFill } from './prizmIcons-minus-circle-fill.icon';
import { prizmIconsMinusCircle } from './prizmIcons-minus-circle.icon';
import { prizmIconsMinus } from './prizmIcons-minus.icon';
import { prizmIconsModuleFill } from './prizmIcons-module-fill.icon';
import { prizmIconsMonitor } from './prizmIcons-monitor.icon';
import { prizmIconsMoon } from './prizmIcons-moon.icon';
import { prizmIconsMusicSlash } from './prizmIcons-music-slash.icon';
import { prizmIconsMusic } from './prizmIcons-music.icon';
import { prizmIconsNetworkExternalLink } from './prizmIcons-network-external-link.icon';
import { prizmIconsNetworkV1 } from './prizmIcons-network-v1.icon';
import { prizmIconsNetworkV2 } from './prizmIcons-network-v2.icon';
import { prizmIconsNetworkV3 } from './prizmIcons-network-v3.icon';
import { prizmIconsNetworkWired } from './prizmIcons-network-wired.icon';
import { prizmIconsNiFiLogo } from './prizmIcons-ni-fi-logo.icon';
import { prizmIconsNormdocsZql } from './prizmIcons-normdocs-zql.icon';
import { prizmIconsNpm } from './prizmIcons-npm.icon';
import { prizmIconsObjectDownSubtract } from './prizmIcons-object-down-subtract.icon';
import { prizmIconsObjectExclude } from './prizmIcons-object-exclude.icon';
import { prizmIconsObjectIntersect } from './prizmIcons-object-intersect.icon';
import { prizmIconsObjectSelection } from './prizmIcons-object-selection.icon';
import { prizmIconsObjectUnion } from './prizmIcons-object-union.icon';
import { prizmIconsObjectUpSubtract } from './prizmIcons-object-up-subtract.icon';
import { prizmIconsObject } from './prizmIcons-object.icon';
import { prizmIconsOilBarrel } from './prizmIcons-oil-barrel.icon';
import { prizmIconsOilCanister } from './prizmIcons-oil-canister.icon';
import { prizmIconsOilDropletArrowsAll } from './prizmIcons-oil-droplet-arrows-all.icon';
import { prizmIconsOilDropletArrowsRepeatH } from './prizmIcons-oil-droplet-arrows-repeat-h.icon';
import { prizmIconsOilDropletChek } from './prizmIcons-oil-droplet-chek.icon';
import { prizmIconsOilDroplet } from './prizmIcons-oil-droplet.icon';
import { prizmIconsOilField } from './prizmIcons-oil-field.icon';
import { prizmIconsOilTank } from './prizmIcons-oil-tank.icon';
import { prizmIconsOntology } from './prizmIcons-ontology.icon';
import { prizmIconsOwl } from './prizmIcons-owl.icon';
import { prizmIconsPalette } from './prizmIcons-palette.icon';
import { prizmIconsPanelDown } from './prizmIcons-panel-down.icon';
import { prizmIconsPanelLeft } from './prizmIcons-panel-left.icon';
import { prizmIconsPanelRight } from './prizmIcons-panel-right.icon';
import { prizmIconsPanelTop } from './prizmIcons-panel-top.icon';
import { prizmIconsPantone } from './prizmIcons-pantone.icon';
import { prizmIconsPaperclipVertical } from './prizmIcons-paperclip-vertical.icon';
import { prizmIconsPaperclip } from './prizmIcons-paperclip.icon';
import { prizmIconsPause } from './prizmIcons-pause.icon';
import { prizmIconsPaverSideView } from './prizmIcons-paver-side-view.icon';
import { prizmIconsPenHammer } from './prizmIcons-pen-hammer.icon';
import { prizmIconsPencilArrowRight } from './prizmIcons-pencil-arrow-right.icon';
import { prizmIconsPencilLineBottom } from './prizmIcons-pencil-line-bottom.icon';
import { prizmIconsPencilTriangleDown } from './prizmIcons-pencil-triangle-down.icon';
import { prizmIconsPencilTriangleLeft } from './prizmIcons-pencil-triangle-left.icon';
import { prizmIconsPencil } from './prizmIcons-pencil.icon';
import { prizmIconsPentagonFill } from './prizmIcons-pentagon-fill.icon';
import { prizmIconsPentagon } from './prizmIcons-pentagon.icon';
import { prizmIconsPercent } from './prizmIcons-percent.icon';
import { prizmIconsPhoneActiveCall } from './prizmIcons-phone-active-call.icon';
import { prizmIconsPhoneCancelled } from './prizmIcons-phone-cancelled.icon';
import { prizmIconsPhoneMinus } from './prizmIcons-phone-minus.icon';
import { prizmIconsPhoneOff } from './prizmIcons-phone-off.icon';
import { prizmIconsPhonePaused } from './prizmIcons-phone-paused.icon';
import { prizmIconsPhonePlus } from './prizmIcons-phone-plus.icon';
import { prizmIconsPhone } from './prizmIcons-phone.icon';
import { prizmIconsPi } from './prizmIcons-pi.icon';
import { prizmIconsPieLineNested } from './prizmIcons-pie-line-nested.icon';
import { prizmIconsPieLine } from './prizmIcons-pie-line.icon';
import { prizmIconsPiePentagon } from './prizmIcons-pie-pentagon.icon';
import { prizmIconsPieSeveralParts } from './prizmIcons-pie-several-parts.icon';
import { prizmIconsPieSimple } from './prizmIcons-pie-simple.icon';
import { prizmIconsPie } from './prizmIcons-pie.icon';
import { prizmIconsPipeNodeSideView } from './prizmIcons-pipe-node-side-view.icon';
import { prizmIconsPipeSensor } from './prizmIcons-pipe-sensor.icon';
import { prizmIconsPipeSlash } from './prizmIcons-pipe-slash.icon';
import { prizmIconsPipeValve } from './prizmIcons-pipe-valve.icon';
import { prizmIconsPipelineV1 } from './prizmIcons-pipeline-v1.icon';
import { prizmIconsPipelineV2 } from './prizmIcons-pipeline-v2.icon';
import { prizmIconsPipette } from './prizmIcons-pipette.icon';
import { prizmIconsPlane } from './prizmIcons-plane.icon';
import { prizmIconsPlayBack } from './prizmIcons-play-back.icon';
import { prizmIconsPlay } from './prizmIcons-play.icon';
import { prizmIconsPlusColumnRight } from './prizmIcons-plus-column-right.icon';
import { prizmIconsPlusColumnTop } from './prizmIcons-plus-column-top.icon';
import { prizmIconsPlusTriangleDown } from './prizmIcons-plus-triangle-down.icon';
import { prizmIconsPlus } from './prizmIcons-plus.icon';
import { prizmIconsPolyline } from './prizmIcons-polyline.icon';
import { prizmIconsPortfel } from './prizmIcons-portfel.icon';
import { prizmIconsPower } from './prizmIcons-power.icon';
import { prizmIconsPremisesZql } from './prizmIcons-premises-zql.icon';
import { prizmIconsPress } from './prizmIcons-press.icon';
import { prizmIconsPrinter } from './prizmIcons-printer.icon';
import { prizmIconsProcess } from './prizmIcons-process.icon';
import { prizmIconsPulse } from './prizmIcons-pulse.icon';
import { prizmIconsPumpTriangleDown } from './prizmIcons-pump-triangle-down.icon';
import { prizmIconsPump } from './prizmIcons-pump.icon';
import { prizmIconsPushButtonCellphone } from './prizmIcons-push-button-cellphone.icon';
import { prizmIconsQr } from './prizmIcons-qr.icon';
import { prizmIconsQuestion } from './prizmIcons-question.icon';
import { prizmIconsQuiltFill } from './prizmIcons-quilt-fill.icon';
import { prizmIconsRadiation } from './prizmIcons-radiation.icon';
import { prizmIconsRailcarHopperSideView } from './prizmIcons-railcar-hopper-side-view.icon';
import { prizmIconsRailcarSideView } from './prizmIcons-railcar-side-view.icon';
import { prizmIconsRange } from './prizmIcons-range.icon';
import { prizmIconsReplay } from './prizmIcons-replay.icon';
import { prizmIconsRespiratorV1 } from './prizmIcons-respirator-v1.icon';
import { prizmIconsRespiratorV2 } from './prizmIcons-respirator-v2.icon';
import { prizmIconsRespiratorV3 } from './prizmIcons-respirator-v3.icon';
import { prizmIconsRespiratorV4 } from './prizmIcons-respirator-v4.icon';
import { prizmIconsRespiratorV5 } from './prizmIcons-respirator-v5.icon';
import { prizmIconsRespiratorV6 } from './prizmIcons-respirator-v6.icon';
import { prizmIconsReturnStep } from './prizmIcons-return-step.icon';
import { prizmIconsReturn } from './prizmIcons-return.icon';
import { prizmIconsRhombusFill } from './prizmIcons-rhombus-fill.icon';
import { prizmIconsRhombus } from './prizmIcons-rhombus.icon';
import { prizmIconsRingInSquare } from './prizmIcons-ring-in-square.icon';
import { prizmIconsRulerIndexZql } from './prizmIcons-ruler-index-zql.icon';
import { prizmIconsRuler } from './prizmIcons-ruler.icon';
import { prizmIconsSampleLogsZql } from './prizmIcons-sample-logs-zql.icon';
import { prizmIconsSampleTemplatesZql } from './prizmIcons-sample-templates-zql.icon';
import { prizmIconsSandglass } from './prizmIcons-sandglass.icon';
import { prizmIconsScatterAxis } from './prizmIcons-scatter-axis.icon';
import { prizmIconsScatterBasic } from './prizmIcons-scatter-basic.icon';
import { prizmIconsScatter } from './prizmIcons-scatter.icon';
import { prizmIconsScissors } from './prizmIcons-scissors.icon';
import { prizmIconsSeedlingCircle } from './prizmIcons-seedling-circle.icon';
import { prizmIconsSeedlingRectangle } from './prizmIcons-seedling-rectangle.icon';
import { prizmIconsSeedling } from './prizmIcons-seedling.icon';
import { prizmIconsSelectionCheckedEmpty } from './prizmIcons-selection-checked-empty.icon';
import { prizmIconsSendBackward } from './prizmIcons-send-backward.icon';
import { prizmIconsSendForward } from './prizmIcons-send-forward.icon';
import { prizmIconsSeparator } from './prizmIcons-separator.icon';
import { prizmIconsSequentialFill } from './prizmIcons-sequential-fill.icon';
import { prizmIconsServerNetworkClose } from './prizmIcons-server-network-close.icon';
import { prizmIconsServerNetworkDownload } from './prizmIcons-server-network-download.icon';
import { prizmIconsServerNetworkMinus } from './prizmIcons-server-network-minus.icon';
import { prizmIconsServerNetworkPlus } from './prizmIcons-server-network-plus.icon';
import { prizmIconsServerNetworkSecurity } from './prizmIcons-server-network-security.icon';
import { prizmIconsServerNetworkUpload } from './prizmIcons-server-network-upload.icon';
import { prizmIconsServerNetwork } from './prizmIcons-server-network.icon';
import { prizmIconsServerShield } from './prizmIcons-server-shield.icon';
import { prizmIconsServerSlashUpLine } from './prizmIcons-server-slash-up-line.icon';
import { prizmIconsServerSlash } from './prizmIcons-server-slash.icon';
import { prizmIconsServerUpLine } from './prizmIcons-server-up-line.icon';
import { prizmIconsServer } from './prizmIcons-server.icon';
import { prizmIconsShapeLinkFill } from './prizmIcons-shape-link-fill.icon';
import { prizmIconsShapeLink } from './prizmIcons-shape-link.icon';
import { prizmIconsShapePlus } from './prizmIcons-shape-plus.icon';
import { prizmIconsShareLeft } from './prizmIcons-share-left.icon';
import { prizmIconsShareRight } from './prizmIcons-share-right.icon';
import { prizmIconsShareing } from './prizmIcons-shareing.icon';
import { prizmIconsShieldExclamation } from './prizmIcons-shield-exclamation.icon';
import { prizmIconsShieldSlash } from './prizmIcons-shield-slash.icon';
import { prizmIconsShield } from './prizmIcons-shield.icon';
import { prizmIconsShipFrontView } from './prizmIcons-ship-front-view.icon';
import { prizmIconsShipSideView } from './prizmIcons-ship-side-view.icon';
import { prizmIconsShoppingBox } from './prizmIcons-shopping-box.icon';
import { prizmIconsShovel } from './prizmIcons-shovel.icon';
import { prizmIconsSigma } from './prizmIcons-sigma.icon';
import { prizmIconsSignalAccessPoint } from './prizmIcons-signal-access-point.icon';
import { prizmIconsSignalOff } from './prizmIcons-signal-off.icon';
import { prizmIconsSignalRadioTower } from './prizmIcons-signal-radio-tower.icon';
import { prizmIconsSignal } from './prizmIcons-signal.icon';
import { prizmIconsSlidersH } from './prizmIcons-sliders-h.icon';
import { prizmIconsSlidersV } from './prizmIcons-sliders-v.icon';
import { prizmIconsSnakeCup } from './prizmIcons-snake-cup.icon';
import { prizmIconsSnowflakeUpToBracket } from './prizmIcons-snowflake-up-to-bracket.icon';
import { prizmIconsSnowflake } from './prizmIcons-snowflake.icon';
import { prizmIconsSortFilterRemove } from './prizmIcons-sort-filter-remove.icon';
import { prizmIconsSpecification } from './prizmIcons-specification.icon';
import { prizmIconsSpecsZql } from './prizmIcons-specs-zql.icon';
import { prizmIconsSpeedReductionCooling } from './prizmIcons-speed-reduction-cooling.icon';
import { prizmIconsSquareArrowsCurveRightDown } from './prizmIcons-square-arrows_curve_right_down.icon';
import { prizmIconsSquareArrowsCurveUpRight } from './prizmIcons-square-arrows_curve_up_right.icon';
import { prizmIconsSquareBracketCurlyLeft } from './prizmIcons-square-bracket-curly-left.icon';
import { prizmIconsSquareBracketCurlyRight } from './prizmIcons-square-bracket-curly-right.icon';
import { prizmIconsSquareBracketLeft } from './prizmIcons-square-bracket-left.icon';
import { prizmIconsSquareBracketRight } from './prizmIcons-square-bracket-right.icon';
import { prizmIconsSquareCirclePlusTriangleFill } from './prizmIcons-square-circle-plus-triangle-fill.icon';
import { prizmIconsSquareCircleTriangleCrossFill } from './prizmIcons-square-circle-triangle-cross-fill.icon';
import { prizmIconsSquareCircleTriangleCross } from './prizmIcons-square-circle-triangle-cross.icon';
import { prizmIconsSquareDivide } from './prizmIcons-square-divide.icon';
import { prizmIconsSquareExcel } from './prizmIcons-square-excel.icon';
import { prizmIconsSquareExclamationEmpty } from './prizmIcons-square-exclamation-empty.icon';
import { prizmIconsSquareExclamationFill } from './prizmIcons-square-exclamation-fill.icon';
import { prizmIconsSquareFill } from './prizmIcons-square-fill.icon';
import { prizmIconsSquareHexagonCircleFill } from './prizmIcons-square-hexagon-circle-fill.icon';
import { prizmIconsSquareHexagonCircle } from './prizmIcons-square-hexagon-circle.icon';
import { prizmIconsSquareInSquare } from './prizmIcons-square-in-square.icon';
import { prizmIconsSquareInfoEmpty } from './prizmIcons-square-info-empty.icon';
import { prizmIconsSquareInfoFill } from './prizmIcons-square-info-fill.icon';
import { prizmIconsSquareMinus } from './prizmIcons-square-minus.icon';
import { prizmIconsSquareMultiply } from './prizmIcons-square-multiply.icon';
import { prizmIconsSquareMusicDouble } from './prizmIcons-square-music-double.icon';
import { prizmIconsSquareMusic } from './prizmIcons-square-music.icon';
import { prizmIconsSquarePercent } from './prizmIcons-square-percent.icon';
import { prizmIconsSquarePlus } from './prizmIcons-square-plus.icon';
import { prizmIconsSquarePowerpoint } from './prizmIcons-square-powerpoint.icon';
import { prizmIconsSquareQuestionEmpty } from './prizmIcons-square-question-empty.icon';
import { prizmIconsSquareQuestionFill } from './prizmIcons-square-question-fill.icon';
import { prizmIconsSquareTriangleCircleTriangleFill } from './prizmIcons-square-triangle-circle-triangle-fill.icon';
import { prizmIconsSquareTriangleCircleTriangle } from './prizmIcons-square-triangle-circle-triangle.icon';
import { prizmIconsSquareWord } from './prizmIcons-square-word.icon';
import { prizmIconsStarEmpty } from './prizmIcons-star-empty.icon';
import { prizmIconsStarFill } from './prizmIcons-star-fill.icon';
import { prizmIconsStarHalfFill } from './prizmIcons-star-half-fill.icon';
import { prizmIconsStarLine } from './prizmIcons-star-line.icon';
import { prizmIconsSteamBoiler } from './prizmIcons-steam-boiler.icon';
import { prizmIconsSteamTurbine } from './prizmIcons-steam-turbine.icon';
import { prizmIconsSteam } from './prizmIcons-steam.icon';
import { prizmIconsStop } from './prizmIcons-stop.icon';
import { prizmIconsStopwatch } from './prizmIcons-stopwatch.icon';
import { prizmIconsStorage } from './prizmIcons-storage.icon';
import { prizmIconsStrikethrough } from './prizmIcons-strikethrough.icon';
import { prizmIconsSubskritDown } from './prizmIcons-subskrit-down.icon';
import { prizmIconsSubskritUp } from './prizmIcons-subskrit-up.icon';
import { prizmIconsSumbolAsterisk } from './prizmIcons-sumbol-asterisk.icon';
import { prizmIconsSun } from './prizmIcons-sun.icon';
import { prizmIconsSupportMan } from './prizmIcons-support-man.icon';
import { prizmIconsTableDown } from './prizmIcons-table-down.icon';
import { prizmIconsTableGear } from './prizmIcons-table-gear.icon';
import { prizmIconsTableMagnifyingGlass } from './prizmIcons-table-magnifying-glass.icon';
import { prizmIconsTableRight } from './prizmIcons-table-right.icon';
import { prizmIconsTableTransposeRight } from './prizmIcons-table-transpose-right.icon';
import { prizmIconsTableTransposeTop } from './prizmIcons-table-transpose-top.icon';
import { prizmIconsTableTranspose } from './prizmIcons-table-transpose.icon';
import { prizmIconsTable } from './prizmIcons-table.icon';
import { prizmIconsTabletIqcZql } from './prizmIcons-tablet-iqc-zql.icon';
import { prizmIconsTablet } from './prizmIcons-tablet.icon';
import { prizmIconsTank } from './prizmIcons-tank.icon';
import { prizmIconsTankcarOilSideView } from './prizmIcons-tankcar-oil-side-view.icon';
import { prizmIconsTankcarSideView } from './prizmIcons-tankcar-side-view.icon';
import { prizmIconsTechsZql } from './prizmIcons-techs-zql.icon';
import { prizmIconsTemperatureMinus } from './prizmIcons-temperature-minus.icon';
import { prizmIconsTemperaturePlus } from './prizmIcons-temperature-plus.icon';
import { prizmIconsTemperature } from './prizmIcons-temperature.icon';
import { prizmIconsTemplate } from './prizmIcons-template.icon';
import { prizmIconsTextColor } from './prizmIcons-text-color.icon';
import { prizmIconsText } from './prizmIcons-text.icon';
import { prizmIconsThumbDown } from './prizmIcons-thumb-down.icon';
import { prizmIconsThumbUp } from './prizmIcons-thumb-up.icon';
import { prizmIconsThumbtackDirectly } from './prizmIcons-thumbtack-directly.icon';
import { prizmIconsThumbtack } from './prizmIcons-thumbtack.icon';
import { prizmIconsTouchpad } from './prizmIcons-touchpad.icon';
import { prizmIconsTrainCargo } from './prizmIcons-train-cargo.icon';
import { prizmIconsTrainPassenger } from './prizmIcons-train-passenger.icon';
import { prizmIconsTransmitter } from './prizmIcons-transmitter.icon';
import { prizmIconsTrashEmpty } from './prizmIcons-trash-empty.icon';
import { prizmIconsTrash } from './prizmIcons-trash.icon';
import { prizmIconsTriangleCircleSquareFill } from './prizmIcons-triangle-circle-square-fill.icon';
import { prizmIconsTriangleCircleSquare } from './prizmIcons-triangle-circle-square.icon';
import { prizmIconsTriangleCrossEmpty } from './prizmIcons-triangle-cross-empty.icon';
import { prizmIconsTriangleDown } from './prizmIcons-triangle-down.icon';
import { prizmIconsTriangleExclamationEmpty } from './prizmIcons-triangle-exclamation-empty.icon';
import { prizmIconsTriangleExclamationFill } from './prizmIcons-triangle-exclamation-fill.icon';
import { prizmIconsTriangleFill } from './prizmIcons-triangle-fill.icon';
import { prizmIconsTriangleInfoEmpty } from './prizmIcons-triangle-info-empty.icon';
import { prizmIconsTriangleInfoFill } from './prizmIcons-triangle-info-fill.icon';
import { prizmIconsTriangleLeft } from './prizmIcons-triangle-left.icon';
import { prizmIconsTrianglePlusEmpty } from './prizmIcons-triangle-plus-empty.icon';
import { prizmIconsTriangleRight } from './prizmIcons-triangle-right.icon';
import { prizmIconsTriangleUpDown } from './prizmIcons-triangle-up-down.icon';
import { prizmIconsTriangleUp } from './prizmIcons-triangle-up.icon';
import { prizmIconsTriangle } from './prizmIcons-triangle.icon';
import { prizmIconsTruckDumpSideView } from './prizmIcons-truck-dump-side-view.icon';
import { prizmIconsTruckEmptySideView } from './prizmIcons-truck-empty-side-view.icon';
import { prizmIconsTruckGarbageSideView } from './prizmIcons-truck-garbage-side-view.icon';
import { prizmIconsTruckGasolineSideView } from './prizmIcons-truck-gasoline-side-view.icon';
import { prizmIconsTruckSideView } from './prizmIcons-truck-side-view.icon';
import { prizmIconsTv } from './prizmIcons-tv.icon';
import { prizmIconsUmbrella } from './prizmIcons-umbrella.icon';
import { prizmIconsUnderlined } from './prizmIcons-underlined.icon';
import { prizmIconsUnlock } from './prizmIcons-unlock.icon';
import { prizmIconsUserArrowsSwap } from './prizmIcons-user-arrows-swap.icon';
import { prizmIconsUserCard } from './prizmIcons-user-card.icon';
import { prizmIconsUserCheck } from './prizmIcons-user-check.icon';
import { prizmIconsUserCircle } from './prizmIcons-user-circle.icon';
import { prizmIconsUserCross } from './prizmIcons-user-cross.icon';
import { prizmIconsUserGear } from './prizmIcons-user-gear.icon';
import { prizmIconsUserGroup } from './prizmIcons-user-group.icon';
import { prizmIconsUserLocation } from './prizmIcons-user-location.icon';
import { prizmIconsUserMinus } from './prizmIcons-user-minus.icon';
import { prizmIconsUserPen } from './prizmIcons-user-pen.icon';
import { prizmIconsUserPlus } from './prizmIcons-user-plus.icon';
import { prizmIconsUserShield } from './prizmIcons-user-shield.icon';
import { prizmIconsUserWorker } from './prizmIcons-user-worker.icon';
import { prizmIconsUser } from './prizmIcons-user.icon';
import { prizmIconsUsersArrowRight } from './prizmIcons-users-arrow-right.icon';
import { prizmIconsUsersArrowUpZql } from './prizmIcons-users-arrow-up-zql.icon';
import { prizmIconsUsersGear } from './prizmIcons-users-gear.icon';
import { prizmIconsUsersKey } from './prizmIcons-users-key.icon';
import { prizmIconsUsersLocation } from './prizmIcons-users-location.icon';
import { prizmIconsUsersMinus } from './prizmIcons-users-minus.icon';
import { prizmIconsUsersPlus } from './prizmIcons-users-plus.icon';
import { prizmIconsUsers } from './prizmIcons-users.icon';
import { prizmIconsVectorCircleOnePoint } from './prizmIcons-vector-circle-one-point.icon';
import { prizmIconsVectorCircleTwoPoint } from './prizmIcons-vector-circle-two-point.icon';
import { prizmIconsVectorCircle } from './prizmIcons-vector-circle.icon';
import { prizmIconsVectorLine } from './prizmIcons-vector-line.icon';
import { prizmIconsVectorPoint } from './prizmIcons-vector-point.icon';
import { prizmIconsVectorPolygon } from './prizmIcons-vector-polygon.icon';
import { prizmIconsVectorRectangle } from './prizmIcons-vector-rectangle.icon';
import { prizmIconsVectorSquare } from './prizmIcons-vector-square.icon';
import { prizmIconsVectorTriangle } from './prizmIcons-vector-triangle.icon';
import { prizmIconsVectorsRadius } from './prizmIcons-vectors-radius.icon';
import { prizmIconsVialArrowRotateLeft } from './prizmIcons-vial-arrow-rotate-left.icon';
import { prizmIconsVialFlask } from './prizmIcons-vial-flask.icon';
import { prizmIconsVialPlus } from './prizmIcons-vial-plus.icon';
import { prizmIconsVialXmark } from './prizmIcons-vial-xmark.icon';
import { prizmIconsVial } from './prizmIcons-vial.icon';
import { prizmIconsVideoCross } from './prizmIcons-video-cross.icon';
import { prizmIconsVideoSlash } from './prizmIcons-video-slash.icon';
import { prizmIconsVideo } from './prizmIcons-video.icon';
import { prizmIconsVoicemail } from './prizmIcons-voicemail.icon';
import { prizmIconsVolumeCross } from './prizmIcons-volume-cross.icon';
import { prizmIconsVolumeLow } from './prizmIcons-volume-low.icon';
import { prizmIconsVolumeMinus } from './prizmIcons-volume-minus.icon';
import { prizmIconsVolumeOff } from './prizmIcons-volume-off.icon';
import { prizmIconsVolumePlus } from './prizmIcons-volume-plus.icon';
import { prizmIconsVolumeSlash } from './prizmIcons-volume-slash.icon';
import { prizmIconsVolume } from './prizmIcons-volume.icon';
import { prizmIconsWallet } from './prizmIcons-wallet.icon';
import { prizmIconsWatch } from './prizmIcons-watch.icon';
import { prizmIconsWaterHeater } from './prizmIcons-water-heater.icon';
import { prizmIconsWaterPump } from './prizmIcons-water-pump.icon';
import { prizmIconsWebcam } from './prizmIcons-webcam.icon';
import { prizmIconsWifiOff } from './prizmIcons-wifi-off.icon';
import { prizmIconsWifi } from './prizmIcons-wifi.icon';
import { prizmIconsWindow } from './prizmIcons-window.icon';
import { prizmIconsWrench } from './prizmIcons-wrench.icon';
import { prizmIconsXmarkColumnRight } from './prizmIcons-xmark-column-right.icon';
import { prizmIconsXmarkColumnTop } from './prizmIcons-xmark-column-top.icon';
import { prizmIconsXmarkMini } from './prizmIcons-xmark-mini.icon';
import { prizmIconsXmark } from './prizmIcons-xmark.icon';
export const completeIconSet = [
  prizmIconsAgendaFill,
  prizmIconsAirplaneSideView,
  prizmIconsAirplaneTopView,
  prizmIconsAlarmClock,
  prizmIconsAlarmPlus,
  prizmIconsAlignBottom,
  prizmIconsAlignCenterH,
  prizmIconsAlignCenterV,
  prizmIconsAlignCenter,
  prizmIconsAlignJustify,
  prizmIconsAlignLeft,
  prizmIconsAlignRight,
  prizmIconsAlignTop,
  prizmIconsAmbulanceSideView,
  prizmIconsAndroidPill,
  prizmIconsAndroid,
  prizmIconsAngleLeftRightArrowsDown,
  prizmIconsAngleLeftRight,
  prizmIconsAngleLeft,
  prizmIconsAngleRight,
  prizmIconsArrangeSendToBack,
  prizmIconsArrayFill,
  prizmIconsArrowBoldDown,
  prizmIconsArrowBoldLeft,
  prizmIconsArrowBoldRight,
  prizmIconsArrowBoldUp,
  prizmIconsArrowDaw,
  prizmIconsArrowDownBetweenLines,
  prizmIconsArrowDownFromDoubleLine,
  prizmIconsArrowDownFromLine,
  prizmIconsArrowDownInCircleEmpty,
  prizmIconsArrowDownToBracket,
  prizmIconsArrowDownToDoubleLine,
  prizmIconsArrowDownToLine,
  prizmIconsArrowDownWideShort,
  prizmIconsArrowDown,
  prizmIconsArrowLeftBetweenLines,
  prizmIconsArrowLeftDown,
  prizmIconsArrowLeftFromBracket,
  prizmIconsArrowLeftInCircleEmpty,
  prizmIconsArrowLeftUp,
  prizmIconsArrowLeft,
  prizmIconsArrowRightBetweenLines,
  prizmIconsArrowRightDown,
  prizmIconsArrowRightFromBracket,
  prizmIconsArrowRightInCircleEmpty,
  prizmIconsArrowRightUp,
  prizmIconsArrowRight,
  prizmIconsArrowRotateLeft,
  prizmIconsArrowRotateRight,
  prizmIconsArrowTurnDownLeft,
  prizmIconsArrowTurnDownRight,
  prizmIconsArrowTurnLeftDown,
  prizmIconsArrowTurnLeftUp,
  prizmIconsArrowTurnRightDown,
  prizmIconsArrowTurnRightUp,
  prizmIconsArrowTurnUpLeft,
  prizmIconsArrowTurnUpRight,
  prizmIconsArrowUpArrowDownH,
  prizmIconsArrowUpArrowDownV,
  prizmIconsArrowUpBetweenLines,
  prizmIconsArrowUpFromBracket,
  prizmIconsArrowUpFromDoubleLine,
  prizmIconsArrowUpFromLine,
  prizmIconsArrowUpInCircleEmpty,
  prizmIconsArrowUpToDottedLine,
  prizmIconsArrowUpToDoubleLine,
  prizmIconsArrowUpToLine,
  prizmIconsArrowUpWideShort,
  prizmIconsArrowUp,
  prizmIconsArrowsAllDirections,
  prizmIconsArrowsCompare,
  prizmIconsArrowsCross,
  prizmIconsArrowsDirectionToTheLines,
  prizmIconsArrowsInside,
  prizmIconsArrowsLeftRightBrackets,
  prizmIconsArrowsLeftRightToLines,
  prizmIconsArrowsMaximize,
  prizmIconsArrowsMinimize,
  prizmIconsArrowsOut,
  prizmIconsArrowsRepeatH,
  prizmIconsArrowsRepeatV,
  prizmIconsArrowsRotateH,
  prizmIconsArrowsRotateV,
  prizmIconsArrowsShuffle,
  prizmIconsArrowsSwapH,
  prizmIconsArrowsSwapV,
  prizmIconsArrowsUpDownToLines,
  prizmIconsAtSign,
  prizmIconsAudioSpeakers,
  prizmIconsAward,
  prizmIconsBag,
  prizmIconsBalloon,
  prizmIconsBan,
  prizmIconsBarAxis,
  prizmIconsBarBasic,
  prizmIconsBarColumnsAxisX,
  prizmIconsBarColumns,
  prizmIconsBarHistogram,
  prizmIconsBarSquare,
  prizmIconsBarStackedAxis,
  prizmIconsBarStacked,
  prizmIconsBarcode,
  prizmIconsBarsSort,
  prizmIconsBars,
  prizmIconsBatteryBolt,
  prizmIconsBatteryEmpty,
  prizmIconsBatteryExclametionMark,
  prizmIconsBatteryFull,
  prizmIconsBatteryHalf,
  prizmIconsBatteryMinus,
  prizmIconsBatteryPlus,
  prizmIconsBatteryQuarter,
  prizmIconsBatteryThreeQuarters,
  prizmIconsBdrvAdministration,
  prizmIconsBellFill,
  prizmIconsBellPlus,
  prizmIconsBellRingFill,
  prizmIconsBellRing,
  prizmIconsBellSlash,
  prizmIconsBell,
  prizmIconsBezierCurve,
  prizmIconsBitcoin,
  prizmIconsBluetooth,
  prizmIconsBoilerHotWaterGasAndOil,
  prizmIconsBoiler,
  prizmIconsBold,
  prizmIconsBookStack,
  prizmIconsBookCheck,
  prizmIconsBookClosed,
  prizmIconsBookOpenPlus,
  prizmIconsBookOpenReArrowLeft,
  prizmIconsBookOpenReArrowRight,
  prizmIconsBookOpenText,
  prizmIconsBookOpenWithPage,
  prizmIconsBookOpen,
  prizmIconsBookmarkCheckFill,
  prizmIconsBookmarkCheck,
  prizmIconsBookmarkCrossFill,
  prizmIconsBookmarkCross,
  prizmIconsBookmarkFill,
  prizmIconsBookmarkMusicFill,
  prizmIconsBookmarkMusic,
  prizmIconsBookmarkPlusFill,
  prizmIconsBookmarkPlus,
  prizmIconsBookmark,
  prizmIconsBorderAll,
  prizmIconsBorderBottom,
  prizmIconsBorderCenterH,
  prizmIconsBorderCenterV,
  prizmIconsBorderInner,
  prizmIconsBorderLeft,
  prizmIconsBorderNone,
  prizmIconsBorderOuter,
  prizmIconsBorderRight,
  prizmIconsBorderTopLeft,
  prizmIconsBorderTop,
  prizmIconsBoxOpenArrowDown,
  prizmIconsBox,
  prizmIconsBracketsCurly,
  prizmIconsBracketsSquare,
  prizmIconsBroom,
  prizmIconsBrowser,
  prizmIconsBrush,
  prizmIconsBubbleMessageAdd,
  prizmIconsBubbleMessageAttention,
  prizmIconsBubbleMessageCircle,
  prizmIconsBubbleMessageEmpty,
  prizmIconsBubbleMessageOff,
  prizmIconsBubbleMessageQuestion,
  prizmIconsBubbleMessageText,
  prizmIconsBubbleMessage,
  prizmIconsBurn,
  prizmIconsCalculatorArrowRotateLeft,
  prizmIconsCalculatorFunction,
  prizmIconsCalculator,
  prizmIconsCalendarBlank,
  prizmIconsCalendarCheck,
  prizmIconsCalendarClock,
  prizmIconsCalendarDeleted,
  prizmIconsCalendarEvent,
  prizmIconsCalendarPlus,
  prizmIconsCalendarQuestion,
  prizmIconsCalendarRange,
  prizmIconsCalendarToday,
  prizmIconsCalendar,
  prizmIconsCalibrationCharacteristicsZql,
  prizmIconsCameraFront,
  prizmIconsCameraMovieCross,
  prizmIconsCameraMovie,
  prizmIconsCamera,
  prizmIconsCarJeepSideView,
  prizmIconsCarLightSideView,
  prizmIconsCarbon,
  prizmIconsCarouselFill,
  prizmIconsCartFlatbedContainer,
  prizmIconsCartPlus,
  prizmIconsCart,
  prizmIconsCellphoneWireless,
  prizmIconsCellphone,
  prizmIconsChartsIqcZql,
  prizmIconsCheckDouble,
  prizmIconsCheckerboard,
  prizmIconsChek,
  prizmIconsChevronDownToDoubleLine,
  prizmIconsChevronDown,
  prizmIconsChevronLeft,
  prizmIconsChevronMiniLeft,
  prizmIconsChevronMiniRight,
  prizmIconsChevronRightAboveDoubleLine,
  prizmIconsChevronRight,
  prizmIconsChevronUp,
  prizmIconsChevronsDoubleDown,
  prizmIconsChevronsDoubleLeft,
  prizmIconsChevronsDoubleMiniLeft,
  prizmIconsChevronsDoubleMiniRight,
  prizmIconsChevronsDoubleRight,
  prizmIconsChevronsDoubleUp,
  prizmIconsChevronsInsideHorizontally,
  prizmIconsChevronsInsideVertically,
  prizmIconsChevronsOutsideHorizontally,
  prizmIconsChevronsOutsideVertically,
  prizmIconsCircleChekEmpty,
  prizmIconsCircleChekFill,
  prizmIconsCircleExclamationEmpty,
  prizmIconsCircleExclamationFill,
  prizmIconsCircleInHexagon,
  prizmIconsCircleInfoEmpty,
  prizmIconsCircleInfoFill,
  prizmIconsCircleMusic,
  prizmIconsCirclePlusFill,
  prizmIconsCirclePlus,
  prizmIconsCircleQuestionEmpty,
  prizmIconsCircleQuestionFill,
  prizmIconsCircleSquareFill,
  prizmIconsCircleSquareInSquare,
  prizmIconsCircleSquare,
  prizmIconsCircleXmarkFill,
  prizmIconsCircleXmark,
  prizmIconsCirclesLineLeftUpCircleRightDownFill,
  prizmIconsCirclesLineLeftUpCircleRightDown,
  prizmIconsClapperboardCross,
  prizmIconsClapperboardOpen,
  prizmIconsClockAdd,
  prizmIconsClockArrowDown,
  prizmIconsClockArrowRight,
  prizmIconsClockArrowUp,
  prizmIconsClockDeleted,
  prizmIconsClockExclamation,
  prizmIconsClockLineEnd,
  prizmIconsClockRotateLeft,
  prizmIconsClockRotateRight,
  prizmIconsClock,
  prizmIconsCloudArrowDown,
  prizmIconsCloudArrowUpInside,
  prizmIconsCloudArrowUp,
  prizmIconsCloudCheck,
  prizmIconsCloud,
  prizmIconsCodeDownload,
  prizmIconsCodeSimple,
  prizmIconsCode,
  prizmIconsCollageFill,
  prizmIconsCollection,
  prizmIconsCollector,
  prizmIconsColumnFill,
  prizmIconsColumn,
  prizmIconsCompass,
  prizmIconsComponent,
  prizmIconsConcreteMixerSideView,
  prizmIconsContainerV1,
  prizmIconsContainerV2,
  prizmIconsContainers,
  prizmIconsControlChartsZql,
  prizmIconsCopyColumn,
  prizmIconsCopyRow,
  prizmIconsCopy,
  prizmIconsCrane,
  prizmIconsCreditCardPlus,
  prizmIconsCreditCardSlash,
  prizmIconsCreditCard,
  prizmIconsCrop,
  prizmIconsCrosshairsDot,
  prizmIconsCrosshairsSimple,
  prizmIconsCubeEmpty,
  prizmIconsCubeFill,
  prizmIconsCubes,
  prizmIconsDashboardFill,
  prizmIconsDashboardVariantFill,
  prizmIconsDatabaseChek,
  prizmIconsDatabaseJson,
  prizmIconsDatabaseMagnifyingGlass,
  prizmIconsDatabaseMinus,
  prizmIconsDatabasePlus,
  prizmIconsDatabaseSql,
  prizmIconsDatabaseXmark,
  prizmIconsDatabase,
  prizmIconsDayFill,
  prizmIconsDecagramChekEmpty,
  prizmIconsDecagramChekFill,
  prizmIconsDecagramExclamationEmpty,
  prizmIconsDecagramExclamationFill,
  prizmIconsDefaultIco,
  prizmIconsDeleteContent,
  prizmIconsDesktopTower,
  prizmIconsDiscreteSet,
  prizmIconsDollarSlash,
  prizmIconsDollar,
  prizmIconsDoughnut,
  prizmIconsDropletSlash,
  prizmIconsDroplet,
  prizmIconsEarlyVersion,
  prizmIconsEarth,
  prizmIconsEditorDown,
  prizmIconsEditorRight,
  prizmIconsElectrics,
  prizmIconsEllipsisGrid,
  prizmIconsEllipsisH,
  prizmIconsEllipsisV,
  prizmIconsEnergyCheck,
  prizmIconsEnergySlash,
  prizmIconsEnergy,
  prizmIconsEquipmentZql,
  prizmIconsEraser,
  prizmIconsEthernet,
  prizmIconsExchanger,
  prizmIconsExclamation,
  prizmIconsEyeClosed,
  prizmIconsEyeSlash,
  prizmIconsEye,
  prizmIconsFaceFrown,
  prizmIconsFaceSmile,
  prizmIconsFactoryPipe,
  prizmIconsFactoryPipes,
  prizmIconsFactory,
  prizmIconsFan,
  prizmIconsFileArrowDownLeft,
  prizmIconsFileArrowDown,
  prizmIconsFileArrowUp,
  prizmIconsFileArrow,
  prizmIconsFileArrowsUpRight,
  prizmIconsFileCamera,
  prizmIconsFileCrossOut,
  prizmIconsFileCross,
  prizmIconsFileDoc,
  prizmIconsFileDocx,
  prizmIconsFileDot,
  prizmIconsFileEmpty,
  prizmIconsFileExclamation,
  prizmIconsFileEye,
  prizmIconsFileFilled,
  prizmIconsFileImage,
  prizmIconsFileMagnifyingGlass,
  prizmIconsFileMinus,
  prizmIconsFileMusic,
  prizmIconsFilePdf,
  prizmIconsFilePen,
  prizmIconsFilePlay,
  prizmIconsFilePlus,
  prizmIconsFilePpt,
  prizmIconsFilePptx,
  prizmIconsFileTxt,
  prizmIconsFileUpRight,
  prizmIconsFileXls,
  prizmIconsFileXlsx,
  prizmIconsFilesMode,
  prizmIconsFill,
  prizmIconsFilmCross,
  prizmIconsFilm,
  prizmIconsFilterGear,
  prizmIconsFilterOntology,
  prizmIconsFilter,
  prizmIconsFinanceScanner,
  prizmIconsFire,
  prizmIconsFlagFillRed,
  prizmIconsFlagFill,
  prizmIconsFlag,
  prizmIconsFlaskRoundPotion,
  prizmIconsFlask,
  prizmIconsFloppyCrossOut,
  prizmIconsFloppyCross,
  prizmIconsFloppyPen,
  prizmIconsFloppyStar,
  prizmIconsFloppy,
  prizmIconsFolderOpen,
  prizmIconsFolderUnderlineMinus,
  prizmIconsFolderUnderlinePlus,
  prizmIconsFolderUnderline,
  prizmIconsFolderArrowDownLeft,
  prizmIconsFolderArrowDown,
  prizmIconsFolderArrowUpRight,
  prizmIconsFolderCross,
  prizmIconsFolderDot,
  prizmIconsFolderMinus,
  prizmIconsFolderPlus,
  prizmIconsFolder,
  prizmIconsForvardStep,
  prizmIconsForward,
  prizmIconsFuelOilTank,
  prizmIconsFunction,
  prizmIconsGantt,
  prizmIconsGasMonitoring,
  prizmIconsGasPump,
  prizmIconsGas,
  prizmIconsGauge,
  prizmIconsGear5Edge,
  prizmIconsGear8Edge,
  prizmIconsGearCooling,
  prizmIconsGenerator,
  prizmIconsGift,
  prizmIconsGitLab,
  prizmIconsGlobe,
  prizmIconsGridFill,
  prizmIconsGrid,
  prizmIconsGripDotsVertical,
  prizmIconsHardDriveOutline,
  prizmIconsHashDash,
  prizmIconsHash,
  prizmIconsHashtag,
  prizmIconsHeadlineFill,
  prizmIconsHeadphones,
  prizmIconsHeartEmpty,
  prizmIconsHeartFill,
  prizmIconsHelicopterSideView,
  prizmIconsHexagonExclamationEmpty,
  prizmIconsHexagonExclamationFill,
  prizmIconsHexagonFill,
  prizmIconsHexagon,
  prizmIconsHexagonsAxis,
  prizmIconsHexagons,
  prizmIconsHistogramAxis,
  prizmIconsHouseMini,
  prizmIconsHouse,
  prizmIconsImage,
  prizmIconsImportersZql,
  prizmIconsIndentArrowLeft,
  prizmIconsIndentArrowRight,
  prizmIconsInfinity,
  prizmIconsInfo,
  prizmIconsInputDevice,
  prizmIconsInstagram,
  prizmIconsItalic,
  prizmIconsKey,
  prizmIconsKeyboardClose,
  prizmIconsKeyboard,
  prizmIconsLabelCross,
  prizmIconsLabelExclamationMark,
  prizmIconsLabelFill,
  prizmIconsLabelMagnifyingGlass,
  prizmIconsLabelPlus,
  prizmIconsLabelQuestion,
  prizmIconsLabelText,
  prizmIconsLabel,
  prizmIconsLanConnect,
  prizmIconsLanDisconnect,
  prizmIconsLanPending,
  prizmIconsLaptopPhoneSlash,
  prizmIconsLaptopPhone,
  prizmIconsLaptopSlash,
  prizmIconsLaptop,
  prizmIconsLayerGroupSlash,
  prizmIconsLayerGroup,
  prizmIconsLayerNetwork,
  prizmIconsLetterDay,
  prizmIconsLetterHour,
  prizmIconsLetterMinute,
  prizmIconsLetterMonth,
  prizmIconsLetterSecond,
  prizmIconsLetterTime,
  prizmIconsLetterYear,
  prizmIconsLibraryPlus,
  prizmIconsLightbulb,
  prizmIconsLineAxisArrowDown,
  prizmIconsLineAxisX,
  prizmIconsLineAxis,
  prizmIconsLineDown,
  prizmIconsLineHeight,
  prizmIconsLineMultipleYAxisX,
  prizmIconsLineMultipleYAxis,
  prizmIconsLineUp,
  prizmIconsLine,
  prizmIconsLinkBreak,
  prizmIconsLinkMinus,
  prizmIconsLinkPlus,
  prizmIconsLinkSimpleH,
  prizmIconsLinkSimple,
  prizmIconsListSquare,
  prizmIconsListFill,
  prizmIconsListOl,
  prizmIconsListTreeArchive,
  prizmIconsListTree,
  prizmIconsListUl,
  prizmIconsList,
  prizmIconsLngStorage,
  prizmIconsLoader,
  prizmIconsLocationArrow,
  prizmIconsLocationDirectly,
  prizmIconsLocationDot,
  prizmIconsLocationMinus,
  prizmIconsLocationPlus,
  prizmIconsLocationSlash,
  prizmIconsLocationUser,
  prizmIconsLock,
  prizmIconsLogoGreyZ,
  prizmIconsMagicWand,
  prizmIconsMagnifyingGlassExclamation,
  prizmIconsMagnifyingGlassMinus,
  prizmIconsMagnifyingGlassOntology,
  prizmIconsMagnifyingGlassPlus,
  prizmIconsMagnifyingGlassTagsWords,
  prizmIconsMagnifyingGlassTopFromBracket,
  prizmIconsMagnifyingGlassTriangleDown,
  prizmIconsMagnifyingGlassXmark,
  prizmIconsMagnifyingGlass,
  prizmIconsMailOpen,
  prizmIconsMail,
  prizmIconsMailbox,
  prizmIconsMapBase,
  prizmIconsMapMarkerDateV1,
  prizmIconsMapMarkerDateV2,
  prizmIconsMapPin,
  prizmIconsMap,
  prizmIconsMedical,
  prizmIconsMerge,
  prizmIconsMessagingTelegramSend,
  prizmIconsMessagingTelegram,
  prizmIconsMicrophoneSlash,
  prizmIconsMicrophone,
  prizmIconsMinibusSideView,
  prizmIconsMinusCircleFill,
  prizmIconsMinusCircle,
  prizmIconsMinus,
  prizmIconsModuleFill,
  prizmIconsMonitor,
  prizmIconsMoon,
  prizmIconsMusicSlash,
  prizmIconsMusic,
  prizmIconsNetworkExternalLink,
  prizmIconsNetworkV1,
  prizmIconsNetworkV2,
  prizmIconsNetworkV3,
  prizmIconsNetworkWired,
  prizmIconsNiFiLogo,
  prizmIconsNormdocsZql,
  prizmIconsNpm,
  prizmIconsObjectDownSubtract,
  prizmIconsObjectExclude,
  prizmIconsObjectIntersect,
  prizmIconsObjectSelection,
  prizmIconsObjectUnion,
  prizmIconsObjectUpSubtract,
  prizmIconsObject,
  prizmIconsOilBarrel,
  prizmIconsOilCanister,
  prizmIconsOilDropletArrowsAll,
  prizmIconsOilDropletArrowsRepeatH,
  prizmIconsOilDropletChek,
  prizmIconsOilDroplet,
  prizmIconsOilField,
  prizmIconsOilTank,
  prizmIconsOntology,
  prizmIconsOwl,
  prizmIconsPalette,
  prizmIconsPanelDown,
  prizmIconsPanelLeft,
  prizmIconsPanelRight,
  prizmIconsPanelTop,
  prizmIconsPantone,
  prizmIconsPaperclipVertical,
  prizmIconsPaperclip,
  prizmIconsPause,
  prizmIconsPaverSideView,
  prizmIconsPenHammer,
  prizmIconsPencilArrowRight,
  prizmIconsPencilLineBottom,
  prizmIconsPencilTriangleDown,
  prizmIconsPencilTriangleLeft,
  prizmIconsPencil,
  prizmIconsPentagonFill,
  prizmIconsPentagon,
  prizmIconsPercent,
  prizmIconsPhoneActiveCall,
  prizmIconsPhoneCancelled,
  prizmIconsPhoneMinus,
  prizmIconsPhoneOff,
  prizmIconsPhonePaused,
  prizmIconsPhonePlus,
  prizmIconsPhone,
  prizmIconsPi,
  prizmIconsPieLineNested,
  prizmIconsPieLine,
  prizmIconsPiePentagon,
  prizmIconsPieSeveralParts,
  prizmIconsPieSimple,
  prizmIconsPie,
  prizmIconsPipeNodeSideView,
  prizmIconsPipeSensor,
  prizmIconsPipeSlash,
  prizmIconsPipeValve,
  prizmIconsPipelineV1,
  prizmIconsPipelineV2,
  prizmIconsPipette,
  prizmIconsPlane,
  prizmIconsPlayBack,
  prizmIconsPlay,
  prizmIconsPlusColumnRight,
  prizmIconsPlusColumnTop,
  prizmIconsPlusTriangleDown,
  prizmIconsPlus,
  prizmIconsPolyline,
  prizmIconsPortfel,
  prizmIconsPower,
  prizmIconsPremisesZql,
  prizmIconsPress,
  prizmIconsPrinter,
  prizmIconsProcess,
  prizmIconsPulse,
  prizmIconsPumpTriangleDown,
  prizmIconsPump,
  prizmIconsPushButtonCellphone,
  prizmIconsQr,
  prizmIconsQuestion,
  prizmIconsQuiltFill,
  prizmIconsRadiation,
  prizmIconsRailcarHopperSideView,
  prizmIconsRailcarSideView,
  prizmIconsRange,
  prizmIconsReplay,
  prizmIconsRespiratorV1,
  prizmIconsRespiratorV2,
  prizmIconsRespiratorV3,
  prizmIconsRespiratorV4,
  prizmIconsRespiratorV5,
  prizmIconsRespiratorV6,
  prizmIconsReturnStep,
  prizmIconsReturn,
  prizmIconsRhombusFill,
  prizmIconsRhombus,
  prizmIconsRingInSquare,
  prizmIconsRulerIndexZql,
  prizmIconsRuler,
  prizmIconsSampleLogsZql,
  prizmIconsSampleTemplatesZql,
  prizmIconsSandglass,
  prizmIconsScatterAxis,
  prizmIconsScatterBasic,
  prizmIconsScatter,
  prizmIconsScissors,
  prizmIconsSeedlingCircle,
  prizmIconsSeedlingRectangle,
  prizmIconsSeedling,
  prizmIconsSelectionCheckedEmpty,
  prizmIconsSendBackward,
  prizmIconsSendForward,
  prizmIconsSeparator,
  prizmIconsSequentialFill,
  prizmIconsServerNetworkClose,
  prizmIconsServerNetworkDownload,
  prizmIconsServerNetworkMinus,
  prizmIconsServerNetworkPlus,
  prizmIconsServerNetworkSecurity,
  prizmIconsServerNetworkUpload,
  prizmIconsServerNetwork,
  prizmIconsServerShield,
  prizmIconsServerSlashUpLine,
  prizmIconsServerSlash,
  prizmIconsServerUpLine,
  prizmIconsServer,
  prizmIconsShapeLinkFill,
  prizmIconsShapeLink,
  prizmIconsShapePlus,
  prizmIconsShareLeft,
  prizmIconsShareRight,
  prizmIconsShareing,
  prizmIconsShieldExclamation,
  prizmIconsShieldSlash,
  prizmIconsShield,
  prizmIconsShipFrontView,
  prizmIconsShipSideView,
  prizmIconsShoppingBox,
  prizmIconsShovel,
  prizmIconsSigma,
  prizmIconsSignalAccessPoint,
  prizmIconsSignalOff,
  prizmIconsSignalRadioTower,
  prizmIconsSignal,
  prizmIconsSlidersH,
  prizmIconsSlidersV,
  prizmIconsSnakeCup,
  prizmIconsSnowflakeUpToBracket,
  prizmIconsSnowflake,
  prizmIconsSortFilterRemove,
  prizmIconsSpecification,
  prizmIconsSpecsZql,
  prizmIconsSpeedReductionCooling,
  prizmIconsSquareArrowsCurveRightDown,
  prizmIconsSquareArrowsCurveUpRight,
  prizmIconsSquareBracketCurlyLeft,
  prizmIconsSquareBracketCurlyRight,
  prizmIconsSquareBracketLeft,
  prizmIconsSquareBracketRight,
  prizmIconsSquareCirclePlusTriangleFill,
  prizmIconsSquareCircleTriangleCrossFill,
  prizmIconsSquareCircleTriangleCross,
  prizmIconsSquareDivide,
  prizmIconsSquareExcel,
  prizmIconsSquareExclamationEmpty,
  prizmIconsSquareExclamationFill,
  prizmIconsSquareFill,
  prizmIconsSquareHexagonCircleFill,
  prizmIconsSquareHexagonCircle,
  prizmIconsSquareInSquare,
  prizmIconsSquareInfoEmpty,
  prizmIconsSquareInfoFill,
  prizmIconsSquareMinus,
  prizmIconsSquareMultiply,
  prizmIconsSquareMusicDouble,
  prizmIconsSquareMusic,
  prizmIconsSquarePercent,
  prizmIconsSquarePlus,
  prizmIconsSquarePowerpoint,
  prizmIconsSquareQuestionEmpty,
  prizmIconsSquareQuestionFill,
  prizmIconsSquareTriangleCircleTriangleFill,
  prizmIconsSquareTriangleCircleTriangle,
  prizmIconsSquareWord,
  prizmIconsStarEmpty,
  prizmIconsStarFill,
  prizmIconsStarHalfFill,
  prizmIconsStarLine,
  prizmIconsSteamBoiler,
  prizmIconsSteamTurbine,
  prizmIconsSteam,
  prizmIconsStop,
  prizmIconsStopwatch,
  prizmIconsStorage,
  prizmIconsStrikethrough,
  prizmIconsSubskritDown,
  prizmIconsSubskritUp,
  prizmIconsSumbolAsterisk,
  prizmIconsSun,
  prizmIconsSupportMan,
  prizmIconsTableDown,
  prizmIconsTableGear,
  prizmIconsTableMagnifyingGlass,
  prizmIconsTableRight,
  prizmIconsTableTransposeRight,
  prizmIconsTableTransposeTop,
  prizmIconsTableTranspose,
  prizmIconsTable,
  prizmIconsTabletIqcZql,
  prizmIconsTablet,
  prizmIconsTank,
  prizmIconsTankcarOilSideView,
  prizmIconsTankcarSideView,
  prizmIconsTechsZql,
  prizmIconsTemperatureMinus,
  prizmIconsTemperaturePlus,
  prizmIconsTemperature,
  prizmIconsTemplate,
  prizmIconsTextColor,
  prizmIconsText,
  prizmIconsThumbDown,
  prizmIconsThumbUp,
  prizmIconsThumbtackDirectly,
  prizmIconsThumbtack,
  prizmIconsTouchpad,
  prizmIconsTrainCargo,
  prizmIconsTrainPassenger,
  prizmIconsTransmitter,
  prizmIconsTrashEmpty,
  prizmIconsTrash,
  prizmIconsTriangleCircleSquareFill,
  prizmIconsTriangleCircleSquare,
  prizmIconsTriangleCrossEmpty,
  prizmIconsTriangleDown,
  prizmIconsTriangleExclamationEmpty,
  prizmIconsTriangleExclamationFill,
  prizmIconsTriangleFill,
  prizmIconsTriangleInfoEmpty,
  prizmIconsTriangleInfoFill,
  prizmIconsTriangleLeft,
  prizmIconsTrianglePlusEmpty,
  prizmIconsTriangleRight,
  prizmIconsTriangleUpDown,
  prizmIconsTriangleUp,
  prizmIconsTriangle,
  prizmIconsTruckDumpSideView,
  prizmIconsTruckEmptySideView,
  prizmIconsTruckGarbageSideView,
  prizmIconsTruckGasolineSideView,
  prizmIconsTruckSideView,
  prizmIconsTv,
  prizmIconsUmbrella,
  prizmIconsUnderlined,
  prizmIconsUnlock,
  prizmIconsUserArrowsSwap,
  prizmIconsUserCard,
  prizmIconsUserCheck,
  prizmIconsUserCircle,
  prizmIconsUserCross,
  prizmIconsUserGear,
  prizmIconsUserGroup,
  prizmIconsUserLocation,
  prizmIconsUserMinus,
  prizmIconsUserPen,
  prizmIconsUserPlus,
  prizmIconsUserShield,
  prizmIconsUserWorker,
  prizmIconsUser,
  prizmIconsUsersArrowRight,
  prizmIconsUsersArrowUpZql,
  prizmIconsUsersGear,
  prizmIconsUsersKey,
  prizmIconsUsersLocation,
  prizmIconsUsersMinus,
  prizmIconsUsersPlus,
  prizmIconsUsers,
  prizmIconsVectorCircleOnePoint,
  prizmIconsVectorCircleTwoPoint,
  prizmIconsVectorCircle,
  prizmIconsVectorLine,
  prizmIconsVectorPoint,
  prizmIconsVectorPolygon,
  prizmIconsVectorRectangle,
  prizmIconsVectorSquare,
  prizmIconsVectorTriangle,
  prizmIconsVectorsRadius,
  prizmIconsVialArrowRotateLeft,
  prizmIconsVialFlask,
  prizmIconsVialPlus,
  prizmIconsVialXmark,
  prizmIconsVial,
  prizmIconsVideoCross,
  prizmIconsVideoSlash,
  prizmIconsVideo,
  prizmIconsVoicemail,
  prizmIconsVolumeCross,
  prizmIconsVolumeLow,
  prizmIconsVolumeMinus,
  prizmIconsVolumeOff,
  prizmIconsVolumePlus,
  prizmIconsVolumeSlash,
  prizmIconsVolume,
  prizmIconsWallet,
  prizmIconsWatch,
  prizmIconsWaterHeater,
  prizmIconsWaterPump,
  prizmIconsWebcam,
  prizmIconsWifiOff,
  prizmIconsWifi,
  prizmIconsWindow,
  prizmIconsWrench,
  prizmIconsXmarkColumnRight,
  prizmIconsXmarkColumnTop,
  prizmIconsXmarkMini,
  prizmIconsXmark,
];
