/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSnowflakeUpToBracket: {
  name: 'snowflake-up-to-bracket';
  data: string;
} = {
  name: 'snowflake-up-to-bracket',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M9.447.776a.5.5 0 1 0-.894.448l.786 1.572L8 5.028 5.429.743a.5.5 0 0 0-.858.514L7.117 5.5H5.25L3.9 3.7a.5.5 0 0 0-.8.6L4 5.5H2a.5.5 0 0 0 0 1h2l-.9 1.2a.5.5 0 1 0 .8.6l1.35-1.8h1.867L4.57 10.743a.5.5 0 1 0 .858.514L8 6.972l1.34 2.232-.787 1.572a.5.5 0 1 0 .894.448l.502-1.004.622 1.037a.5.5 0 0 0 .858-.514L10.683 9.5H12a.5.5 0 0 0 0-1h-1.917l-1.2-2H14a.5.5 0 0 0 0-1H8.883l1.2-2H12a.5.5 0 0 0 0-1h-1.317l.746-1.243a.5.5 0 1 0-.858-.514L9.95 1.78 9.447.776ZM1.5 12a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 2 15.5h12a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-2Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`
};
