/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSortFilterRemove: {
  name: 'sort-filter-remove';
  data: string;
} = {
  name: 'sort-filter-remove',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.29.5a.5.5 0 0 0-.447.724L4.79 9.118V13a.5.5 0 0 0 .276.447l4 2A.5.5 0 0 0 9.79 15V9.118l3.947-7.894A.5.5 0 0 0 13.29.5h-12Zm4.447 8.276L2.1 1.5h10.382L8.843 8.776A.5.5 0 0 0 8.79 9v5.191l-3-1.5V9a.5.5 0 0 0-.053-.224Zm5.617 1.87a.5.5 0 0 0-.708.708L12.293 13l-1.647 1.646a.5.5 0 0 0 .708.708L13 13.707l1.646 1.647a.5.5 0 0 0 .708-.708L13.707 13l1.647-1.646a.5.5 0 0 0-.708-.708L13 12.293l-1.646-1.647Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
