/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsTruckGasolineSideView: {
  name: 'truck-gasoline-side-view';
  data: string;
} = {
  name: 'truck-gasoline-side-view',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 8a3 3 0 0 1 3-3h7a3 3 0 0 1 3 3v3c0 .35-.06.687-.17 1H16V7a1 1 0 0 1 1-1h2a1 1 0 0 1 .707.293l2 2A1 1 0 0 1 22 9v4a1 1 0 0 1-1 1H5a3 3 0 0 1-3-3V8Zm8 4h2a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h5Zm-5.5 5a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1Zm-2.5.5a2.5 2.5 0 1 1 5 0 2.5 2.5 0 0 1-5 0Zm5 0a2.5 2.5 0 1 1 5 0 2.5 2.5 0 0 1-5 0Zm2.5-.5a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1Zm8.5.5a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0Zm.5-2.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5Zm1.5-3h-2V8h.586L20 9.414V12Z" fill="currentColor"/></svg>`
};
