/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsHash: {
  name: 'hash';
  data: string;
} = {
  name: 'hash',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M10.354 1.354a.5.5 0 0 0-.708-.708L8 2.293 6.354.646a.5.5 0 1 0-.708.708L7.293 3 3 7.293 1.354 5.646a.5.5 0 1 0-.708.708L2.293 8 .646 9.646a.5.5 0 0 0 .708.708L3 8.707 7.293 13l-1.647 1.646a.5.5 0 0 0 .708.708L8 13.707l1.646 1.647a.5.5 0 0 0 .708-.708L8.707 13 13 8.707l1.646 1.647a.5.5 0 0 0 .708-.708L13.707 8l1.647-1.646a.5.5 0 0 0-.708-.708L13 7.293 8.707 3l1.647-1.646ZM8 12.293 12.293 8 8 3.707 3.707 8 8 12.293Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
