/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsVectorCircle: {
  name: 'vector-circle';
  data: string;
} = {
  name: 'vector-circle',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M9 3a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v.512A9.022 9.022 0 0 1 20.488 9H21a2 2 0 0 1 2 2v2a2 2 0 0 1-2 2h-.512A9.023 9.023 0 0 1 15 20.488V21a2 2 0 0 1-2 2h-2a2 2 0 0 1-2-2v-.512A9.023 9.023 0 0 1 3.512 15H3a2 2 0 0 1-2-2v-2a2 2 0 0 1 2-2h.512A9.022 9.022 0 0 1 9 3.512V3Zm-4.765 8H5v2H3v-2h1.235Zm1.392 3.9A2 2 0 0 0 7 13v-2a2 2 0 0 0-1.373-1.9A7.03 7.03 0 0 1 9.1 5.627 2 2 0 0 0 11 7h2a2 2 0 0 0 1.9-1.373A7.031 7.031 0 0 1 18.373 9.1 2 2 0 0 0 17 11v2a2 2 0 0 0 1.373 1.9 7.03 7.03 0 0 1-3.473 3.473A2 2 0 0 0 13 17h-2a2 2 0 0 0-1.9 1.373A7.03 7.03 0 0 1 5.627 14.9ZM13 3v2h-2V3h2Zm0 16.725V19h-2v2h2v-1.275ZM19.765 11H19v2h2v-2h-1.235Z" fill="currentColor"/></svg>`,
};
