/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsVolumeSlash: {
  name: 'volume-slash';
  data: string;
} = {
  name: 'volume-slash',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.354 1.646a.5.5 0 1 0-.708.708l12 12a.5.5 0 0 0 .708-.708l-12-12ZM9.5 3a.5.5 0 0 0-.757-.429l-2 1.2a.5.5 0 0 0 .514.858L8.5 3.883V6a.5.5 0 0 0 1 0V3ZM1 5.5a.5.5 0 0 0-.5.5v4a.5.5 0 0 0 .5.5h2.862l4.88 2.929A.5.5 0 0 0 9.5 13v-2a.5.5 0 0 0-1 0v1.117L4.257 9.57A.5.5 0 0 0 4 9.5H1.5v-3H3a.5.5 0 0 0 0-1H1Zm10-2a.5.5 0 0 0 0 1 3.5 3.5 0 0 1 2.315 6.125.5.5 0 1 0 .662.75A4.5 4.5 0 0 0 11 3.5ZM10.5 6a.5.5 0 0 1 .5-.5 2.5 2.5 0 0 1 2.165 3.75.5.5 0 1 1-.865-.5A1.5 1.5 0 0 0 11 6.5a.5.5 0 0 1-.5-.5Z" fill="currentColor"/></svg>`
};
