/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsServer: {
  name: 'server';
  data: string;
} = {
  name: 'server',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 .5A1.5 1.5 0 0 0 .5 2v3c0 .384.144.735.382 1A1.494 1.494 0 0 0 .5 7v2c0 .384.144.735.382 1A1.494 1.494 0 0 0 .5 11v3A1.5 1.5 0 0 0 2 15.5h12a1.5 1.5 0 0 0 1.5-1.5v-3c0-.384-.144-.735-.382-1 .238-.265.382-.616.382-1V7c0-.384-.144-.735-.382-1 .238-.265.382-.616.382-1V2A1.5 1.5 0 0 0 14 .5H2Zm12 10H2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h12a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5Zm-12-1h12a.5.5 0 0 0 .5-.5V7a.5.5 0 0 0-.5-.5H2a.5.5 0 0 0-.5.5v2a.5.5 0 0 0 .5.5ZM1.5 2a.5.5 0 0 1 .5-.5h12a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V2ZM3 5a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm0 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm1 3a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`
};
