/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsFactory: {
  name: 'factory';
  data: string;
} = {
  name: 'factory',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M10 .5A1.5 1.5 0 0 0 8.5 2v2.5h-2V3a.5.5 0 0 0-1 0v1.5H4A1.5 1.5 0 0 0 2.5 6v3.585A1.5 1.5 0 0 0 1.5 11v3.5H1a.5.5 0 0 0 0 1h14a.5.5 0 0 0 0-1h-.566l-.938-6.563-.002-.016-.876-6.133A1.5 1.5 0 0 0 11.133.5H10Zm3.424 14-.858-6H9.5v6h3.924Zm-4.924 0v-4H3a.5.5 0 0 0-.5.5v3.5h2V13a.5.5 0 0 1 1 0v1.5h3Zm3.924-7H9.5v-2h2.638l.286 2ZM8.5 5.5v4h-5V6a.5.5 0 0 1 .5-.5h4.5Zm3.495-1-.367-2.57a.5.5 0 0 0-.495-.43H10a.5.5 0 0 0-.5.5v2.5h2.495Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
