/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsMessagingTelegram: {
  name: 'messaging-telegram';
  data: string;
} = {
  name: 'messaging-telegram',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_435_8995)"><path fill-rule="evenodd" clip-rule="evenodd" d="M15.4709 1.16817C15.5359 0.9862 15.4902 0.783075 15.3536 0.646445C15.2169 0.509816 15.0138 0.46414 14.8319 0.529128L0.831853 5.52913C0.613802 5.607 0.477742 5.8244 0.503007 6.05456C0.528272 6.28471 0.708252 6.46742 0.938004 6.49614L8.55212 7.4479L9.50388 15.062C9.5326 15.2918 9.71531 15.4717 9.94546 15.497C10.1756 15.5223 10.393 15.3862 10.4709 15.1682L15.4709 1.16817ZM8.81938 6.47353L3.14632 5.76439L13.0742 2.21873L8.81938 6.47353ZM9.52649 7.18064L10.2356 12.8537L13.7813 2.92584L9.52649 7.18064Z" fill="#6E778C"/></g><defs><clipPath id="clip0_435_8995"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`,
};
