/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsLocationDot: {
  name: 'location-dot';
  data: string;
} = {
  name: 'location-dot',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M3.5 6a4.5 4.5 0 0 1 9 0c0 2.084-1.168 4.224-2.402 5.89A21.402 21.402 0 0 1 8 14.309a21.405 21.405 0 0 1-2.098-2.419C4.668 10.224 3.5 8.084 3.5 6Zm4.165 9.371L8 15l-.334.372a.5.5 0 0 0 .668 0L8 15c.334.372.335.371.335.371h.001l.004-.004.012-.011.045-.041.165-.157a22.41 22.41 0 0 0 2.34-2.673C12.168 10.776 13.5 8.416 13.5 6a5.5 5.5 0 1 0-11 0c0 2.416 1.332 4.776 2.598 6.485a22.412 22.412 0 0 0 2.34 2.673 12.785 12.785 0 0 0 .21.198l.012.011.004.003v.001h.001ZM6.5 6a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0ZM8 3.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5Z" fill="currentColor"/></svg>`
};
