/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSeedlingCircle: {
  name: 'seedling-circle';
  data: string;
} = {
  name: 'seedling-circle',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M8 1.5a6.5 6.5 0 0 0-.5 12.981V9.478c-1.101-.098-2.051-.522-2.754-1.224C3.94 7.447 3.5 6.314 3.5 5a.5.5 0 0 1 .5-.5c1.314 0 2.447.44 3.254 1.246C8.06 6.553 8.5 7.686 8.5 9v.017c.078-.094.16-.184.246-.27C9.553 7.94 10.686 7.5 12 7.5a.5.5 0 0 1 .5.5c0 1.314-.44 2.447-1.246 3.254-.703.702-1.653 1.126-2.754 1.224v2.003A6.5 6.5 0 0 0 8 1.5ZM15.5 8a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Zm-4.954 2.546c-.493.494-1.175.826-2.016.924.098-.84.43-1.523.924-2.016.493-.494 1.175-.826 2.016-.924-.098.84-.43 1.523-.924 2.016ZM4.53 5.53c.098.84.43 1.523.924 2.016.493.494 1.175.826 2.016.924-.098-.84-.43-1.523-.924-2.016-.493-.494-1.175-.826-2.016-.924ZM10 6a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
