/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsLetterMonth: {
  name: 'letter-month';
  data: string;
} = {
  name: 'letter-month',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M2 1H3.33884L7.94421 12.3242H8.05578L12.6612 1H14V14H12.9091V3.50732H12.8099L8.52686 14H7.47314L3.19008 3.50732H3.09091V14H2V1Z" fill="#6E778C"/></svg>`,
};
