/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsOilDropletArrowsRepeatH: {
  name: 'oil-droplet-arrows-repeat-h';
  data: string;
} = {
  name: 'oil-droplet-arrows-repeat-h',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M22.707 7.293a1 1 0 0 1 0 1.414l-2 2a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414l.293.293V6a1 1 0 0 0-1-1H6a1 1 0 0 0-1 1v4a1 1 0 1 1-2 0V6a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3v1.586l.293-.293a1 1 0 0 1 1.414 0Zm-11.35-1.059a1 1 0 0 1 1.286 0C15.006 8.22 16 10.807 16 12.85c0 2.245-1.745 4.15-4 4.15s-4-1.905-4-4.15c0-2.043.994-4.63 3.357-6.616ZM12 8.366c-1.443 1.496-2 3.22-2 4.484 0 1.234.94 2.15 2 2.15s2-.916 2-2.15c0-1.263-.557-2.988-2-4.484ZM1.293 15.293a1 1 0 1 0 1.414 1.414L3 16.414V18a3 3 0 0 0 3 3h12a3 3 0 0 0 3-3v-4a1 1 0 1 0-2 0v4a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1v-1.586l.293.293a1 1 0 0 0 1.414-1.414l-2-2a1 1 0 0 0-1.414 0l-2 2Z" fill="currentColor"/></svg>`
};
