/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSquareExclamationEmpty: {
  name: 'square-exclamation-empty';
  data: string;
} = {
  name: 'square-exclamation-empty',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_414_11884)"><path fill-rule="evenodd" clip-rule="evenodd" d="M0.5 2C0.5 1.17157 1.17157 0.5 2 0.5H14C14.8284 0.5 15.5 1.17157 15.5 2V14C15.5 14.8284 14.8284 15.5 14 15.5H2C1.17157 15.5 0.5 14.8284 0.5 14V2ZM2 1.5C1.72386 1.5 1.5 1.72386 1.5 2V14C1.5 14.2761 1.72386 14.5 2 14.5H14C14.2761 14.5 14.5 14.2761 14.5 14V2C14.5 1.72386 14.2761 1.5 14 1.5H2ZM8 4C8.27614 4 8.5 4.22386 8.5 4.5V9.5C8.5 9.77614 8.27614 10 8 10C7.72386 10 7.5 9.77614 7.5 9.5V4.5C7.5 4.22386 7.72386 4 8 4ZM8 12C8.27614 12 8.5 11.7761 8.5 11.5C8.5 11.2239 8.27614 11 8 11C7.72386 11 7.5 11.2239 7.5 11.5C7.5 11.7761 7.72386 12 8 12Z" fill="#6E778C"/></g><defs><clipPath id="clip0_414_11884"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`,
};
