/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsTempSelectionUnchoice: {
  name: 'temp-selection-unchoice';
  data: string;
} = {
  name: 'temp-selection-unchoice',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 4c-1.324 0-2.57.32-3.668.888a1 1 0 0 1-.918-1.776A9.962 9.962 0 0 1 12 2c5.523 0 10 4.477 10 10a9.962 9.962 0 0 1-1.112 4.586 1 1 0 1 1-1.776-.918A8 8 0 0 0 12 4ZM4.46 6.984a1 1 0 0 1 .428 1.348 8 8 0 0 0 10.667 10.837 1 1 0 1 1 .89 1.791A9.963 9.963 0 0 1 12 22C6.477 22 2 17.523 2 12c0-1.651.4-3.212 1.112-4.586a1 1 0 0 1 1.347-.43Zm12.18 1.248a1 1 0 0 1 .128 1.408l-1 1.2a1 1 0 1 1-1.536-1.28l1-1.2a1 1 0 0 1 1.408-.128Zm-9.347 3.06a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1-1.414 1.415l-3-3a1 1 0 0 1 0-1.414Zm-1.586-7a1 1 0 0 0-1.414 1.415l14 14a1 1 0 0 0 1.414-1.414l-14-14Z" fill="currentColor"/></svg>`
};
