/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsChartsIqcZql: {
  name: 'charts-iqc-zql';
  data: string;
} = {
  name: 'charts-iqc-zql',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.5 2a.5.5 0 0 1 .5-.5h12a.5.5 0 0 1 .5.5v2.93l-2.207 1.444-1.777-1.55a.5.5 0 0 0-.74.093L8.196 7.213 6.511 3.78a.5.5 0 0 0-.921.057l-2.063 6a.5.5 0 1 0 .946.325l1.671-4.861 1.532 3.12a.5.5 0 0 0 .861.062l1.745-2.537 1.64 1.43a.5.5 0 0 0 .602.042L14.5 6.125V8.7a.5.5 0 0 0 1 0V2A1.5 1.5 0 0 0 14 .5H2A1.5 1.5 0 0 0 .5 2v12A1.5 1.5 0 0 0 2 15.5h6.7a.5.5 0 0 0 0-1H2a.5.5 0 0 1-.5-.5v-1h1a.5.5 0 0 0 0-1h-1v-2h1a.5.5 0 0 0 0-1h-1V7h1a.5.5 0 0 0 0-1h-1V4h1a.5.5 0 0 0 0-1h-1V2Zm13 10c0 .51-.152.983-.414 1.379l1.268 1.267a.5.5 0 0 1-.708.708l-1.267-1.268A2.5 2.5 0 1 1 14.5 12ZM12 10.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`
};
