/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsTableTransposeTop: {
  name: 'table-transpose-top';
  data: string;
} = {
  name: 'table-transpose-top',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_1342_9900)"><path fill-rule="evenodd" clip-rule="evenodd" d="M1 0.5C0.723858 0.5 0.5 0.723858 0.5 1V4C0.5 4.27614 0.723858 4.5 1 4.5H15C15.2761 4.5 15.5 4.27614 15.5 4V1C15.5 0.723858 15.2761 0.5 15 0.5H1ZM1.5 3.5V1.5H14.5V3.5H1.5ZM1 5.5C0.723858 5.5 0.5 5.72386 0.5 6V15C0.5 15.2761 0.723858 15.5 1 15.5H4C4.27614 15.5 4.5 15.2761 4.5 15V6C4.5 5.72386 4.27614 5.5 4 5.5H1ZM1.5 14.5V6.5H3.5V14.5H1.5ZM5.5 6C5.5 5.72386 5.72386 5.5 6 5.5H10C10.2761 5.5 10.5 5.72386 10.5 6V15C10.5 15.2761 10.2761 15.5 10 15.5H6C5.72386 15.5 5.5 15.2761 5.5 15V6ZM6.5 6.5V14.5H9.5V6.5H6.5ZM12 5.5C11.7239 5.5 11.5 5.72386 11.5 6V15C11.5 15.2761 11.7239 15.5 12 15.5H15C15.2761 15.5 15.5 15.2761 15.5 15V6C15.5 5.72386 15.2761 5.5 15 5.5H12ZM12.5 14.5V6.5H14.5V14.5H12.5Z" fill="#6E778C"/></g><defs><clipPath id="clip0_1342_9900"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`,
};
