/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsTriangleLeft: {
  name: 'triangle-left';
  data: string;
} = {
  name: 'triangle-left',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M10 12V4L6 8L10 12Z" fill="#6E778C"/></svg>`,
};
