/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsVectorPolygon: {
  name: 'vector-polygon';
  data: string;
} = {
  name: 'vector-polygon',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 1a2 2 0 0 0-2 2v2a2 2 0 0 0 2 2h.153L4.82 17.008A2 2 0 0 0 3 19v2a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2h8a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2v-2a2 2 0 0 0-2-2V9a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v1.5l-3.44 2.58A2 2 0 0 0 13 9h-2c-.18 0-.353.024-.518.068l-3.55-3.55C6.976 5.353 7 5.179 7 5V3a2 2 0 0 0-2-2H3Zm11.947 9.54c.035.148.053.302.053.46v2a2 2 0 0 1-2 2h-2a2 2 0 0 1-2-2v-2c0-.18.024-.353.068-.518l-3.55-3.55c-.11.03-.223.05-.339.06L6.847 17H7a2 2 0 0 1 2 2h8a2 2 0 0 1 2-2V9c-.51 0-.974-.19-1.328-.504l-2.725 2.044ZM19 7h2V5h-2v2ZM7 19v2H5v-2h2Zm12 2v-2h2v2h-2ZM3.984 5H5V3H3v2h.984ZM13 11h-2v2h2v-2Z" fill="currentColor"/></svg>`
};
