/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSubskritUp: {
  name: 'subskrit-up';
  data: string;
} = {
  name: 'subskrit-up',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 12H10" stroke="#6E778C" stroke-linecap="round" stroke-linejoin="round"/><path d="M2 15L7 4L12 15" stroke="#6E778C" stroke-linecap="round" stroke-linejoin="round"/><path d="M14 5H12C12 5 14 3.5 14 2" stroke="#6E778C" stroke-linecap="round" stroke-linejoin="round"/><path d="M14 2C14 1.44772 13.5523 1 13 1C12.4477 1 12 1.44772 12 2" stroke="#6E778C" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
