/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsLngStorage: {
  name: 'lng-storage';
  data: string;
} = {
  name: 'lng-storage',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M4.5.5A.5.5 0 0 0 4 1v1.493C1.833 3.834.502 6.255.5 8.995V15a.5.5 0 0 0 .5.5h2.538a.5.5 0 0 0 .5-.5v-2.071h1.539V15a.5.5 0 0 0 .5.5h3.385a.5.5 0 0 0 .5-.5v-2.071H11.5V15a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V9c0-2.742-1.332-5.165-3.5-6.507V1a.5.5 0 0 0-.5-.5h-7Zm8 11.929a.5.5 0 0 0-.5-.5H9.462a.5.5 0 0 0-.5.5V14.5H6.577v-2.071a.5.5 0 0 0-.5-.5H3.538a.5.5 0 0 0-.5.5V14.5H1.5V9c0-2.445 1.198-4.56 3.099-5.701A.5.5 0 0 0 5 3.5h6a.5.5 0 0 0 .401-.201c1.9 1.14 3.098 3.254 3.099 5.697V14.5h-2v-2.071ZM11 2.5v-1H5v1h6Z" fill="currentColor"/></svg>`
};
