/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsObjectUnion: {
  name: 'object-union';
  data: string;
} = {
  name: 'object-union',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M9 1.5H2a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .5.5h3A1.5 1.5 0 0 1 6.5 11v3a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5V7a.5.5 0 0 0-.5-.5h-3A1.5 1.5 0 0 1 9.5 5V2a.5.5 0 0 0-.5-.5Zm-7-1h7A1.5 1.5 0 0 1 10.5 2v3a.5.5 0 0 0 .5.5h3A1.5 1.5 0 0 1 15.5 7v7a1.5 1.5 0 0 1-1.5 1.5H7A1.5 1.5 0 0 1 5.5 14v-3a.5.5 0 0 0-.5-.5H2A1.5 1.5 0 0 1 .5 9V2A1.5 1.5 0 0 1 2 .5Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" transform="rotate(-180 8 8)" d="M0 0h16v16H0z"/></clipPath></defs></svg>`
};
