/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsShareRight: {
  name: 'share-right';
  data: string;
} = {
  name: 'share-right',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M12.553 3.106A1 1 0 0 1 13.6 3.2l8 6a1 1 0 0 1 0 1.6l-8 6A1 1 0 0 1 12 16v-2.029a6.516 6.516 0 0 0-2.004.457c-1.597.64-3.652 2.17-5.06 5.923A1 1 0 0 1 3 20c0-5.506 2.149-8.963 4.474-11.059A13.435 13.435 0 0 1 12 6.256V4a1 1 0 0 1 .553-.894ZM13 13l.164-.986A1 1 0 0 1 14 13v1l5.333-4L14 6v.92c0 .451-.288.929-.825 1.066-.346.09-2.404.676-4.362 2.44-1.156 1.043-2.3 2.516-3.028 4.59 1.126-1.234 2.338-1.992 3.469-2.444a8.502 8.502 0 0 1 2.71-.602 7.064 7.064 0 0 1 1.087.028l.074.01.024.003.009.002h.005L13 13Z" fill="currentColor"/></svg>`
};
