/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSquareQuestionEmpty: {
  name: 'square-question-empty';
  data: string;
} = {
  name: 'square-question-empty',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 .5A1.5 1.5 0 0 0 .5 2v12A1.5 1.5 0 0 0 2 15.5h12a1.5 1.5 0 0 0 1.5-1.5V2A1.5 1.5 0 0 0 14 .5H2ZM1.5 2a.5.5 0 0 1 .5-.5h12a.5.5 0 0 1 .5.5v12a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V2ZM8 12a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Zm0-7.5A1.5 1.5 0 0 0 6.5 6a.5.5 0 0 1-1 0 2.5 2.5 0 1 1 3.7 2.194 1.89 1.89 0 0 0-.523.402c-.125.146-.177.28-.177.404v.5a.5.5 0 0 1-1 0V9c0-.428.186-.784.418-1.055.23-.269.525-.477.8-.628A1.5 1.5 0 0 0 8 4.5Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`
};
