/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsBoxOpenArrowDown: {
  name: 'box-open-arrow-down';
  data: string;
} = {
  name: 'box-open-arrow-down',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M8 .5a.5.5 0 0 1 .5.5v6.191l1.276-.638a.5.5 0 1 1 .448.894l-2 1a.5.5 0 0 1-.448 0l-2-1a.5.5 0 1 1 .448-.894L7.5 7.19V1A.5.5 0 0 1 8 .5ZM4.447 6.776a.5.5 0 0 1-.223.671l-1.186.593 4.22 2.531A.5.5 0 0 1 7.5 11v4a.5.5 0 0 1-.757.429l-5-3A.5.5 0 0 1 1.5 12V8a.5.5 0 0 1 .276-.447l2-1a.5.5 0 0 1 .671.223ZM2.5 8.883v2.834l4 2.4v-2.834l-4-2.4Zm9.724-2.33a.5.5 0 1 0-.448.894l1.186.593-4.22 2.531A.5.5 0 0 0 8.5 11v4a.5.5 0 0 0 .757.429l5-3A.5.5 0 0 0 14.5 12V8a.5.5 0 0 0-.276-.447l-2-1ZM9.5 11.283l4-2.4v2.834l-4 2.4v-2.834Z" fill="currentColor"/></svg>`,
};
