/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsTempSelectionCheckboxMarkedCircleChanel: {
  name: 'temp-selection-checkbox-marked-circle-chanel';
  data: string;
} = {
  name: 'temp-selection-checkbox-marked-circle-chanel',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 4c-1.324 0-2.57.32-3.668.888a1 1 0 0 1-.918-1.776A9.962 9.962 0 0 1 12 2c1.651 0 3.212.4 4.586 1.112a1 1 0 0 1-.918 1.776A7.962 7.962 0 0 0 12 4ZM4.46 6.984a1 1 0 0 1 .428 1.348 8 8 0 0 0 10.667 10.837 1 1 0 1 1 .89 1.791A9.963 9.963 0 0 1 12 22C6.477 22 2 17.523 2 12c0-1.651.4-3.212 1.112-4.586a1 1 0 0 1 1.347-.43ZM20.17 8.09a1 1 0 0 1 1.274.615A9.986 9.986 0 0 1 22 12a9.962 9.962 0 0 1-1.112 4.586 1 1 0 1 1-1.776-.918A7.962 7.962 0 0 0 20 12c0-.925-.157-1.812-.444-2.636a1 1 0 0 1 .615-1.274ZM4.294 4.293a1 1 0 0 1 1.414 0l14 14a1 1 0 0 1-1.414 1.414l-14-14a1 1 0 0 1 0-1.414Zm15.454 2.371a1 1 0 0 0-1.494-1.328l-4 4.5a1 1 0 0 0 1.494 1.328l4-4.5Zm-11.04 4.629a1 1 0 0 0-1.414 1.414l3 3a1 1 0 0 0 1.414-1.414l-3-3Z" fill="currentColor"/></svg>`
};
