/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSquareBracketRight: {
  name: 'square-bracket-right';
  data: string;
} = {
  name: 'square-bracket-right',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M5 3a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2H5Zm0 2h14v14H5V5Zm6.29 4.705-.007-.008a1 1 0 0 1 1.424-1.404L12 9c.707-.707.707-.707.708-.706l.002.002.003.003.008.008.02.02.055.061a4.697 4.697 0 0 1 .599.914c.31.623.605 1.525.605 2.698s-.294 2.075-.606 2.697a4.7 4.7 0 0 1-.438.716 3.383 3.383 0 0 1-.215.26l-.02.02-.008.008-.003.003-.002.002L12 15l.707.707a1 1 0 0 1-1.424-1.404l.007-.008a2.691 2.691 0 0 0 .315-.492c.19-.378.395-.976.395-1.803s-.206-1.425-.394-1.803a2.693 2.693 0 0 0-.316-.492Z" fill="currentColor"/></svg>`,
};
