/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsLinkBreak: {
  name: 'link-break';
  data: string;
} = {
  name: 'link-break',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M3.707 2.293a1 1 0 0 0-1.414 1.414l2 2a1 1 0 0 0 1.414-1.414l-2-2Zm9.5 2.914a3.95 3.95 0 0 1 5.586 5.586l-1.5 1.5a1 1 0 0 0 1.414 1.414l1.5-1.5a5.95 5.95 0 0 0-8.414-8.414l-1.5 1.5a1 1 0 1 0 1.414 1.414l1.5-1.5Zm-6.5 6.5a1 1 0 1 0-1.414-1.414l-1.5 1.5a5.95 5.95 0 1 0 8.414 8.414l1.5-1.5a1 1 0 0 0-1.414-1.414l-1.5 1.5a3.95 3.95 0 1 1-5.586-5.586l1.5-1.5Zm13 6.586 2 2a1 1 0 0 1-1.414 1.414l-2-2a1 1 0 0 1 1.414-1.414ZM18 16a1 1 0 0 1 1-1h2a1 1 0 1 1 0 2h-2a1 1 0 0 1-1-1ZM3 7a1 1 0 0 0 0 2h2a1 1 0 0 0 0-2H3Zm13 11a1 1 0 0 1 1 1v2a1 1 0 1 1-2 0v-2a1 1 0 0 1 1-1ZM9 3a1 1 0 0 0-2 0v2a1 1 0 0 0 2 0V3Z" fill="currentColor"/></svg>`
};
