/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsArrowsMinimize: {
  name: 'arrows-minimize';
  data: string;
} = {
  name: 'arrows-minimize',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M6.5 1a.5.5 0 0 0-1 0v3.793L1.354.646a.5.5 0 1 0-.708.708L4.793 5.5H1a.5.5 0 0 0 0 1h5a.5.5 0 0 0 .5-.5V1ZM10 .5a.5.5 0 0 0-.5.5v5a.5.5 0 0 0 .5.5h5a.5.5 0 0 0 0-1h-3.793l4.147-4.146a.5.5 0 0 0-.708-.708L10.5 4.793V1a.5.5 0 0 0-.5-.5Zm-9 10a.5.5 0 0 1 0-1h5a.5.5 0 0 1 .5.5v5a.5.5 0 0 1-1 0v-3.793l-4.146 4.147a.5.5 0 0 1-.708-.708L4.793 10.5H1Zm9-1a.5.5 0 0 0-.5.5v5a.5.5 0 0 0 1 0v-3.793l4.146 4.147a.5.5 0 0 0 .708-.708L11.207 10.5H15a.5.5 0 0 0 0-1h-5Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
