/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsArrowsRotateV: {
  name: 'arrows-rotate-v';
  data: string;
} = {
  name: 'arrows-rotate-v',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M3.553.776a.5.5 0 0 1 .67-.223l2 1a.5.5 0 0 1 .224.67l-1 2a.5.5 0 1 1-.894-.447l.352-.703A5.426 5.426 0 0 0 3.658 4.35 6.366 6.366 0 0 0 2.5 8c0 1.39.464 2.665 1.158 3.65.7.99 1.607 1.651 2.463 1.865a.5.5 0 0 1-.242.97c-1.144-.286-2.237-1.125-3.037-2.26A7.366 7.366 0 0 1 1.5 8c0-1.61.536-3.085 1.342-4.226.542-.768 1.217-1.4 1.953-1.818l-1.019-.509a.5.5 0 0 1-.223-.67Zm6 1a.5.5 0 0 1 .67-.223C12.326 2.603 14.5 4.745 14.5 8c0 1.61-.536 3.085-1.341 4.226-.543.768-1.219 1.4-1.954 1.818l1.019.509a.5.5 0 1 1-.448.894l-2-1a.5.5 0 0 1-.223-.67l1-2a.5.5 0 1 1 .894.447l-.352.703a5.423 5.423 0 0 0 1.246-1.278A6.366 6.366 0 0 0 13.5 8c0-2.745-1.825-4.604-3.724-5.553a.5.5 0 0 1-.223-.67Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" transform="rotate(-90 8 8)" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
