/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsServerShield: {
  name: 'server-shield';
  data: string;
} = {
  name: 'server-shield',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 .5A1.5 1.5 0 0 0 .5 2v3c0 .384.144.735.382 1A1.494 1.494 0 0 0 .5 7v2c0 .384.144.735.382 1A1.494 1.494 0 0 0 .5 11v3A1.5 1.5 0 0 0 2 15.5h7.5a.5.5 0 0 0 0-1H2a.5.5 0 0 1-.5-.5v-3a.5.5 0 0 1 .5-.5h8.001a1.35 1.35 0 0 0-.45 1.177c.105.85.459 2.513 1.724 3.46a1.21 1.21 0 0 0 1.45 0c1.265-.947 1.619-2.61 1.725-3.46a1.35 1.35 0 0 0-.451-1.177H14A1.5 1.5 0 0 0 15.5 9V7c0-.384-.144-.735-.382-1 .238-.265.382-.616.382-1V2A1.5 1.5 0 0 0 14 .5H2Zm8 9h4a.5.5 0 0 0 .5-.5V7a.5.5 0 0 0-.5-.5H2a.5.5 0 0 0-.5.5v2a.5.5 0 0 0 .5.5h8Zm4-4H2a.5.5 0 0 1-.5-.5V2a.5.5 0 0 1 .5-.5h12a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.5.5ZM4 4a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm8.224 6.67a.5.5 0 0 0-.448 0l-1 .5c-.175.089-.25.246-.233.384.101.815.42 2.1 1.332 2.783a.21.21 0 0 0 .25 0c.913-.683 1.23-1.968 1.332-2.783.018-.138-.058-.295-.233-.383l-1-.5ZM3 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm1 3a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
