/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsVectorCircleTwoPoint: {
  name: 'vector-circle-two-point';
  data: string;
} = {
  name: 'vector-circle-two-point',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.5 8a5.5 5.5 0 0 1 10.625-2H13a1.5 1.5 0 0 0-1.5 1.5v1A1.5 1.5 0 0 0 13 10h.125A5.52 5.52 0 0 1 10 13.125V13a1.5 1.5 0 0 0-1.5-1.5h-1A1.5 1.5 0 0 0 6 13v.125A5.502 5.502 0 0 1 2.5 8Zm3.508 6.159a.5.5 0 0 1-.175-.029 6.5 6.5 0 1 1 8.297-8.297.5.5 0 0 1 .029.175A1.5 1.5 0 0 1 15.5 7.5v1a1.5 1.5 0 0 1-1.341 1.492.499.499 0 0 1-.029.175 6.517 6.517 0 0 1-3.963 3.963.499.499 0 0 1-.175.029A1.5 1.5 0 0 1 8.5 15.5h-1a1.5 1.5 0 0 1-1.492-1.341ZM13 7a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1A.5.5 0 0 0 14 7h-1Zm-5.5 5.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1A.5.5 0 0 0 9 14v-1a.5.5 0 0 0-.5-.5h-1Z" fill="currentColor"/></svg>`,
};
