/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsFloppy: {
  name: 'floppy';
  data: string;
} = {
  name: 'floppy',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M.5 2A1.5 1.5 0 0 1 2 .5h7.586a1.5 1.5 0 0 1 1.06.44l4.415 4.414a1.5 1.5 0 0 1 .439 1.06V14a1.5 1.5 0 0 1-1.5 1.5H2A1.5 1.5 0 0 1 .5 14V2Zm5 12.5h5V12a.5.5 0 0 0-.5-.5H6a.5.5 0 0 0-.5.5v2.5Zm6 0V12a1.5 1.5 0 0 0-1.5-1.5H6A1.5 1.5 0 0 0 4.5 12v2.5H2a.5.5 0 0 1-.5-.5V2a.5.5 0 0 1 .5-.5h2.5V5A1.5 1.5 0 0 0 6 6.5h3a.5.5 0 0 0 0-1H6a.5.5 0 0 1-.5-.5V1.5h4.086a.5.5 0 0 1 .353.146l4.415 4.415a.5.5 0 0 1 .146.353V14a.5.5 0 0 1-.5.5h-2.5Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`
};
