/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsShieldSlash: {
  name: 'shield-slash';
  data: string;
} = {
  name: 'shield-slash',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M12.894 2.33a2 2 0 0 0-1.788 0L8.553 3.605a1 1 0 1 0 .894 1.788L12 4.118l6.987 3.493c-.108 2.476-.86 4.616-1.86 6.4a1 1 0 1 0 1.745.978c1.13-2.018 1.997-4.473 2.114-7.33a1.962 1.962 0 0 0-1.092-1.83l-7-3.5ZM5.031 7.932a1 1 0 0 0-1.996.134c.5 7.496 6.126 12.123 7.864 13.388a1.865 1.865 0 0 0 2.203 0c.48-.35 1.22-.93 2.061-1.732a1 1 0 0 0-1.38-1.446A18.626 18.626 0 0 1 12 19.782c-1.708-1.26-6.538-5.387-6.969-11.849Zm-.324-4.64a1 1 0 0 0-1.414 1.414l16 16a1 1 0 0 0 1.414-1.414l-16-16Z" fill="currentColor"/></svg>`
};
