/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSteamBoiler: {
  name: 'steam-boiler';
  data: string;
} = {
  name: 'steam-boiler',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M5 .5a.5.5 0 0 0 0 1h3.5v4h-3V4a.5.5 0 0 0-1 0v1.5H4a.5.5 0 0 0-.5.5v2.5H2a.5.5 0 0 0 0 1h1.5v1.01a.5.5 0 0 0-.1-.01H1a.5.5 0 0 0-.5.5v4a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 .5-.5v-2.5H15a.5.5 0 0 0 .5-.5V9a.5.5 0 0 0-.5-.5h-2.5V6a.5.5 0 0 0-.5-.5H9.5V1A.5.5 0 0 0 9 .5H5Zm-.5 6h7v4h-7v-4Zm10 5h-2v-2h2v2Zm-10 0h7v3h-7v-3Zm-1 3v-3.01a.5.5 0 0 1-.1.01H1.5v3h2ZM12 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
