/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsFileCamera: {
  name: 'file-camera';
  data: string;
} = {
  name: 'file-camera',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.5 2A1.5 1.5 0 0 1 4 .5h4.586a1.5 1.5 0 0 1 1.06.44l3.415 3.414a1.5 1.5 0 0 1 .439 1.06V9a.5.5 0 0 1-1 0V5.5H10A1.5 1.5 0 0 1 8.5 4V1.5H4a.5.5 0 0 0-.5.5v7a.5.5 0 0 1-1 0V2Zm7 .207V4a.5.5 0 0 0 .5.5h1.793L9.5 2.207ZM5 9.5A1.5 1.5 0 0 0 3.5 11v3A1.5 1.5 0 0 0 5 15.5h4a1.5 1.5 0 0 0 1.5-1.5v-.191l1.276.638A.5.5 0 0 0 12.5 14v-3a.5.5 0 0 0-.724-.447l-1.276.638V11A1.5 1.5 0 0 0 9 9.5H5Zm5.5 3.191v-.382l1-.5v1.382l-1-.5Zm-1-.701V11a.5.5 0 0 0-.5-.5H5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-2.01Z" fill="currentColor"/></svg>`,
};
