/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsAirplaneSideView: {
  name: 'airplane-side-view';
  data: string;
} = {
  name: 'airplane-side-view',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M11.333 1.5a.5.5 0 0 0-.431.248L8.712 5.5H3.579L2.172 3.693a.5.5 0 0 0-.394-.193H1a.5.5 0 0 0-.492.591l.62 3.344A1.833 1.833 0 0 0 2.51 8.886l3.985.937-1.945 3.956A.5.5 0 0 0 5 14.5h1.556a.5.5 0 0 0 .352-.145l4.41-4.375h3.034c.634 0 1.148-.514 1.148-1.148 0-1.826-1.47-3.31-3.29-3.332l.288-3.458A.5.5 0 0 0 12 1.5h-.667Zm.329 5h.506A2.332 2.332 0 0 1 14.5 8.832a.148.148 0 0 1-.148.148h-3.24a.5.5 0 0 0-.353.145L6.349 13.5h-.546l1.868-3.8a.5.5 0 0 0-.334-.707L2.74 7.913a.833.833 0 0 1-.63-.66l-.488-2.638L2.94 6.307a.5.5 0 0 0 .394.193h8.329Zm-.455-1 .222-2.672L9.871 5.5h1.336Z" fill="currentColor"/></svg>`,
};
