/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsChartsIqcZql: {
  name: 'charts-iqc-zql';
  data: string;
} = {
  name: 'charts-iqc-zql',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 1a2 2 0 0 0-2 2v18a2 2 0 0 0 2 2h10a1 1 0 1 0 0-2H3v-2h1a1 1 0 1 0 0-2H3v-2h1a1 1 0 1 0 0-2H3v-2h1a1 1 0 1 0 0-2H3V7h1a1 1 0 0 0 0-2H3V3h18v4.5l-2.906 2.18-2.387-2.387a1 1 0 0 0-1.565.192L12.15 10.81l-2.23-5.203a1 1 0 0 0-1.877.107l-3 10a1 1 0 1 0 1.916.574l2.208-7.36 1.915 4.467a1 1 0 0 0 1.777.12l2.34-3.901 2.095 2.094a1 1 0 0 0 1.307.093L21 10v3a1 1 0 1 0 2 0V3a2 2 0 0 0-2-2H3Zm18.446 19.032a4 4 0 1 0-1.414 1.414l1.26 1.261a1 1 0 0 0 1.415-1.414l-1.26-1.261ZM16 18a2 2 0 1 1 4 0 2 2 0 0 1-4 0Z" fill="currentColor"/></svg>`
};
