/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsBoxOpenArrowDown: {
  name: 'box-open-arrow-down';
  data: string;
} = {
  name: 'box-open-arrow-down',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 2a1 1 0 0 1 1 1v6.131l1.445-.963a1 1 0 0 1 1.11 1.664l-3 2a1 1 0 0 1-1.11 0l-3-2a1 1 0 0 1 1.11-1.664L11 9.13V3a1 1 0 0 1 1-1ZM6.832 8.445a1 1 0 0 1-.277 1.387L4.9 10.934l5.091 2.91A2 2 0 0 1 11 15.58v3.697c0 1.535-1.659 2.498-2.992 1.736l-5-2.857A2 2 0 0 1 2 16.42V11a1 1 0 0 1 .445-.832l3-2a1 1 0 0 1 1.387.277ZM4 12.723l5 2.857v3.697L4 16.42v-3.697Zm14.555-4.555a1 1 0 0 0-1.11 1.664l1.654 1.102-5.091 2.91A2 2 0 0 0 13 15.58v3.697c0 1.535 1.659 2.498 2.992 1.736l5-2.857A2 2 0 0 0 22 16.42V11a1 1 0 0 0-.445-.832l-3-2ZM15 15.58l5-2.857v3.697l-5 2.857V15.58Z" fill="currentColor"/></svg>`
};
