/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsAngleLeft: {
  name: 'angle-left';
  data: string;
} = {
  name: 'angle-left',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M10.3123 2.60957C10.528 2.78207 10.5629 3.09672 10.3904 3.31235L6.64031 8L10.3904 12.6877C10.5629 12.9033 10.528 13.2179 10.3123 13.3904C10.0967 13.5629 9.78207 13.528 9.60957 13.3124L5.60957 8.31235C5.46348 8.12974 5.46348 7.87027 5.60957 7.68766L9.60957 2.68766C9.78207 2.47202 10.0967 2.43706 10.3123 2.60957Z" fill="currentColor"/></svg>`
};
