/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsCalculatorFunction: {
  name: 'calculator-function';
  data: string;
} = {
  name: 'calculator-function',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 .5A1.5 1.5 0 0 0 .5 2v12A1.5 1.5 0 0 0 2 15.5h5.5a.5.5 0 0 0 0-1H2a.5.5 0 0 1-.5-.5V4.5h13v2a.5.5 0 0 0 1 0V2A1.5 1.5 0 0 0 14 .5H2Zm12.5 3V2a.5.5 0 0 0-.5-.5H2a.5.5 0 0 0-.5.5v1.5h13ZM6 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-1 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm4-4a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-1 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm3 2.5V12h-.5a.5.5 0 0 1 0-1h.5V9a1.5 1.5 0 0 1 3 0 .5.5 0 0 1-1 0 .5.5 0 0 0-1 0v2h.5a.5.5 0 0 1 0 1H12v2.5a1.5 1.5 0 0 1-3 0 .5.5 0 0 1 1 0 .5.5 0 0 0 1 0Zm4.854-1.354a.5.5 0 0 1 0 .708l-.647.646.647.646a.5.5 0 0 1-.708.708l-.646-.647-.646.647a.5.5 0 0 1-.708-.708l.647-.646-.647-.646a.5.5 0 0 1 .708-.708l.646.647.646-.647a.5.5 0 0 1 .708 0Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`
};
