export * from './lazy-icon-set';
export * from './lazy-icon-set-16';
export * from './prizm-icons.component';
export * from './prizm-icons-16.component';
export * from './prizm-icons.registry';
export * from './prizm-icons-16.registry';
export * from './types';
export * from './token';
export * from './24';
