/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsArrayFill: {
  name: 'array-fill';
  data: string;
} = {
  name: 'array-fill',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_389_13162)"><path fill-rule="evenodd" clip-rule="evenodd" d="M1 0.5C0.723858 0.5 0.5 0.723858 0.5 1V15C0.5 15.2761 0.723858 15.5 1 15.5H3C3.27614 15.5 3.5 15.2761 3.5 15V1C3.5 0.723858 3.27614 0.5 3 0.5H1ZM5 0.5C4.72386 0.5 4.5 0.723858 4.5 1V15C4.5 15.2761 4.72386 15.5 5 15.5H11C11.2761 15.5 11.5 15.2761 11.5 15V1C11.5 0.723858 11.2761 0.5 11 0.5H5ZM12.5 1C12.5 0.723858 12.7239 0.5 13 0.5H15C15.2761 0.5 15.5 0.723858 15.5 1V15C15.5 15.2761 15.2761 15.5 15 15.5H13C12.7239 15.5 12.5 15.2761 12.5 15V1Z" fill="#6E778C"/></g><defs><clipPath id="clip0_389_13162"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`,
};
