/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsOilDropletArrowsAll: {
  name: 'oil-droplet-arrows-all';
  data: string;
} = {
  name: 'oil-droplet-arrows-all',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M5.646 3.646a.5.5 0 0 0 .708.708L7.5 3.207V6a.5.5 0 0 0 1 0V3.207l1.146 1.147a.5.5 0 1 0 .707-.708l-2-2a.5.5 0 0 0-.707 0l-2 2ZM2.98 11.02a.5.5 0 1 0 .707-.707L2.54 9.167h2.127a.5.5 0 0 0 0-1H2.54L3.687 7.02a.5.5 0 0 0-.707-.707l-2 2a.5.5 0 0 0 0 .707l2 2Zm9.333-4.707a.5.5 0 0 1 .707 0l2 2a.5.5 0 0 1 0 .707l-2 2a.5.5 0 1 1-.707-.707l1.146-1.146h-2.126a.5.5 0 1 1 0-1h2.127L12.313 7.02a.5.5 0 0 1 0-.707ZM10.5 11.9c0-1.312-.64-2.99-2.178-4.283a.5.5 0 0 0-.644 0C6.14 8.91 5.5 10.588 5.5 11.9c0 1.413 1.097 2.6 2.5 2.6s2.5-1.187 2.5-2.6Zm-4 0c0-.922.42-2.172 1.5-3.226 1.08 1.054 1.5 2.304 1.5 3.226 0 .907-.694 1.6-1.5 1.6s-1.5-.693-1.5-1.6Z" fill="currentColor"/></svg>`
};
