/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsTruckGarbageSideView: {
  name: 'truck-garbage-side-view';
  data: string;
} = {
  name: 'truck-garbage-side-view',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M9.06 2.646a.5.5 0 0 1 .354-.146H10.5v8H3.225a.5.5 0 0 1-.466-.32L1.7 7.427a.5.5 0 0 1 .113-.533l1.345-1.345a.5.5 0 0 1 .232-.131l3.463-.866a1.5 1.5 0 0 0 .696-.394l1.512-1.512ZM11 1.5H9.414a1.5 1.5 0 0 0-1.06.44L6.842 3.45a.5.5 0 0 1-.232.132l-3.463.866a1.5 1.5 0 0 0-.696.394L1.106 6.187a1.5 1.5 0 0 0-.34 1.599L1.81 10.5H1a.5.5 0 0 0 0 1h.768a2 2 0 1 0 3.465 0h5.535a2 2 0 1 0 3.455-.016A1.5 1.5 0 0 0 15.5 10V8.5a1.5 1.5 0 0 0-.6-1.2l-3.4-2.55V2.5H13a.5.5 0 0 0 0-1h-2Zm.5 4.5v4.5H14a.5.5 0 0 0 .5-.5V8.5a.5.5 0 0 0-.2-.4L11.5 6Zm-8 5.5a1 1 0 1 0 0 2 1 1 0 0 0 0-2Zm8 1a1 1 0 1 1 2 0 1 1 0 0 1-2 0Z" fill="currentColor"/></svg>`,
};
