/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsTempSelectionChecked: {
  name: 'temp-selection-checked';
  data: string;
} = {
  name: 'temp-selection-checked',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_6095_15)"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.5 2C1.5 1.72386 1.72386 1.5 2 1.5H11C11.2761 1.5 11.5 1.27614 11.5 1C11.5 0.723858 11.2761 0.5 11 0.5H2C1.17157 0.5 0.5 1.17157 0.5 2V14C0.5 14.8284 1.17157 15.5 2 15.5H14C14.8284 15.5 15.5 14.8284 15.5 14V7C15.5 6.72386 15.2761 6.5 15 6.5C14.7239 6.5 14.5 6.72386 14.5 7V14C14.5 14.2761 14.2761 14.5 14 14.5H2C1.72386 14.5 1.5 14.2761 1.5 14V2ZM15.3536 2.35355C15.5488 2.15829 15.5488 1.84171 15.3536 1.64645C15.1583 1.45118 14.8417 1.45118 14.6464 1.64645L7 9.29289L5.35355 7.64645C5.15829 7.45118 4.84171 7.45118 4.64645 7.64645C4.45118 7.84171 4.45118 8.15829 4.64645 8.35355L6.64645 10.3536C6.84171 10.5488 7.15829 10.5488 7.35355 10.3536L15.3536 2.35355Z" fill="currentColor"/></g><defs><clipPath id="clip0_6095_15"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`
};
