/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSampleTemplatesZql: {
  name: 'sample-templates-zql';
  data: string;
} = {
  name: 'sample-templates-zql',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M1 .5a.5.5 0 0 0 0 1h.5V13a2.5 2.5 0 0 0 5 0V1.5H7a.5.5 0 0 0 0-1H1Zm1.5 1v3h3v-3h-3Zm0 4h3V13a1.5 1.5 0 0 1-3 0V5.5Zm11 7.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0ZM11 6.207a.5.5 0 1 0-.707-.707.5.5 0 0 0 .707.707ZM11.5 11a.5.5 0 0 1 .5-.5h2a1.5 1.5 0 0 1 1.5 1.5v2a1.5 1.5 0 0 1-1.5 1.5H8a.5.5 0 0 1 0-1h6a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 0-.5-.5h-2a.5.5 0 0 1-.5-.5ZM8.086 4.879a.5.5 0 0 0 .707.707l1.414-1.414a.5.5 0 0 1 .707 0l1.414 1.414a.5.5 0 0 1 0 .707l-4.242 4.243a.5.5 0 1 0 .707.707L13.036 7a1.5 1.5 0 0 0 0-2.121L11.62 3.464a1.5 1.5 0 0 0-2.121 0L8.086 4.88Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`
};
