/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSteamTurbine: {
  name: 'steam-turbine';
  data: string;
} = {
  name: 'steam-turbine',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M13.5 1.5v2h-2V2a.5.5 0 0 0-1 0v1.5h-2V2a.5.5 0 0 0-1 0v1.5H5.49a.502.502 0 0 0 .01-.1V2A1.5 1.5 0 0 0 4 .5H2A1.5 1.5 0 0 0 .5 2v9A1.5 1.5 0 0 0 2 12.5h12a1.5 1.5 0 0 0 1.5-1.5V4a.5.5 0 0 0-.5-.5h-.5v-2h.5a.5.5 0 0 0 0-1h-2a.5.5 0 0 0 0 1h.5Zm-12 2V2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5v1.4c0 .034.003.068.01.1H1.5Zm6.5 1h6.5V11a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V4.5H8Zm-7 10a.5.5 0 0 0 0 1h14a.5.5 0 0 0 0-1H1ZM3.5 7a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.5-.5Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
