/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsCarJeepSideView: {
  name: 'car-jeep-side-view';
  data: string;
} = {
  name: 'car-jeep-side-view',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M4 9a1 1 0 0 1 1-1h8.063a1 1 0 0 1 .768.36l1.301 1.56A3 3 0 0 0 17.437 11H19a1 1 0 0 1 1 1v1.586l-.586.586A2.496 2.496 0 0 0 16.5 15H9c-.154 0-.3.035-.43.097a2.498 2.498 0 0 0-3.619-.56L4 13.586V9Zm.001 7.416-1.708-1.709A1 1 0 0 1 2 14V9a3 3 0 0 1 3-3h8.063a3 3 0 0 1 2.305 1.08l1.3 1.56a1 1 0 0 0 .769.36H19a3 3 0 0 1 3 3v2a1 1 0 0 1-.293.707l-.88.88A2.5 2.5 0 1 1 16.05 17H9.001l-.05-.002a2.5 2.5 0 0 1-4.949-.583ZM6 16.5a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0Zm12 0a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0Z" fill="currentColor"/></svg>`
};
