/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsBorderNone: {
  name: 'border-none';
  data: string;
} = {
  name: 'border-none',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M5 4a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM8 21a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm-3-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm7-15a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm1 15a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM12 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm1 3a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-1 5a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm-3-5a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm7-7a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm1 15a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm-3-9a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm3-7a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm1 3a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM4 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm17 3a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM4 13a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm17 3a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM4 17a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z" fill="currentColor"/></svg>`
};
