/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsObject: {
  name: 'object';
  data: string;
} = {
  name: 'object',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 .5A1.5 1.5 0 0 0 .5 2v3A1.5 1.5 0 0 0 2 6.5h.5v3H2A1.5 1.5 0 0 0 .5 11v3A1.5 1.5 0 0 0 2 15.5h3A1.5 1.5 0 0 0 6.5 14v-.5h3v.5a1.5 1.5 0 0 0 1.5 1.5h3a1.5 1.5 0 0 0 1.5-1.5v-3A1.5 1.5 0 0 0 14 9.5h-.5v-3h.5A1.5 1.5 0 0 0 15.5 5V2A1.5 1.5 0 0 0 14 .5h-3A1.5 1.5 0 0 0 9.5 2v.5h-3V2A1.5 1.5 0 0 0 5 .5H2Zm7.5 12h-3V11A1.5 1.5 0 0 0 5 9.5H3.5v-3H5A1.5 1.5 0 0 0 6.5 5V3.5h3V5A1.5 1.5 0 0 0 11 6.5h1.5v3H11A1.5 1.5 0 0 0 9.5 11v1.5Zm1 .5v1a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v2Zm-5 0v-2a.5.5 0 0 0-.5-.5H2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-1Zm0-11v3a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V2a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5Zm5 3V2a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
