/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsPipeNodeSideView: {
  name: 'pipe-node-side-view';
  data: string;
} = {
  name: 'pipe-node-side-view',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M7 4a1 1 0 0 0 0 2h4v2c0 .033.002.066.005.1A5.002 5.002 0 0 0 8 10H5V8a1 1 0 0 0-2 0v10a1 1 0 1 0 2 0v-2h3a4.993 4.993 0 0 0 4 2c1.637 0 3.09-.787 4-2h3v2a1 1 0 1 0 2 0V8a1 1 0 1 0-2 0v2h-3a5.002 5.002 0 0 0-3.005-1.9c.003-.034.005-.067.005-.1V6h4a1 1 0 1 0 0-2H7Zm12 8v2h-3.535a1 1 0 0 0-.866.5c-.52.899-1.49 1.5-2.599 1.5a2.998 2.998 0 0 1-2.6-1.5 1 1 0 0 0-.865-.5H5v-2h3.535a1 1 0 0 0 .866-.5C9.92 10.602 10.89 10 12 10c1.11 0 2.079.601 2.6 1.5a1 1 0 0 0 .865.5H19Z" fill="currentColor"/></svg>`,
};
