/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsArrowLeftDown: {
  name: 'arrow_left_down';
  data: string;
} = {
  name: 'arrow_left_down',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M17.7071 6.29289C18.0976 6.68342 18.0976 7.31658 17.7071 7.70711L9.41422 16H15C15.5523 16 16 16.4477 16 17C16 17.5522 15.5523 18 15 18H7C6.44772 18 6 17.5522 6 17L6 9C6 8.44772 6.44771 8 7 8C7.55228 8 8 8.44771 8 9L8 14.5858L16.2929 6.29289C16.6834 5.90237 17.3166 5.90237 17.7071 6.29289Z" fill="#6E778C"/></svg>`,
};
