/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsCubeFill: {
  name: 'cube_fill';
  data: string;
} = {
  name: 'cube_fill',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M12.8944 2.32919C12.3314 2.04766 11.6686 2.04766 11.1056 2.32919L4.10557 5.82919C3.428 6.16797 3 6.8605 3 7.61804V16.382C3 17.1395 3.428 17.832 4.10557 18.1708L11.1056 21.6708C11.6686 21.9524 12.3314 21.9524 12.8944 21.6708L19.8944 18.1708C20.572 17.832 21 17.1395 21 16.382V7.61804C21 6.8605 20.572 6.16797 19.8944 5.82919L12.8944 2.32919ZM6 8.00014L12 5.00014L18 8.00014L12 11.0001L6 8.00014Z" fill="#6E778C"/></svg>`,
};
