/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSendBackward: {
  name: 'send_backward';
  data: string;
} = {
  name: 'send_backward',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M4 2C2.89543 2 2 2.89543 2 4V17C2 17.5523 2.44772 18 3 18C3.55228 18 4 17.5523 4 17V4H17C17.5523 4 18 3.55228 18 3C18 2.44772 17.5523 2 17 2H4ZM8 6C6.89543 6 6 6.89543 6 8V20C6 21.1046 6.89543 22 8 22H20C21.1046 22 22 21.1046 22 20V8C22 6.89543 21.1046 6 20 6H8ZM8 8L20 8V20H8V8Z" fill="#6E778C"/></svg>`,
};
