/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsLaptopPhone: {
  name: 'laptop_phone';
  data: string;
} = {
  name: 'laptop_phone',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 5C3 3.89543 3.89543 3 5 3H19C20.1046 3 21 3.89543 21 5V8C21 8.55228 20.5523 9 20 9C19.4477 9 19 8.55228 19 8V5L5 5V15H12C12.5523 15 13 15.4477 13 16C13 16.5523 12.5523 17 12 17H5C3.89543 17 3 16.1046 3 15V5ZM2 20C2 19.4477 2.44772 19 3 19H12C12.5523 19 13 19.4477 13 20C13 20.5523 12.5523 21 12 21H3C2.44772 21 2 20.5523 2 20ZM16 10C14.8954 10 14 10.8954 14 12V19C14 20.1046 14.8954 21 16 21H20C21.1046 21 22 20.1046 22 19V12C22 10.8954 21.1046 10 20 10H16ZM16 12H20V19H16V12Z" fill="#6E778C"/></svg>`,
};
