/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsBracketsSquare: {
  name: 'brackets_square';
  data: string;
} = {
  name: 'brackets_square',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M4 3C2.89543 3 2 3.89543 2 5V19C2 20.1046 2.89543 21 4 21H7C7.55228 21 8 20.5523 8 20C8 19.4477 7.55228 19 7 19H4V5H7C7.55228 5 8 4.55228 8 4C8 3.44772 7.55228 3 7 3H4ZM17 3C16.4477 3 16 3.44772 16 4C16 4.55228 16.4477 5 17 5H20V19H17C16.4477 19 16 19.4477 16 20C16 20.5523 16.4477 21 17 21H20C21.1046 21 22 20.1046 22 19V5C22 3.89543 21.1046 3 20 3H17Z" fill="#6E778C"/></svg>`,
};
