/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsRhombus: {
  name: 'rhombus';
  data: string;
} = {
  name: 'rhombus',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M10.5859 2.99997C11.3669 2.21892 12.6333 2.21892 13.4143 2.99997L21.0001 10.5858C21.7811 11.3668 21.7811 12.6331 21.0001 13.4142L13.4143 21C12.6333 21.781 11.3669 21.781 10.5859 21L3.00009 13.4142C2.21904 12.6331 2.21905 11.3668 3.00009 10.5858L10.5859 2.99997ZM12.0001 4.41418L4.41431 12L12.0001 19.5858L19.5859 12L12.0001 4.41418Z" fill="#6E778C"/></svg>`,
};
