/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsArrowTurnDownRight: {
  name: 'arrow_turn_down_right';
  data: string;
} = {
  name: 'arrow_turn_down_right',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M6 6C6.55228 6 7 6.44772 7 7L7 12L15.5858 12L13.2929 9.70711C12.9024 9.31658 12.9024 8.68342 13.2929 8.29289C13.6834 7.90237 14.3166 7.90237 14.7071 8.29289L18.7071 12.2929C19.0976 12.6834 19.0976 13.3166 18.7071 13.7071L14.7071 17.7071C14.3166 18.0976 13.6834 18.0976 13.2929 17.7071C12.9024 17.3166 12.9024 16.6834 13.2929 16.2929L15.5858 14H7C5.89543 14 5 13.1046 5 12L5 7C5 6.44772 5.44772 6 6 6Z" fill="#6E778C"/></svg>`,
};
