/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsPi: {
  name: 'pi';
  data: string;
} = {
  name: 'pi',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M6 7C6 5.89543 6.89543 5 8 5H19C19.5523 5 20 4.55228 20 4C20 3.44772 19.5523 3 19 3H8C5.79086 3 4 4.79086 4 7C4 9.20914 5.79086 11 8 11C8.55228 11 9 10.5523 9 10C9 9.44772 8.55228 9 8 9C6.89543 9 6 8.10457 6 7ZM12 8C12 7.44772 11.5523 7 11 7C10.4477 7 10 7.44772 10 8L10 20C10 20.5523 10.4477 21 11 21C11.5523 21 12 20.5523 12 20L12 8ZM17 8C17 7.44772 16.5523 7 16 7C15.4477 7 15 7.44772 15 8L15 20C15 20.5523 15.4477 21 16 21C16.5523 21 17 20.5523 17 20L17 8Z" fill="#6E778C"/></svg>`,
};
