/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsPentagonFill: {
  name: 'pentagon_fill';
  data: string;
} = {
  name: 'pentagon_fill',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M13.147 2.58218C12.4584 2.10013 11.5418 2.10013 10.8532 2.58218L2.05515 8.74079C1.31366 9.25983 1.01317 10.2121 1.32248 11.0627L4.82093 20.6835C5.10834 21.4739 5.8595 22 6.70052 22H17.2997C18.1407 22 18.8918 21.4739 19.1792 20.6835L22.6777 11.0627C22.987 10.2121 22.6865 9.25983 21.945 8.74079L13.147 2.58218Z" fill="#6E778C"/></svg>`,
};
