/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsPipeline2: {
  name: 'pipeline_2';
  data: string;
} = {
  name: 'pipeline_2',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 4C3 2.89543 3.89543 2 5 2H9C10.1046 2 11 2.89543 11 4V8H15C18.3137 8 21 10.6863 21 14V20C21 21.1046 20.1046 22 19 22H15C13.8954 22 13 21.1046 13 20V16H9C5.68629 16 3 13.3137 3 10V4ZM9 4L5 4V10C5 12.2091 6.79086 14 9 14H13C14.1046 14 15 14.8954 15 16V20H19V14C19 11.7909 17.2091 10 15 10H11C9.89543 10 9 9.10457 9 8V4Z" fill="#6E778C"/></svg>`,
};
