/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsBubbleMessageAttention: {
  name: 'bubble_message_attention';
  data: string;
} = {
  name: 'bubble_message_attention',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 5C2 3.89543 2.89543 3 4 3H20C21.1046 3 22 3.89543 22 5V17C22 18.1046 21.1046 19 20 19H8.27698L3.5145 21.8575C3.20557 22.0429 2.82081 22.0477 2.5073 21.8702C2.19379 21.6927 2 21.3603 2 21V5ZM20 5H4V19.2338L7.24799 17.285C7.55882 17.0985 7.9145 17 8.27698 17H20V5ZM13 14C13 14.5523 12.5523 15 12 15C11.4477 15 11 14.5523 11 14C11 13.4477 11.4477 13 12 13C12.5523 13 13 13.4477 13 14ZM13 8C13 7.44772 12.5523 7 12 7C11.4477 7 11 7.44772 11 8V11C11 11.5523 11.4477 12 12 12C12.5523 12 13 11.5523 13 11V8Z" fill="#6E778C"/></svg>`,
};
