/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsBatteryQuarter: {
  name: 'battery_quarter';
  data: string;
} = {
  name: 'battery_quarter',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 8C2 6.89543 2.89543 6 4 6H17C18.1046 6 19 6.89543 19 8V16C19 17.1046 18.1046 18 17 18H4C2.89543 18 2 17.1046 2 16V8ZM17 8L4 8V16H17V8ZM22 9C22.5523 9 23 9.44772 23 10V14C23 14.5523 22.5523 15 22 15C21.4477 15 21 14.5523 21 14V10C21 9.44772 21.4477 9 22 9ZM7 10C7 9.44772 6.55228 9 6 9C5.44772 9 5 9.44772 5 10V14C5 14.5523 5.44772 15 6 15C6.55228 15 7 14.5523 7 14V10Z" fill="#6E778C"/></svg>`,
};
