/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsEraser: {
  name: 'eraser';
  data: string;
} = {
  name: 'eraser',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M15.4141 3C14.633 2.21895 13.3667 2.21895 12.5856 3L2.99985 12.5858C2.2188 13.3668 2.2188 14.6332 2.99985 15.4142L8.58564 21C9.36669 21.7811 10.633 21.781 11.4141 21L20.9998 11.4142C21.7809 10.6332 21.7809 9.36684 20.9998 8.58579L15.4141 3ZM7.91406 10.5L13.9998 4.41422L19.5856 10L13.4998 16.0858L7.91406 10.5ZM6.49985 11.9142L4.41406 14L9.99985 19.5858L12.0856 17.5L6.49985 11.9142Z" fill="#6E778C"/></svg>`,
};
