/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsBoilerHotWaterGasAndOil: {
  name: 'boiler-hot-water-gas-and-oil';
  data: string;
} = {
  name: 'boiler-hot-water-gas-and-oil',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 .5A2.5 2.5 0 0 0 .5 3v8A1.5 1.5 0 0 0 2 12.5h12a1.5 1.5 0 0 0 1.5-1.5V3A2.5 2.5 0 0 0 13 .5H3ZM1.5 3A1.5 1.5 0 0 1 3 1.5h10A1.5 1.5 0 0 1 14.5 3v8a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V3ZM10 6.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V7a.5.5 0 0 0-.5-.5h-3Zm.5 3v-2h2v2h-2ZM.5 15a.5.5 0 0 1 .5-.5h14a.5.5 0 0 1 0 1H1a.5.5 0 0 1-.5-.5Zm4-7a.5.5 0 0 0-1 0v2a.5.5 0 0 0 1 0V8ZM5 4a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm2 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
