/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsMicrophoneSlash: {
  name: 'microphone-slash';
  data: string;
} = {
  name: 'microphone-slash',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M8 .5A2.5 2.5 0 0 0 5.5 3v1a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 1 3 0v4a.5.5 0 0 0 1 0V3A2.5 2.5 0 0 0 8 .5Zm-.5 11.973A4.5 4.5 0 0 1 3.5 8a.5.5 0 0 1 1 0 3.5 3.5 0 0 0 4.375 3.39.5.5 0 1 1 .25.968 4.49 4.49 0 0 1-.625.114V14.5H10a.5.5 0 0 1 0 1H6a.5.5 0 0 1 0-1h1.5v-2.027ZM12.5 8a.5.5 0 0 0-1 0c0 .303-.038.596-.11.875a.5.5 0 1 0 .968.25c.093-.36.142-.737.142-1.125ZM1.646 1.646a.5.5 0 0 1 .708 0l12 12a.5.5 0 0 1-.708.708l-12-12a.5.5 0 0 1 0-.708ZM6.5 8a.5.5 0 0 0-1 0c0 .413.12 1.022.494 1.542.393.546 1.043.958 2.006.958a.5.5 0 0 0 0-1c-.637 0-.987-.254-1.194-.542A1.736 1.736 0 0 1 6.5 8Z" fill="currentColor"/></svg>`
};
