/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsFilterOntology: {
  name: 'filter-ontology';
  data: string;
} = {
  name: 'filter-ontology',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M9.748 12.788 5.699 5.5H11a1 1 0 1 0 0-2H5.7c-1.526 0-2.49 1.638-1.75 2.971L8 13.76V17a2 2 0 0 0 .8 1.6l2 1.5c1.318.989 3.2.048 3.2-1.6v-2a1 1 0 1 0-2 0v2L10 17v-3.24a2 2 0 0 0-.252-.972ZM17 5a1.5 1.5 0 1 0-2 1.415v1.17c-.426.151-.764.489-.915.915h-1.17a1.5 1.5 0 1 0 0 1h1.17c.151.426.489.764.915.915v1.17a1.5 1.5 0 1 0 1 0v-1.17c.426-.151.764-.489.915-.915h1.17a1.5 1.5 0 1 0 0-1h-1.17A1.504 1.504 0 0 0 16 7.585v-1.17A1.5 1.5 0 0 0 17 5Zm-1.5-.5a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1Zm0 4a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1ZM16 13a.5.5 0 1 0-1 0 .5.5 0 0 0 1 0Zm4-4a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0Zm-8.5.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Z" fill="currentColor"/></svg>`
};
