/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsGasMonitoring: {
  name: 'gas-monitoring';
  data: string;
} = {
  name: 'gas-monitoring',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 .5A1.5 1.5 0 0 0 .5 2v12A1.5 1.5 0 0 0 2 15.5h12a1.5 1.5 0 0 0 1.5-1.5V2A1.5 1.5 0 0 0 14 .5H2Zm12.5 12V2a.5.5 0 0 0-.5-.5H2a.5.5 0 0 0-.5.5v10.5h13Zm-13 1h13v.5a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-.5ZM4 5a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm1 2a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-1 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm2.5-7a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1H7a.5.5 0 0 1-.5-.5ZM7 6.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1H7ZM6.5 10a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1H7a.5.5 0 0 1-.5-.5Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
