/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsAirplaneSideView: {
  name: 'airplane-side-view';
  data: string;
} = {
  name: 'airplane-side-view',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M16 4.5a1 1 0 0 0-.832.445L12.465 9h-5.93L4.832 6.445A1 1 0 0 0 4 6H3a1 1 0 0 0-.98 1.196L2.78 11a3 3 0 0 0 2.118 2.296l4.574 1.307-2.33 3.882A1 1 0 0 0 8 20h2a1 1 0 0 0 .64-.232L16.362 15h3.893C21.22 15 22 14.219 22 13.255a4.256 4.256 0 0 0-4-4.247V5.5a1 1 0 0 0-1-1h-1ZM16 9V7.303L14.868 9H16Zm-2.986 2h4.731c1.159 0 2.114.875 2.24 2H16a1 1 0 0 0-.64.232l-5.466 4.554 1.963-3.272a1 1 0 0 0-.582-1.475l-5.828-1.665a1 1 0 0 1-.706-.766l-.198-.99.625.937A1 1 0 0 0 6 11h7.014Z" fill="currentColor"/></svg>`,
};
