/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsAmbulanceSideView: {
  name: 'ambulance-side-view';
  data: string;
} = {
  name: 'ambulance-side-view',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M.5 3A1.5 1.5 0 0 1 2 1.5h8A1.5 1.5 0 0 1 11.5 3v1.75l3.4 2.55c.378.283.6.728.6 1.2V10a1.5 1.5 0 0 1-1.277 1.484 2 2 0 1 1-3.429-.028.502.502 0 0 1-.147-.102A1.494 1.494 0 0 1 10 11.5H5.232a2 2 0 1 1-3.455-.016A1.5 1.5 0 0 1 .5 10V3Zm12 8.5a1 1 0 1 0 0 2 1 1 0 0 0 0-2Zm0-1H14a.5.5 0 0 0 .5-.5V8.5a.5.5 0 0 0-.2-.4L11.5 6v4c0 .175-.03.344-.085.5H12.5Zm-2.5 0H2a.5.5 0 0 1-.5-.5V3a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5Zm-7.5 2a1 1 0 1 1 2 0 1 1 0 0 1-2 0Zm4-7.5a.5.5 0 0 0-1 0v1.5H4a.5.5 0 0 0 0 1h1.5V9a.5.5 0 0 0 1 0V7.5H8a.5.5 0 0 0 0-1H6.5V5Z" fill="currentColor"/></svg>`
};
