/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSampleTemplatesZql: {
  name: 'sample-templates-zql';
  data: string;
} = {
  name: 'sample-templates-zql',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 3a1 1 0 0 1-1 1h-1v14.5a3.5 3.5 0 1 1-7 0V4H2a1 1 0 1 1 0-2h9a1 1 0 0 1 1 1ZM5 4v4h3V4H5Zm3 6H5v8.5a1.5 1.5 0 0 0 3 0V10Zm6.586-2.414A1 1 0 1 1 16 9a1 1 0 0 1-1.414-1.414ZM19 19a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm-7 2a1 1 0 0 1 1-1h7a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1h-2a1 1 0 1 1 0-2h2a3 3 0 0 1 3 3v2a3 3 0 0 1-3 3h-7a1 1 0 0 1-1-1Zm.536-7.1a1 1 0 0 0 1.414 1.414l4.95-4.95a3 3 0 0 0 0-4.243l-1.415-1.414a3 3 0 0 0-4.242 0l-1.415 1.414a1 1 0 0 0 1.415 1.414l1.414-1.414a1 1 0 0 1 1.414 0l1.414 1.414a1 1 0 0 1 0 1.415l-4.95 4.95Z" fill="currentColor"/></svg>`
};
