#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx nx-cloud record -- npx nx workspace-lint
npx nx-cloud record -- npm run check-branch-name
git fetch origin main
npx nx-cloud record -- npx nx format:check --parallel=3 --base main
npx nx affected --target=lint --parallel=3 --base main
### TODO enable after fix test in ng 12
##npx nx affected --target=test --parallel=3 --configuration=ci --base main
## TODO remove schematics excluding after update angular ng14
npx nx affected --target=build --parallel=3 --configuration=ci --base main --exclude=schematics
