#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx nx-cloud record -- npx nx workspace-lint
npx nx-cloud record -- npm run check-branch-name
npx nx-cloud record -- npx nx format:check --parallel=3 --base origin/main
npx nx affected --target=lint --parallel=3 --base origin/main
npx nx affected --target=test --parallel=3 --configuration=ci --base origin/main
npx nx affected --target=build --parallel=3 --configuration=ci --base origin/main
