/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsSpeedReductionCooling: {
  name: 'speed-reduction-cooling';
  data: string;
} = {
  name: 'speed-reduction-cooling',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M13 2a1 1 0 1 0 0 2h1v2h-.069a2 2 0 0 0-1.995 1.857L11.783 10H9a2 2 0 0 0-2 2v2H3v-3a1 1 0 1 0-2 0v3a2 2 0 0 0 2 2h4v2a2 2 0 0 0 2 2h2.074a2 2 0 0 0 2 2h3.852a2 2 0 0 0 2-2H21a2 2 0 0 0 2-2v-6a2 2 0 0 0-2-2h-2.783l-.153-2.142A2 2 0 0 0 16.069 6H16V4h1a1 1 0 1 0 0-2h-4Zm5.36 10 .428 6H21v-6h-2.64ZM9 12h2.64l-.143 2H9v-2Zm0 6v-2h2.355l-.143 2H9Zm6.001-10h-1.07l-.857 12h3.852l-.857-12H15ZM11 5a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-5 5a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z" fill="currentColor"/></svg>`
};
