/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsOilBarrel: {
  name: 'oil-barrel';
  data: string;
} = {
  name: 'oil-barrel',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M.5 1A.5.5 0 0 1 1 .5h14a.5.5 0 0 1 0 1h-1.5v2H15a.5.5 0 0 1 0 1h-1.5v7H15a.5.5 0 0 1 0 1h-1.5v2H15a.5.5 0 0 1 0 1H1a.5.5 0 0 1 0-1h1.5v-2H1a.5.5 0 0 1 0-1h1.5v-7H1a.5.5 0 0 1 0-1h1.5v-2H1A.5.5 0 0 1 .5 1Zm3 11V1.5h9v13h-9V12ZM8 6l.3-.4a.5.5 0 0 0-.6 0L8 6Zm-.626 1.27c.225-.254.452-.468.626-.621.174.153.401.367.626.62.489.55.874 1.179.874 1.731a1.5 1.5 0 1 1-3 0c0-.552.385-1.18.874-1.73ZM8 6l-.3-.4h-.001l-.002.002-.006.005-.02.015-.07.056a8.34 8.34 0 0 0-.975.928C6.115 7.18 5.5 8.051 5.5 9a2.5 2.5 0 0 0 5 0c0-.948-.615-1.82-1.126-2.395a8.34 8.34 0 0 0-1.045-.983l-.02-.015-.006-.005-.002-.001S8.3 5.6 8 6Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
