/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsCircleSquareFill: {
  name: 'circle-square-fill';
  data: string;
} = {
  name: 'circle-square-fill',
  data: `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_430_11594)"><path fill-rule="evenodd" clip-rule="evenodd" d="M5 0.5C2.51472 0.5 0.5 2.51472 0.5 5C0.5 7.48528 2.51472 9.5 5 9.5C7.48528 9.5 9.5 7.48528 9.5 5C9.5 2.51472 7.48528 0.5 5 0.5ZM10 8.5C9.17157 8.5 8.5 9.17157 8.5 10V14C8.5 14.8284 9.17157 15.5 10 15.5H14C14.8284 15.5 15.5 14.8284 15.5 14V10C15.5 9.17157 14.8284 8.5 14 8.5H10Z" fill="currentColor"/></g><defs><clipPath id="clip0_430_11594"><rect width="16" height="16" fill="white"/></clipPath></defs></svg>`,
};
