/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsMagnifyingGlassTagsWords: {
  name: 'magnifying-glass-tags-words';
  data: string;
} = {
  name: 'magnifying-glass-tags-words',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.5 7A5.5 5.5 0 0 1 7 1.5a.5.5 0 0 0 0-1 6.5 6.5 0 1 0 4.23 11.436l3.416 3.418a.5.5 0 0 0 .708-.708l-3.418-3.417c.26-.303.493-.63.694-.979a.5.5 0 1 0-.866-.5A5.5 5.5 0 0 1 1.5 7Zm9-6a.5.5 0 0 0-1 0v1.5H8a.5.5 0 0 0 0 1h1.5v2H8a.5.5 0 0 0 0 1h1.5V8a.5.5 0 0 0 1 0V6.5h2V8a.5.5 0 0 0 1 0V6.5H15a.5.5 0 0 0 0-1h-1.5v-2H15a.5.5 0 0 0 0-1h-1.5V1a.5.5 0 0 0-1 0v1.5h-2V1Zm2 4.5v-2h-2v2h2Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`
};
