/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsEyeClosed: {
  name: 'eye-closed';
  data: string;
} = {
  name: 'eye-closed',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 5C7.806 5 4.915 6.948 3.814 7.835a1.842 1.842 0 0 0-.575 2.062 9.334 9.334 0 0 0 2.083 3.365l-1.53 1.53a1 1 0 1 0 1.415 1.414l1.67-1.67A9.198 9.198 0 0 0 11 15.953a.921.921 0 0 0 0 .048v2a1 1 0 0 0 2 0v-2l-.002-.048a9.2 9.2 0 0 0 4.124-1.414l1.67 1.67a1 1 0 0 0 1.414-1.415l-1.53-1.53a9.33 9.33 0 0 0 2.084-3.365 1.842 1.842 0 0 0-.576-2.062C19.085 6.95 16.194 5 12 5Zm0 9c-3.307 0-5.808-1.912-6.842-4.677A11.217 11.217 0 0 1 12 6.999c3.452 0 5.868 1.56 6.842 2.324C17.808 12.088 15.307 14 12 14Z" fill="currentColor"/></svg>`
};
