/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsKeyboardClose: {
  name: 'keyboard-close';
  data: string;
} = {
  name: 'keyboard-close',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M15.354.646a.5.5 0 0 0-.708 0L14 1.293l-.646-.647a.5.5 0 0 0-.708.708l.647.646-.647.646a.5.5 0 0 0 .708.708L14 2.707l.646.647a.5.5 0 0 0 .708-.708L14.707 2l.647-.646a.5.5 0 0 0 0-.708ZM6 2a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm1 5a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm4-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-3 5a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm4-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm2 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2ZM9 2a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-8-.5a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1H1ZM.5 6a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1H1A.5.5 0 0 1 .5 6ZM1 9.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1H1ZM.5 14a.5.5 0 0 1 .5-.5h14a.5.5 0 0 1 0 1H1a.5.5 0 0 1-.5-.5ZM13 6.5a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2Z" fill="currentColor"/></svg>`
};
