/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsBdrvAdministration: {
  name: 'bdrv-administration';
  data: string;
} = {
  name: 'bdrv-administration',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 .5A1.5 1.5 0 0 0 .5 2v3c0 .384.144.735.382 1A1.494 1.494 0 0 0 .5 7v2c0 .384.144.735.382 1A1.494 1.494 0 0 0 .5 11v3A1.5 1.5 0 0 0 2 15.5h7.5a.5.5 0 0 0 0-1H2a.5.5 0 0 1-.5-.5v-3a.5.5 0 0 1 .5-.5h12A1.5 1.5 0 0 0 15.5 9V7c0-.384-.144-.735-.382-1 .238-.265.382-.616.382-1V2A1.5 1.5 0 0 0 14 .5H2Zm12 9H2a.5.5 0 0 1-.5-.5V7a.5.5 0 0 1 .5-.5h12a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5ZM1.5 2a.5.5 0 0 1 .5-.5h12a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V2Zm13.874 10.332a.5.5 0 1 0-.748-.664l-2.293 2.58-.96-1.08a.5.5 0 1 0-.747.664l1.334 1.5a.5.5 0 0 0 .747 0l2.667-3Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
