/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsNetworkV1: {
  name: 'network-v1';
  data: string;
} = {
  name: 'network-v1',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 .5A1.5 1.5 0 0 0 .5 2v3A1.5 1.5 0 0 0 2 6.5h1.5V12A1.5 1.5 0 0 0 5 13.5h3.5v.5a1.5 1.5 0 0 0 1.5 1.5h4a1.5 1.5 0 0 0 1.5-1.5v-3A1.5 1.5 0 0 0 14 9.5h-1.5V4A1.5 1.5 0 0 0 11 2.5H7.5V2A1.5 1.5 0 0 0 6 .5H2Zm6.5 12H5a.5.5 0 0 1-.5-.5V6.5H6A1.5 1.5 0 0 0 7.5 5V3.5H11a.5.5 0 0 1 .5.5v5.5H10A1.5 1.5 0 0 0 8.5 11v1.5Zm1 .5v1a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-4a.5.5 0 0 0-.5.5v2ZM4 5.5h2a.5.5 0 0 0 .5-.5V2a.5.5 0 0 0-.5-.5H2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h2Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`
};
