/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsHexagonExclamationFill: {
  name: 'hexagon-exclamation-fill';
  data: string;
} = {
  name: 'hexagon-exclamation-fill',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M5.414.5a1.5 1.5 0 0 0-1.06.44L.939 4.353A1.5 1.5 0 0 0 .5 5.414v5.172c0 .398.158.78.44 1.06l3.414 3.415a1.5 1.5 0 0 0 1.06.439h5.172a1.5 1.5 0 0 0 1.06-.44l3.415-3.414a1.5 1.5 0 0 0 .439-1.06V5.414a1.5 1.5 0 0 0-.44-1.06L11.647.939A1.5 1.5 0 0 0 10.586.5H5.414Zm3.086 4a.5.5 0 0 0-1 0v5a.5.5 0 0 0 1 0v-5ZM8 12a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`
};
