/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsBorderCenterV: {
  name: 'border-center-v';
  data: string;
} = {
  name: 'border-center-v',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M14 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm-2 5a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-1-5a1 1 0 1 0 0-2 1 1 0 0 0 0 2ZM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM6 2a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM3 2a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm2 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm6 6a1 1 0 1 0 0-2 1 1 0 0 0 0 2ZM8 1.5a.5.5 0 0 1 .5.5v12a.5.5 0 0 1-1 0V2a.5.5 0 0 1 .5-.5ZM15 5a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM2 6a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm13 2a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM2 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm13 2a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM2 12a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm13 2a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM2 15a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z" fill="currentColor"/></svg>`
};
