/* 🤖 this file was generated by svg-to-ts */
export const prizmIconsLineMultipleYAxis: {
  name: 'line-multiple-y-axis';
  data: string;
} = {
  name: 'line-multiple-y-axis',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M1 .5a.5.5 0 0 1 .5.5v4.793l2.146-2.147a.5.5 0 0 1 .578-.093L7.9 5.392l3.745-3.746a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.578.093L4.1 4.608 1.5 7.208v3.585l2.146-2.147a.5.5 0 0 1 .578-.093L7.9 10.392l4.745-4.746A.5.5 0 0 1 13.5 6v8.5H15a.5.5 0 0 1 0 1H1a.5.5 0 0 1-.5-.5V1A.5.5 0 0 1 1 .5Zm.5 11.707V14.5h11V7.207l-4.146 4.147a.5.5 0 0 1-.578.093L4.1 9.608l-2.599 2.6Z" fill="currentColor"/></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h16v16H0z"/></clipPath></defs></svg>`,
};
